# Crop Recommendation Model

## Load Data

In [1]:
import pandas as pd

In [2]:
data = pd.read_csv("Datasets/Crop_recommendation.csv")
data.head()

    N   P   K  temperature   humidity        ph    rainfall label
0  90  42  43    20.879744  82.002744  6.502985  202.935536  rice
1  85  58  41    21.770462  80.319644  7.038096  226.655537  rice
2  60  55  44    23.004459  82.320763  7.840207  263.964248  rice
3  74  35  40    26.491096  80.158363  6.980401  242.864034  rice
4  78  42  42    20.130175  81.604873  7.628473  262.717340  rice

In [3]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 2200 entries, 0 to 2199
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   N            2200 non-null   int64
 1   P            2200 non-null   int64
 2   K            2200 non-null   int64
 3   temperature  2200 non-null   float64
 4   humidity     2200 non-null   float64
 5   ph           2200 non-null   float64
 6   rainfall     2200 non-null   float64
 7   label        2200 non-null   str
dtypes: float64(4), int64(3), str(1)
memory usage: 137.6 KB

In [4]:
# set example
a = {1, 2, 3, 1, 1, 2, 4}
a

{1, 2, 3, 4}

In [5]:
label_names = list(set(data["label"]))
label_names

['chickpea',
 'jute',
 'kidneybeans',
 'rice',
 'papaya',
 'mango',
 'pomegranate',
 'coconut',
 'pigeonpeas',
 'mungbean',
 'maize',
 'banana',
 'watermelon',
 'muskmelon',
 'apple',
 'grapes',
 'orange',
 'blackgram',
 'mothbeans',
 'cotton',
 'lentil',
 'coffee']

In [6]:
len(label_names)

22

In [7]:
data

        N   P   K  temperature   humidity        ph    rainfall   label
0      90  42  43    20.879744  82.002744  6.502985  202.935536    rice
1      85  58  41    21.770462  80.319644  7.038096  226.655537    rice
2      60  55  44    23.004459  82.320763  7.840207  263.964248    rice
3      74  35  40    26.491096  80.158363  6.980401  242.864034    rice
4      78  42  42    20.130175  81.604873  7.628473  262.717340    rice
...   ...  ..  ..          ...        ...       ...         ...     ...
2195  107  34  32    26.774637  66.413269  6.780064  177.774507  coffee
2196   99  15  27    27.417112  56.636362  6.086922  127.924610  coffee
2197  118  33  30    24.131797  67.225123  6.362608  173.322839  coffee
2198  117  32  34    26.272418  52.127394  6.758793  127.175293  coffee
2199  104  18  30    23.603016  60.396475  6.779833  140.937041  coffee

[2200 rows x 8 columns]

# Feature
- Split our data into input and output values
- Input values will be stored in X and output values will be stored in y variables.

In [8]:
data.head()

    N   P   K  temperature   humidity        ph    rainfall label
0  90  42  43    20.879744  82.002744  6.502985  202.935536  rice
1  85  58  41    21.770462  80.319644  7.038096  226.655537  rice
2  60  55  44    23.004459  82.320763  7.840207  263.964248  rice
3  74  35  40    26.491096  80.158363  6.980401  242.864034  rice
4  78  42  42    20.130175  81.604873  7.628473  262.717340  rice

In [9]:
X = data.drop(["label"], axis=1)
y = data["label"]

In [10]:
X.head()

    N   P   K  temperature   humidity        ph    rainfall
0  90  42  43    20.879744  82.002744  6.502985  202.935536
1  85  58  41    21.770462  80.319644  7.038096  226.655537
2  60  55  44    23.004459  82.320763  7.840207  263.964248
3  74  35  40    26.491096  80.158363  6.980401  242.864034
4  78  42  42    20.130175  81.604873  7.628473  262.717340

In [11]:
y.head()

0    rice
1    rice
2    rice
3    rice
4    rice
Name: label, dtype: str

In [12]:
X.shape, y.shape

((2200, 7), (2200,))

- Let's convert 'y' variable into integer data type.

In [13]:
from sklearn.preprocessing import LabelEncoder

In [14]:
le = LabelEncoder()

y = le.fit_transform(y)
y[:5]

array([20, 20, 20, 20, 20])

- Lets convert our data variables `X` and `y` into pytorch tensors.

In [15]:
import torch

In [16]:
X_tensors = torch.tensor(X.values, dtype=torch.float)
y_tensors = torch.tensor(y, dtype=torch.long)

In [17]:
X_tensors, X_tensors.ndim, X_tensors.shape

(tensor([[ 90.0000,  42.0000,  43.0000,  ...,  82.0027,   6.5030, 202.9355],
         [ 85.0000,  58.0000,  41.0000,  ...,  80.3196,   7.0381, 226.6555],
         [ 60.0000,  55.0000,  44.0000,  ...,  82.3208,   7.8402, 263.9642],
         ...,
         [118.0000,  33.0000,  30.0000,  ...,  67.2251,   6.3626, 173.3228],
         [117.0000,  32.0000,  34.0000,  ...,  52.1274,   6.7588, 127.1753],
         [104.0000,  18.0000,  30.0000,  ...,  60.3965,   6.7798, 140.9370]]),
 2,
 torch.Size([2200, 7]))

In [18]:
y_tensors, y_tensors.ndim, y_tensors.shape

(tensor([20, 20, 20,  ...,  5,  5,  5]), 1, torch.Size([2200]))

## Train test split

In [19]:
from sklearn.model_selection import train_test_split

In [20]:
X_train, X_test, y_train, y_test = train_test_split(X_tensors, y_tensors, test_size=0.2, random_state=42)

In [21]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

(torch.Size([1760, 7]),
 torch.Size([440, 7]),
 torch.Size([1760]),
 torch.Size([440]))

# Model training

In [22]:
import torch.nn as nn

In [23]:
class CropRecommendationModel(nn.Module):
    def __init__(self):
        super(CropRecommendationModel, self).__init__()

        # layers
        self.fc1 = nn.Linear(7, 14)
        # ------ hidden layer
        self.fc2 = nn.Linear(14, 28)
        self.fc3 = nn.Linear(28, 56)
        self.fc4 = nn.Linear(56, 34)
        # -------
        self.fc5 = nn.Linear(34, 22) # output layer

    def forward(self, x):
        x = self.fc1(x) # input layer

        # hidden layer
        x = self.fc2(x)
        x = self.fc3(x)
        x = self.fc4(x)

        x = self.fc5(x) # output layer

    def forward(self, x):
        x = self.fc1(x) # input layer 
        
        # Hidden layer
        x = self.fc2(x)
        x = self.fc3(x)
        x = self.fc4(x)

        x = self.fc5(x) # output layer

        return x

In [24]:
model = CropRecommendationModel()

In [25]:
model

CropRecommendationModel(
  (fc1): Linear(in_features=7, out_features=14, bias=True)
  (fc2): Linear(in_features=14, out_features=28, bias=True)
  (fc3): Linear(in_features=28, out_features=56, bias=True)
  (fc4): Linear(in_features=56, out_features=34, bias=True)
  (fc5): Linear(in_features=34, out_features=22, bias=True)
)

In [26]:
loss_function = nn.CrossEntropyLoss()

optimizer = torch.optim.Adam(model.parameters(), lr=0.001)

In [27]:
# Training loop 
epoches = 100

for epoch in range(epoches):
    model.train()

    out = model(X_tensors)
    loss = loss_function(out, y_tensors.long().squeeze())

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    if epoch % 10 == 0 :
        print("Epoch: ", epoch, "Loss value: ", loss.item())

Epoch:  0 Loss value:  7.391234397888184
Epoch:  10 Loss value:  2.926284074783325
Epoch:  20 Loss value:  2.025489091873169
Epoch:  30 Loss value:  1.5201667547225952
Epoch:  40 Loss value:  1.209848403930664
Epoch:  50 Loss value:  0.9821112751960754
Epoch:  60 Loss value:  0.8170006275177002
Epoch:  70 Loss value:  0.6893021464347839
Epoch:  80 Loss value:  0.5903308391571045
Epoch:  90 Loss value:  0.512000560760498

In [28]:
y_pred = model(X_test).argmax(dim=1)

In [29]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, y_pred))

0.8727272727272727

# Implement on wandb

In [30]:
import wandb

In [31]:
model = CropRecommendationModel()
optimizer = torch.optim.Adam(model.parameters(), lr=0.001)

In [32]:
run = wandb.init(
    # Set the wandb entity where your project will be logged (generally your team name).
    entity="aishwaryapatil845-aish-com",
    # Set the wandb project where this run will be logged.
    project="Crop_Recommendation",
    name="Model-epoch-100",
    # Track hyperparameters and run metadata.
    config={
        "learning_rate": 0.001,
        "architecture": "FNN",
        "dataset": "crop_recommndation",
        "epochs": 100,
    },
)

# Training loop 
epoches = 100

for epoch in range(epoches):
    model.train()

    out = model(X_tensors)
    loss = loss_function(out, y_tensors.long().squeeze())

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    # accuracy
    model.eval()
    y_pred = model(X_test).argmax(dim=1)
    acc = accuracy_score(y_test, y_pred)

    if epoch % 10 == 0 :
        print("Epoch: ", epoch, "Loss value: ", loss.item())
        run.log({"loss": loss.item(), "epoch": epoch, "accuracy": acc})

wandb: ERROR Failed to detect the name of this notebook. You can set it manually with the WANDB_NOTEBOOK_NAME environment variable to enable code saving.
wandb: [wandb.login()] Loaded credentials for https://api.wandb.ai from /home/aishwarya/.netrc.
wandb: Currently logged in as: aishwaryapatil845 (aishwaryapatil845-aish-com) to https://api.wandb.ai. Use `wandb login --relogin` to force relogin

Epoch:  0 Loss value:  5.794986248016357
Epoch:  10 Loss value:  2.341503381729126
Epoch:  20 Loss value:  1.698952317237854
Epoch:  30 Loss value:  1.3026777505874634
Epoch:  40 Loss value:  1.0443819761276245
Epoch:  50 Loss value:  0.8526265025138855
Epoch:  60 Loss value:  0.7088205218315125
Epoch:  70 Loss value:  0.5944904088973999
Epoch:  80 Loss value:  0.502465546131134
Epoch:  90 Loss value:  0.4293285310268402

### Using ReLU activation function

In [33]:
class CropRecommendationModelReLU(nn.Module):
    def __init__(self):
        super(CropRecommendationModelReLU, self).__init__()

        # layers
        self.fc1 = nn.Linear(7, 14)
        self.relu1 = nn.ReLU()
        
        # ------ hidden layer
        self.fc2 = nn.Linear(14, 28)
        self.relu2 = nn.ReLU()
        self.do1 = nn.Dropout(0.2)
        
        self.fc3 = nn.Linear(28, 56)
        self.relu3 = nn.ReLU()
        self.do2 = nn.Dropout(0.2)
        
        self.fc4 = nn.Linear(56, 34)
        self.relu4 = nn.ReLU()
        self.do3 = nn.Dropout(0.1)
        # -------
        self.fc5 = nn.Linear(34, 22) # output layer

    def forward(self, x):
        x = self.fc1(x) # input layer
        x = self.relu1(x)
        

        # hidden layer
        x = self.fc2(x)
        x = self.relu2(x)
        x = self.do1(x)
        
        x = self.fc3(x)
        x = self.relu3(x)
        x = self.do2(x)
        
        x = self.fc4(x)
        x = self.relu4(x)
        x = self.do3(x)

        x = self.fc5(x) # output layer

        return x

In [34]:
model = CropRecommendationModelReLU()

In [35]:
model

CropRecommendationModelReLU(
  (fc1): Linear(in_features=7, out_features=14, bias=True)
  (relu1): ReLU()
  (fc2): Linear(in_features=14, out_features=28, bias=True)
  (relu2): ReLU()
  (do1): Dropout(p=0.2, inplace=False)
  (fc3): Linear(in_features=28, out_features=56, bias=True)
  (relu3): ReLU()
  (do2): Dropout(p=0.2, inplace=False)
  (fc4): Linear(in_features=56, out_features=34, bias=True)
  (relu4): ReLU()
  (do3): Dropout(p=0.1, inplace=False)
  (fc5): Linear(in_features=34, out_features=22, bias=True)
)

In [36]:
optimizer = torch.optim.Adam(model.parameters(), lr=0.001)

In [37]:
run = wandb.init(
    # Set the wandb entity where your project will be logged (generally your team name).
    entity="aishwaryapatil845-aish-com",
    # Set the wandb project where this run will be logged.
    project="Crop_Recommendation",
    name="Model-epoch-500-relu-dropout",
    # Track hyperparameters and run metadata.
    config={
        "learning_rate": 0.001,
        "architecture": "FNN",
        "dataset": "crop_recommndation",
        "epochs": 500,
    },
)

# Training loop 
epoches = 500

for epoch in range(epoches):
    model.train()

    out = model(X_tensors)
    loss = loss_function(out, y_tensors)

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    # accuracy
    model.eval()
    y_pred = model(X_test).argmax(dim=1)
    acc = accuracy_score(y_test, y_pred)

    if epoch % 10 == 0 :
        print("Epoch: ", epoch, "Loss value: ", loss.item())
        run.log({"loss": loss.item(), "epoch": epoch, "accuracy": acc})

Epoch:  0 Loss value:  3.4075043201446533
Epoch:  10 Loss value:  2.9907870292663574
Epoch:  20 Loss value:  2.745776891708374
Epoch:  30 Loss value:  2.4777700901031494
Epoch:  40 Loss value:  2.155073642730713
Epoch:  50 Loss value:  1.873935580253601
Epoch:  60 Loss value:  1.6566598415374756
Epoch:  70 Loss value:  1.4612520933151245
Epoch:  80 Loss value:  1.3425694704055786
Epoch:  90 Loss value:  1.210930585861206
Epoch:  100 Loss value:  1.1175220012664795
Epoch:  110 Loss value:  1.0575675964355469
Epoch:  120 Loss value:  1.0404616594314575
Epoch:  130 Loss value:  0.92586350440979
Epoch:  140 Loss value:  0.8796277642250061
Epoch:  150 Loss value:  0.8202274441719055
Epoch:  160 Loss value:  0.7644671201705933
Epoch:  170 Loss value:  0.7584009170532227
Epoch:  180 Loss value:  0.710794985294342
Epoch:  190 Loss value:  0.6867251396179199
Epoch:  200 Loss value:  0.6478351354598999
Epoch:  210 Loss value:  0.648277223110199
Epoch:  220 Loss value:  0.6221253871917725
Epoch:  230 Loss value:  0.5943616628646851
Epoch:  240 Loss value:  0.5599353313446045
Epoch:  250 Loss value:  0.5490466952323914
Epoch:  260 Loss value:  0.5083953738212585
Epoch:  270 Loss value:  0.5496922731399536
Epoch:  280 Loss value:  0.5029035806655884
Epoch:  290 Loss value:  0.4897688329219818
Epoch:  300 Loss value:  0.4558612108230591
Epoch:  310 Loss value:  0.46608152985572815
Epoch:  320 Loss value:  0.46444520354270935
Epoch:  330 Loss value:  0.4375678300857544
Epoch:  340 Loss value:  0.41441285610198975
Epoch:  350 Loss value:  0.41806554794311523
Epoch:  360 Loss value:  0.3988324701786041
Epoch:  370 Loss value:  0.4100436270236969
Epoch:  380 Loss value:  0.4151816666126251
Epoch:  390 Loss value:  0.38898298144340515
Epoch:  400 Loss value:  0.3868100941181183
Epoch:  410 Loss value:  0.38638702034950256
Epoch:  420 Loss value:  0.3731337785720825
Epoch:  430 Loss value:  0.3697327971458435
Epoch:  440 Loss value:  0.39222586154937744
Epoch:  450 Loss value:  0.3470018804073334
Epoch:  460 Loss value:  0.3590777814388275
Epoch:  470 Loss value:  0.33042529225349426
Epoch:  480 Loss value:  0.33329707384109497
Epoch:  490 Loss value:  0.3078475296497345

# Data Scaling

In [38]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

In [39]:
X_scaled = scaler.fit_transform(X_tensors)
X_scaled

array([[ 1.0687974 , -0.34455075, -0.1016875 , ...,  0.47266656,
         0.04330197,  1.81036042],
       [ 0.93332887,  0.14061552, -0.14118477, ...,  0.39705111,
         0.73487264,  2.24205783],
       [ 0.25598625,  0.04964684, -0.08193887, ...,  0.4869538 ,
         1.7715104 ,  2.92106578],
       ...,
       [ 1.82742114, -0.61745677, -0.35841972, ..., -0.19123529,
        -0.13812017,  1.27141778],
       [ 1.80032743, -0.64777967, -0.27942519, ..., -0.86951795,
         0.37390363,  0.43154519],
       [ 1.44810927, -1.07230015, -0.35841972, ..., -0.49802014,
         0.40109603,  0.68200519]], shape=(2200, 7))

In [40]:
X_scaled_tensors = torch.tensor(X_scaled, dtype=torch.float)

- Now we have scaled our data .
- Lets apply train_test_split

In [41]:
X_train, X_test, y_train, y_test = train_test_split(X_scaled_tensors, y_tensors, test_size=0.2, random_state=42)

In [42]:
model = CropRecommendationModelReLU()
optimizer = torch.optim.Adam(model.parameters(), lr=0.001)

In [43]:

run = wandb.init(
    # Set the wandb entity where your project will be logged (generally your team name).
    entity="aishwaryapatil845-aish-com",
    # Set the wandb project where this run will be logged.
    project="Crop_Recommendation",
    name="Model-epoch-500-scaled-data-new",
    # Track hyperparameters and run metadata.
    config={
        "learning_rate": 0.001,
        "architecture": "FNN",
        "dataset": "crop_recommndation",
        "epochs": 500,
    },
)

# Training loop 
epoches = 500

for epoch in range(epoches):
    model.train()

    out = model(X_train)
    loss = loss_function(out, y_train)

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    # accuracy
    model.eval()
    y_pred = model(X_test).argmax(dim=1)
    acc = accuracy_score(y_test, y_pred)

    if epoch % 10 == 0 :
        print("Epoch: ", epoch, "Loss value: ", loss.item())
        run.log({"loss": loss.item(), "epoch": epoch, "accuracy": acc})

wandb: W&B API key is configured. Use `wandb login --relogin` to force relogin

Epoch:  0 Loss value:  3.096477746963501
Epoch:  10 Loss value:  3.074800968170166
Epoch:  20 Loss value:  3.0452969074249268
Epoch:  30 Loss value:  2.988262414932251
Epoch:  40 Loss value:  2.8750529289245605
Epoch:  50 Loss value:  2.727652072906494
Epoch:  60 Loss value:  2.5449271202087402
Epoch:  70 Loss value:  2.3012471199035645
Epoch:  80 Loss value:  2.045234203338623
Epoch:  90 Loss value:  1.8235034942626953
Epoch:  100 Loss value:  1.6501739025115967
Epoch:  110 Loss value:  1.505462646484375
Epoch:  120 Loss value:  1.3590359687805176
Epoch:  130 Loss value:  1.2712204456329346
Epoch:  140 Loss value:  1.1727410554885864
Epoch:  150 Loss value:  1.08346688747406
Epoch:  160 Loss value:  1.0346919298171997
Epoch:  170 Loss value:  0.9689128398895264
Epoch:  180 Loss value:  0.9064351320266724
Epoch:  190 Loss value:  0.8293977379798889
Epoch:  200 Loss value:  0.8066613674163818
Epoch:  210 Loss value:  0.7106796503067017
Epoch:  220 Loss value:  0.6774309277534485
Epoch:  230 Loss value:  0.6454689502716064
Epoch:  240 Loss value:  0.6316921710968018
Epoch:  250 Loss value:  0.6049806475639343
Epoch:  260 Loss value:  0.5821413993835449
Epoch:  270 Loss value:  0.5842390656471252
Epoch:  280 Loss value:  0.5385156273841858
Epoch:  290 Loss value:  0.5287824273109436
Epoch:  300 Loss value:  0.5060716867446899
Epoch:  310 Loss value:  0.4981796145439148
Epoch:  320 Loss value:  0.5055767893791199
Epoch:  330 Loss value:  0.48654431104660034
Epoch:  340 Loss value:  0.46316084265708923
Epoch:  350 Loss value:  0.452477365732193
Epoch:  360 Loss value:  0.4223308265209198
Epoch:  370 Loss value:  0.448407918214798
Epoch:  380 Loss value:  0.42594054341316223
Epoch:  390 Loss value:  0.4343029856681824
Epoch:  400 Loss value:  0.4056698679924011
Epoch:  410 Loss value:  0.4088647961616516
Epoch:  420 Loss value:  0.37156060338020325
Epoch:  430 Loss value:  0.36717239022254944
Epoch:  440 Loss value:  0.3599732220172882
Epoch:  450 Loss value:  0.3644818663597107
Epoch:  460 Loss value:  0.3395870625972748
Epoch:  470 Loss value:  0.3218531608581543
Epoch:  480 Loss value:  0.32468220591545105
Epoch:  490 Loss value:  0.30436041951179504

## Increase hidden layer

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X_scaled_tensors, y_tensors, test_size=0.2, random_state=42)

In [44]:
class CropRecommendationModelMoreNeurons(nn.Module):
    def __init__(self):
        super(CropRecommendationModelMoreNeurons, self).__init__()

        # layers
        self.fc1 = nn.Linear(7, 14)
        self.relu1 = nn.ReLU()
        
        # ------ hidden layer
        self.fc2 = nn.Linear(14, 28)
        self.relu2 = nn.ReLU()
        self.do1 = nn.Dropout(0.2)
        
        self.fc3 = nn.Linear(28, 56)
        self.relu3 = nn.ReLU()
        self.do2 = nn.Dropout(0.2)
        
        self.fc4 = nn.Linear(56, 112)
        self.relu4 = nn.ReLU()
        self.do3 = nn.Dropout(0.2)
        # -------
        self.fc5 = nn.Linear(112, 56) 
        self.relu5 = nn.ReLU()
        self.do4 = nn.Dropout(0.1)

        self.fc6 = nn.Linear(56, 34)
        self.relu6 = nn.ReLU()
        self.do5 = nn.Dropout(0.1)

        # ------
        self.fc7 = nn.Linear(34, 22) # output layer
        
    def forward(self, x):
        x = self.fc1(x) # input layer
        x = self.relu1(x)
        

        # hidden layer
        x = self.fc2(x)
        x = self.relu2(x)
        x = self.do1(x)
        
        x = self.fc3(x)
        x = self.relu3(x)
        x = self.do2(x)
        
        x = self.fc4(x)
        x = self.relu4(x)
        x = self.do3(x)

        x = self.fc5(x)
        x = self.relu5(x)
        x = self.do4(x)

        x = self.fc6(x)
        x = self.relu6(x)
        x = self.do5(x)

        x = self.fc7(x) # output layer

        return x

In [45]:
model = CropRecommendationModelMoreNeurons()
optimizer = torch.optim.Adam(model.parameters(), lr=0.001)

In [46]:

run = wandb.init(
    # Set the wandb entity where your project will be logged (generally your team name).
    entity="aishwaryapatil845-aish-com",
    # Set the wandb project where this run will be logged.
    project="Crop_Recommendation",
    name="Model-epoch-500-more-neurons",
    # Track hyperparameters and run metadata.
    config={
        "learning_rate": 0.001,
        "architecture": "FNN",
        "dataset": "crop_recommndation",
        "epochs": 500,
    },
)

# Training loop 
epoches = 500

for epoch in range(epoches):
    model.train()

    out = model(X_train)
    loss = loss_function(out, y_train)

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    # accuracy
    model.eval()
    y_pred = model(X_test).argmax(dim=1)
    acc = accuracy_score(y_test, y_pred)

    if epoch % 10 == 0 :
        print("Epoch: ", epoch, "Loss value: ", loss.item())
        run.log({"loss": loss.item(), "epoch": epoch, "accuracy": acc})

Epoch:  0 Loss value:  3.094923257827759
Epoch:  10 Loss value:  3.087531328201294
Epoch:  20 Loss value:  3.0677073001861572
Epoch:  30 Loss value:  2.997974157333374
Epoch:  40 Loss value:  2.7874410152435303
Epoch:  50 Loss value:  2.5076310634613037
Epoch:  60 Loss value:  2.1649041175842285
Epoch:  70 Loss value:  1.9130603075027466
Epoch:  80 Loss value:  1.7043753862380981
Epoch:  90 Loss value:  1.586687445640564
Epoch:  100 Loss value:  1.4299242496490479
Epoch:  110 Loss value:  1.2771503925323486
Epoch:  120 Loss value:  1.1656399965286255
Epoch:  130 Loss value:  1.0835031270980835
Epoch:  140 Loss value:  1.0053064823150635
Epoch:  150 Loss value:  0.9875475764274597
Epoch:  160 Loss value:  0.9308463335037231
Epoch:  170 Loss value:  0.8771899938583374
Epoch:  180 Loss value:  0.8193437457084656
Epoch:  190 Loss value:  0.8418900966644287
Epoch:  200 Loss value:  0.7890362739562988
Epoch:  210 Loss value:  0.7743886113166809
Epoch:  220 Loss value:  0.7045037150382996
Epoch:  230 Loss value:  0.7107053995132446
Epoch:  240 Loss value:  0.6611323356628418
Epoch:  250 Loss value:  0.6243197321891785
Epoch:  260 Loss value:  0.6242856979370117
Epoch:  270 Loss value:  0.6142368912696838
Epoch:  280 Loss value:  0.6136834621429443
Epoch:  290 Loss value:  0.5960569381713867
Epoch:  300 Loss value:  0.5922130346298218
Epoch:  310 Loss value:  0.5411810278892517
Epoch:  320 Loss value:  0.49051275849342346
Epoch:  330 Loss value:  0.4915575683116913
Epoch:  340 Loss value:  0.4642215371131897
Epoch:  350 Loss value:  0.4551299810409546
Epoch:  360 Loss value:  0.4163093864917755
Epoch:  370 Loss value:  0.43049320578575134
Epoch:  380 Loss value:  0.4284769892692566
Epoch:  390 Loss value:  0.396903932094574
Epoch:  400 Loss value:  0.39502447843551636
Epoch:  410 Loss value:  0.34977760910987854
Epoch:  420 Loss value:  0.3487159311771393
Epoch:  430 Loss value:  0.36532828211784363
Epoch:  440 Loss value:  0.3421662747859955
Epoch:  450 Loss value:  0.3367697298526764
Epoch:  460 Loss value:  0.32268404960632324
Epoch:  470 Loss value:  0.322053998708725
Epoch:  480 Loss value:  0.30917489528656006
Epoch:  490 Loss value:  0.2924005687236786