# Crop Recommendation Model

## Load Data

In [1]:
import pandas as pd

In [2]:
data = pd.read_csv("Datasets/Crop_recommendation.csv")
data.head()

    N   P   K  temperature   humidity        ph    rainfall label
0  90  42  43    20.879744  82.002744  6.502985  202.935536  rice
1  85  58  41    21.770462  80.319644  7.038096  226.655537  rice
2  60  55  44    23.004459  82.320763  7.840207  263.964248  rice
3  74  35  40    26.491096  80.158363  6.980401  242.864034  rice
4  78  42  42    20.130175  81.604873  7.628473  262.717340  rice

In [3]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 2200 entries, 0 to 2199
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   N            2200 non-null   int64
 1   P            2200 non-null   int64
 2   K            2200 non-null   int64
 3   temperature  2200 non-null   float64
 4   humidity     2200 non-null   float64
 5   ph           2200 non-null   float64
 6   rainfall     2200 non-null   float64
 7   label        2200 non-null   str
dtypes: float64(4), int64(3), str(1)
memory usage: 137.6 KB

In [4]:
# set example
a = {1, 2, 3, 1, 1, 2, 4}
a

{1, 2, 3, 4}

In [5]:
label_names = list(set(data["label"]))
label_names

['mango',
 'coffee',
 'grapes',
 'muskmelon',
 'cotton',
 'apple',
 'orange',
 'chickpea',
 'coconut',
 'watermelon',
 'mungbean',
 'rice',
 'banana',
 'lentil',
 'kidneybeans',
 'blackgram',
 'maize',
 'jute',
 'pigeonpeas',
 'pomegranate',
 'mothbeans',
 'papaya']

In [6]:
len(label_names)

22

In [7]:
data

        N   P   K  temperature   humidity        ph    rainfall   label
0      90  42  43    20.879744  82.002744  6.502985  202.935536    rice
1      85  58  41    21.770462  80.319644  7.038096  226.655537    rice
2      60  55  44    23.004459  82.320763  7.840207  263.964248    rice
3      74  35  40    26.491096  80.158363  6.980401  242.864034    rice
4      78  42  42    20.130175  81.604873  7.628473  262.717340    rice
...   ...  ..  ..          ...        ...       ...         ...     ...
2195  107  34  32    26.774637  66.413269  6.780064  177.774507  coffee
2196   99  15  27    27.417112  56.636362  6.086922  127.924610  coffee
2197  118  33  30    24.131797  67.225123  6.362608  173.322839  coffee
2198  117  32  34    26.272418  52.127394  6.758793  127.175293  coffee
2199  104  18  30    23.603016  60.396475  6.779833  140.937041  coffee

[2200 rows x 8 columns]

# Feature
- Split our data into input and output values
- Input values will be stored in X and output values will be stored in y variables.

In [9]:
data.head()

    N   P   K  temperature   humidity        ph    rainfall label
0  90  42  43    20.879744  82.002744  6.502985  202.935536  rice
1  85  58  41    21.770462  80.319644  7.038096  226.655537  rice
2  60  55  44    23.004459  82.320763  7.840207  263.964248  rice
3  74  35  40    26.491096  80.158363  6.980401  242.864034  rice
4  78  42  42    20.130175  81.604873  7.628473  262.717340  rice

In [10]:
X = data.drop(["label"], axis=1)
y = data["label"]

In [11]:
X.head()

    N   P   K  temperature   humidity        ph    rainfall
0  90  42  43    20.879744  82.002744  6.502985  202.935536
1  85  58  41    21.770462  80.319644  7.038096  226.655537
2  60  55  44    23.004459  82.320763  7.840207  263.964248
3  74  35  40    26.491096  80.158363  6.980401  242.864034
4  78  42  42    20.130175  81.604873  7.628473  262.717340

In [12]:
y.head()

0    rice
1    rice
2    rice
3    rice
4    rice
Name: label, dtype: str

In [13]:
X.shape, y.shape

((2200, 7), (2200,))

- Let's convert 'y' variable into integer data type.

In [14]:
from sklearn.preprocessing import LabelEncoder

In [17]:
le = LabelEncoder()

y = le.fit_transform(y)
y[:5]

array([20, 20, 20, 20, 20])

- Lets convert our data variables `X` and `y` into pytorch tensors.

In [19]:
import torch

In [32]:
X_tensors = torch.tensor(X.values, dtype=torch.float)
y_tensors = torch.tensor(y, dtype=torch.long)

In [33]:
X_tensors, X_tensors.ndim, X_tensors.shape

(tensor([[ 90.0000,  42.0000,  43.0000,  ...,  82.0027,   6.5030, 202.9355],
         [ 85.0000,  58.0000,  41.0000,  ...,  80.3196,   7.0381, 226.6555],
         [ 60.0000,  55.0000,  44.0000,  ...,  82.3208,   7.8402, 263.9642],
         ...,
         [118.0000,  33.0000,  30.0000,  ...,  67.2251,   6.3626, 173.3228],
         [117.0000,  32.0000,  34.0000,  ...,  52.1274,   6.7588, 127.1753],
         [104.0000,  18.0000,  30.0000,  ...,  60.3965,   6.7798, 140.9370]]),
 2,
 torch.Size([2200, 7]))

In [34]:
y_tensors, y_tensors.ndim, y_tensors.shape

(tensor([20, 20, 20,  ...,  5,  5,  5]), 1, torch.Size([2200]))

## Train test split

In [35]:
from sklearn.model_selection import train_test_split

In [36]:
X_train, X_test, y_train, y_test = train_test_split(X_tensors, y_tensors, test_size=0.2, random_state=42)

In [37]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

(torch.Size([1760, 7]),
 torch.Size([440, 7]),
 torch.Size([1760]),
 torch.Size([440]))

# Model training

In [38]:
import torch.nn as nn

In [49]:
class CropRecommendationModel(nn.Module):
    def __init__(self):
        super(CropRecommendationModel, self).__init__()

        # layers
        self.fc1 = nn.Linear(7, 14)
        # ------ hidden layer
        self.fc2 = nn.Linear(14, 28)
        self.fc3 = nn.Linear(28, 56)
        self.fc4 = nn.Linear(56, 34)
        # -------
        self.fc5 = nn.Linear(34, 22) # output layer

    def forward(self, x):
        x = self.fc1(x) # input layer

        # hidden layer
        x = self.fc2(x)
        x = self.fc3(x)
        x = self.fc4(x)

        x = self.fc5(x) # output layer

    def forward(self, x):
        x = self.fc1(x) # input layer 
        
        # Hidden layer
        x = self.fc2(x)
        x = self.fc3(x)
        x = self.fc4(x)

        x = self.fc5(x) # output layer

        return x

In [50]:
model = CropRecommendationModel()

In [51]:
model

CropRecommendationModel(
  (fc1): Linear(in_features=7, out_features=14, bias=True)
  (fc2): Linear(in_features=14, out_features=28, bias=True)
  (fc3): Linear(in_features=28, out_features=56, bias=True)
  (fc4): Linear(in_features=56, out_features=34, bias=True)
  (fc5): Linear(in_features=34, out_features=22, bias=True)
)

In [52]:
loss_function = nn.CrossEntropyLoss()

optimizer = torch.optim.Adam(model.parameters(), lr=0.001)

In [53]:
# Training loop 
epoches = 100

for epoch in range(epoches):
    model.train()

    out = model(X_tensors)
    loss = loss_function(out, y_tensors.long().squeeze())

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    if epoch % 10 == 0 :
        print("Epoch: ", epoch, "Loss value: ", loss.item())

Epoch:  0 Loss value:  7.333548545837402
Epoch:  10 Loss value:  2.9855496883392334
Epoch:  20 Loss value:  2.0402040481567383
Epoch:  30 Loss value:  1.6334699392318726
Epoch:  40 Loss value:  1.3150845766067505
Epoch:  50 Loss value:  1.0623359680175781
Epoch:  60 Loss value:  0.861183762550354
Epoch:  70 Loss value:  0.7012999057769775
Epoch:  80 Loss value:  0.5781705379486084
Epoch:  90 Loss value:  0.48431816697120667

In [54]:
y_pred = model(X_test).argmax(dim=1)

In [55]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, y_pred))

0.884090909090909

# Implement on wandb

In [56]:
import wandb

In [57]:
model = CropRecommendationModel()
optimizer = torch.optim.Adam(model.parameters(), lr=0.001)

In [59]:
run = wandb.init(
    # Set the wandb entity where your project will be logged (generally your team name).
    entity="aishwaryapatil845-aish-com",
    # Set the wandb project where this run will be logged.
    project="Crop_Recommendation",
    name="Model-epoch-100",
    # Track hyperparameters and run metadata.
    config={
        "learning_rate": 0.001,
        "architecture": "FNN",
        "dataset": "crop_recommndation",
        "epochs": 100,
    },
)

# Training loop 
epoches = 100

for epoch in range(epoches):
    model.train()

    out = model(X_tensors)
    loss = loss_function(out, y_tensors.long().squeeze())

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    # accuracy
    model.eval()
    y_pred = model(X_test).argmax(dim=1)
    acc = accuracy_score(y_test, y_pred)

    if epoch % 10 == 0 :
        print("Epoch: ", epoch, "Loss value: ", loss.item())
        run.log({"loss": loss.item(), "epoch": epoch, "accuracy": acc})

wandb: ERROR Failed to detect the name of this notebook. You can set it manually with the WANDB_NOTEBOOK_NAME environment variable to enable code saving.
wandb: [wandb.login()] Loaded credentials for https://api.wandb.ai from /home/aishwarya/.netrc.
wandb: W&B API key is configured. Use `wandb login --relogin` to force relogin

Epoch:  0 Loss value:  6.811892032623291
Epoch:  10 Loss value:  2.54935884475708
Epoch:  20 Loss value:  1.8115451335906982
Epoch:  30 Loss value:  1.3938188552856445
Epoch:  40 Loss value:  1.1192419528961182
Epoch:  50 Loss value:  0.8991709351539612
Epoch:  60 Loss value:  0.7322045564651489
Epoch:  70 Loss value:  0.6071386337280273
Epoch:  80 Loss value:  0.5126942992210388
Epoch:  90 Loss value:  0.43990710377693176