# Crop Recommendation Model

## Load Data

In [1]:
import pandas as pd

In [2]:
data = pd.read_csv("Datasets/Crop_recommendation.csv")
data.head()

    N   P   K  temperature   humidity        ph    rainfall label
0  90  42  43    20.879744  82.002744  6.502985  202.935536  rice
1  85  58  41    21.770462  80.319644  7.038096  226.655537  rice
2  60  55  44    23.004459  82.320763  7.840207  263.964248  rice
3  74  35  40    26.491096  80.158363  6.980401  242.864034  rice
4  78  42  42    20.130175  81.604873  7.628473  262.717340  rice

In [3]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 2200 entries, 0 to 2199
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   N            2200 non-null   int64
 1   P            2200 non-null   int64
 2   K            2200 non-null   int64
 3   temperature  2200 non-null   float64
 4   humidity     2200 non-null   float64
 5   ph           2200 non-null   float64
 6   rainfall     2200 non-null   float64
 7   label        2200 non-null   str
dtypes: float64(4), int64(3), str(1)
memory usage: 137.6 KB

In [4]:
# set example
a = {1, 2, 3, 1, 1, 2, 4}
a

{1, 2, 3, 4}

In [5]:
label_names = list(set(data["label"]))
label_names

['cotton',
 'rice',
 'papaya',
 'grapes',
 'muskmelon',
 'apple',
 'watermelon',
 'pigeonpeas',
 'mungbean',
 'chickpea',
 'kidneybeans',
 'coffee',
 'mango',
 'mothbeans',
 'lentil',
 'maize',
 'pomegranate',
 'coconut',
 'blackgram',
 'orange',
 'jute',
 'banana']

In [6]:
len(label_names)

22

In [7]:
data

        N   P   K  temperature   humidity        ph    rainfall   label
0      90  42  43    20.879744  82.002744  6.502985  202.935536    rice
1      85  58  41    21.770462  80.319644  7.038096  226.655537    rice
2      60  55  44    23.004459  82.320763  7.840207  263.964248    rice
3      74  35  40    26.491096  80.158363  6.980401  242.864034    rice
4      78  42  42    20.130175  81.604873  7.628473  262.717340    rice
...   ...  ..  ..          ...        ...       ...         ...     ...
2195  107  34  32    26.774637  66.413269  6.780064  177.774507  coffee
2196   99  15  27    27.417112  56.636362  6.086922  127.924610  coffee
2197  118  33  30    24.131797  67.225123  6.362608  173.322839  coffee
2198  117  32  34    26.272418  52.127394  6.758793  127.175293  coffee
2199  104  18  30    23.603016  60.396475  6.779833  140.937041  coffee

[2200 rows x 8 columns]

# Feature
- Split our data into input and output values
- Input values will be stored in X and output values will be stored in y variables.

In [8]:
data.head()

    N   P   K  temperature   humidity        ph    rainfall label
0  90  42  43    20.879744  82.002744  6.502985  202.935536  rice
1  85  58  41    21.770462  80.319644  7.038096  226.655537  rice
2  60  55  44    23.004459  82.320763  7.840207  263.964248  rice
3  74  35  40    26.491096  80.158363  6.980401  242.864034  rice
4  78  42  42    20.130175  81.604873  7.628473  262.717340  rice

In [9]:
X = data.drop(["label"], axis=1)
y = data["label"]

In [10]:
X.head()

    N   P   K  temperature   humidity        ph    rainfall
0  90  42  43    20.879744  82.002744  6.502985  202.935536
1  85  58  41    21.770462  80.319644  7.038096  226.655537
2  60  55  44    23.004459  82.320763  7.840207  263.964248
3  74  35  40    26.491096  80.158363  6.980401  242.864034
4  78  42  42    20.130175  81.604873  7.628473  262.717340

In [11]:
y.head()

0    rice
1    rice
2    rice
3    rice
4    rice
Name: label, dtype: str

In [12]:
X.shape, y.shape

((2200, 7), (2200,))

- Let's convert 'y' variable into integer data type.

In [13]:
from sklearn.preprocessing import LabelEncoder

In [14]:
le = LabelEncoder()

y = le.fit_transform(y)
y[:5]

array([20, 20, 20, 20, 20])

- Lets convert our data variables `X` and `y` into pytorch tensors.

In [15]:
import torch

In [16]:
X_tensors = torch.tensor(X.values, dtype=torch.float)
y_tensors = torch.tensor(y, dtype=torch.long)

In [17]:
X_tensors, X_tensors.ndim, X_tensors.shape

(tensor([[ 90.0000,  42.0000,  43.0000,  ...,  82.0027,   6.5030, 202.9355],
         [ 85.0000,  58.0000,  41.0000,  ...,  80.3196,   7.0381, 226.6555],
         [ 60.0000,  55.0000,  44.0000,  ...,  82.3208,   7.8402, 263.9642],
         ...,
         [118.0000,  33.0000,  30.0000,  ...,  67.2251,   6.3626, 173.3228],
         [117.0000,  32.0000,  34.0000,  ...,  52.1274,   6.7588, 127.1753],
         [104.0000,  18.0000,  30.0000,  ...,  60.3965,   6.7798, 140.9370]]),
 2,
 torch.Size([2200, 7]))

In [18]:
y_tensors, y_tensors.ndim, y_tensors.shape

(tensor([20, 20, 20,  ...,  5,  5,  5]), 1, torch.Size([2200]))

## Train test split

In [19]:
from sklearn.model_selection import train_test_split

In [20]:
X_train, X_test, y_train, y_test = train_test_split(X_tensors, y_tensors, test_size=0.2, random_state=42)

In [21]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

(torch.Size([1760, 7]),
 torch.Size([440, 7]),
 torch.Size([1760]),
 torch.Size([440]))

# Model training

In [22]:
import torch.nn as nn

In [23]:
class CropRecommendationModel(nn.Module):
    def __init__(self):
        super(CropRecommendationModel, self).__init__()

        # layers
        self.fc1 = nn.Linear(7, 14)
        # ------ hidden layer
        self.fc2 = nn.Linear(14, 28)
        self.fc3 = nn.Linear(28, 56)
        self.fc4 = nn.Linear(56, 34)
        # -------
        self.fc5 = nn.Linear(34, 22) # output layer

    def forward(self, x):
        x = self.fc1(x) # input layer

        # hidden layer
        x = self.fc2(x)
        x = self.fc3(x)
        x = self.fc4(x)

        x = self.fc5(x) # output layer

    def forward(self, x):
        x = self.fc1(x) # input layer 
        
        # Hidden layer
        x = self.fc2(x)
        x = self.fc3(x)
        x = self.fc4(x)

        x = self.fc5(x) # output layer

        return x

In [24]:
model = CropRecommendationModel()

In [25]:
model

CropRecommendationModel(
  (fc1): Linear(in_features=7, out_features=14, bias=True)
  (fc2): Linear(in_features=14, out_features=28, bias=True)
  (fc3): Linear(in_features=28, out_features=56, bias=True)
  (fc4): Linear(in_features=56, out_features=34, bias=True)
  (fc5): Linear(in_features=34, out_features=22, bias=True)
)

In [26]:
loss_function = nn.CrossEntropyLoss()

optimizer = torch.optim.Adam(model.parameters(), lr=0.001)

In [27]:
# Training loop 
epoches = 100

for epoch in range(epoches):
    model.train()

    out = model(X_tensors)
    loss = loss_function(out, y_tensors.long().squeeze())

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    if epoch % 10 == 0 :
        print("Epoch: ", epoch, "Loss value: ", loss.item())

Epoch:  0 Loss value:  8.878954887390137
Epoch:  10 Loss value:  2.9194064140319824
Epoch:  20 Loss value:  2.101060628890991
Epoch:  30 Loss value:  1.6371562480926514
Epoch:  40 Loss value:  1.3632235527038574
Epoch:  50 Loss value:  1.1494251489639282
Epoch:  60 Loss value:  0.9766015410423279
Epoch:  70 Loss value:  0.8363673090934753
Epoch:  80 Loss value:  0.7229306697845459
Epoch:  90 Loss value:  0.6321389079093933

In [28]:
y_pred = model(X_test).argmax(dim=1)

In [29]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, y_pred))

0.8386363636363636

# Implement on wandb

In [30]:
import wandb

In [31]:
model = CropRecommendationModel()
optimizer = torch.optim.Adam(model.parameters(), lr=0.001)

In [32]:
run = wandb.init(
    # Set the wandb entity where your project will be logged (generally your team name).
    entity="aishwaryapatil845-aish-com",
    # Set the wandb project where this run will be logged.
    project="Crop_Recommendation",
    name="Model-epoch-100",
    # Track hyperparameters and run metadata.
    config={
        "learning_rate": 0.001,
        "architecture": "FNN",
        "dataset": "crop_recommndation",
        "epochs": 100,
    },
)

# Training loop 
epoches = 100

for epoch in range(epoches):
    model.train()

    out = model(X_tensors)
    loss = loss_function(out, y_tensors.long().squeeze())

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    # accuracy
    model.eval()
    y_pred = model(X_test).argmax(dim=1)
    acc = accuracy_score(y_test, y_pred)

    if epoch % 10 == 0 :
        print("Epoch: ", epoch, "Loss value: ", loss.item())
        run.log({"loss": loss.item(), "epoch": epoch, "accuracy": acc})

wandb: ERROR Failed to detect the name of this notebook. You can set it manually with the WANDB_NOTEBOOK_NAME environment variable to enable code saving.
wandb: [wandb.login()] Loaded credentials for https://api.wandb.ai from /home/aishwarya/.netrc.
wandb: Currently logged in as: aishwaryapatil845 (aishwaryapatil845-aish-com) to https://api.wandb.ai. Use `wandb login --relogin` to force relogin

Epoch:  0 Loss value:  9.31525707244873
Epoch:  10 Loss value:  3.140000343322754
Epoch:  20 Loss value:  2.2627012729644775
Epoch:  30 Loss value:  1.8019658327102661
Epoch:  40 Loss value:  1.4659464359283447
Epoch:  50 Loss value:  1.2216438055038452
Epoch:  60 Loss value:  1.0205583572387695
Epoch:  70 Loss value:  0.8522229194641113
Epoch:  80 Loss value:  0.7160545587539673
Epoch:  90 Loss value:  0.6083643436431885

### Using ReLU activation function

In [33]:
class CropRecommendationModelReLU(nn.Module):
    def __init__(self):
        super(CropRecommendationModelReLU, self).__init__()

        # layers
        self.fc1 = nn.Linear(7, 14)
        self.relu1 = nn.ReLU()
        
        # ------ hidden layer
        self.fc2 = nn.Linear(14, 28)
        self.relu2 = nn.ReLU()
        self.do1 = nn.Dropout(0.2)
        
        self.fc3 = nn.Linear(28, 56)
        self.relu3 = nn.ReLU()
        self.do2 = nn.Dropout(0.2)
        
        self.fc4 = nn.Linear(56, 34)
        self.relu4 = nn.ReLU()
        self.do3 = nn.Dropout(0.1)
        # -------
        self.fc5 = nn.Linear(34, 22) # output layer

    def forward(self, x):
        x = self.fc1(x) # input layer
        x = self.relu1(x)
        

        # hidden layer
        x = self.fc2(x)
        x = self.relu2(x)
        x = self.do1(x)
        
        x = self.fc3(x)
        x = self.relu3(x)
        x = self.do2(x)
        
        x = self.fc4(x)
        x = self.relu4(x)
        x = self.do3(x)

        x = self.fc5(x) # output layer

        return x

In [34]:
model = CropRecommendationModelReLU()

In [35]:
model

CropRecommendationModelReLU(
  (fc1): Linear(in_features=7, out_features=14, bias=True)
  (relu1): ReLU()
  (fc2): Linear(in_features=14, out_features=28, bias=True)
  (relu2): ReLU()
  (do1): Dropout(p=0.2, inplace=False)
  (fc3): Linear(in_features=28, out_features=56, bias=True)
  (relu3): ReLU()
  (do2): Dropout(p=0.2, inplace=False)
  (fc4): Linear(in_features=56, out_features=34, bias=True)
  (relu4): ReLU()
  (do3): Dropout(p=0.1, inplace=False)
  (fc5): Linear(in_features=34, out_features=22, bias=True)
)

In [36]:
optimizer = torch.optim.Adam(model.parameters(), lr=0.001)

In [37]:
run = wandb.init(
    # Set the wandb entity where your project will be logged (generally your team name).
    entity="aishwaryapatil845-aish-com",
    # Set the wandb project where this run will be logged.
    project="Crop_Recommendation",
    name="Model-epoch-500-relu-dropout",
    # Track hyperparameters and run metadata.
    config={
        "learning_rate": 0.001,
        "architecture": "FNN",
        "dataset": "crop_recommndation",
        "epochs": 500,
    },
)

# Training loop 
epoches = 500

for epoch in range(epoches):
    model.train()

    out = model(X_tensors)
    loss = loss_function(out, y_tensors)

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    # accuracy
    model.eval()
    y_pred = model(X_test).argmax(dim=1)
    acc = accuracy_score(y_test, y_pred)

    if epoch % 10 == 0 :
        print("Epoch: ", epoch, "Loss value: ", loss.item())
        run.log({"loss": loss.item(), "epoch": epoch, "accuracy": acc})

Epoch:  0 Loss value:  3.3611056804656982
Epoch:  10 Loss value:  2.91513729095459
Epoch:  20 Loss value:  2.673192262649536
Epoch:  30 Loss value:  2.377135753631592
Epoch:  40 Loss value:  2.0668821334838867
Epoch:  50 Loss value:  1.8262720108032227
Epoch:  60 Loss value:  1.6366795301437378
Epoch:  70 Loss value:  1.4706857204437256
Epoch:  80 Loss value:  1.3549813032150269
Epoch:  90 Loss value:  1.2009940147399902
Epoch:  100 Loss value:  1.1459907293319702
Epoch:  110 Loss value:  1.0935158729553223
Epoch:  120 Loss value:  1.0327879190444946
Epoch:  130 Loss value:  0.962049126625061
Epoch:  140 Loss value:  0.9229065179824829
Epoch:  150 Loss value:  0.9002360701560974
Epoch:  160 Loss value:  0.8217368125915527
Epoch:  170 Loss value:  0.7926322221755981
Epoch:  180 Loss value:  0.7458497285842896
Epoch:  190 Loss value:  0.7337234020233154
Epoch:  200 Loss value:  0.6851602792739868
Epoch:  210 Loss value:  0.6345052719116211
Epoch:  220 Loss value:  0.6353235244750977
Epoch:  230 Loss value:  0.6242120862007141
Epoch:  240 Loss value:  0.580241322517395
Epoch:  250 Loss value:  0.540026843547821
Epoch:  260 Loss value:  0.5732385516166687
Epoch:  270 Loss value:  0.5649241209030151
Epoch:  280 Loss value:  0.5060606598854065
Epoch:  290 Loss value:  0.4952446520328522
Epoch:  300 Loss value:  0.4745117127895355
Epoch:  310 Loss value:  0.4762956202030182
Epoch:  320 Loss value:  0.4449099898338318
Epoch:  330 Loss value:  0.44770973920822144
Epoch:  340 Loss value:  0.41723009943962097
Epoch:  350 Loss value:  0.4314541518688202
Epoch:  360 Loss value:  0.39645645022392273
Epoch:  370 Loss value:  0.4004610776901245
Epoch:  380 Loss value:  0.42791447043418884
Epoch:  390 Loss value:  0.39627015590667725
Epoch:  400 Loss value:  0.37634479999542236
Epoch:  410 Loss value:  0.3817584812641144
Epoch:  420 Loss value:  0.36668431758880615
Epoch:  430 Loss value:  0.3484231233596802
Epoch:  440 Loss value:  0.37024298310279846
Epoch:  450 Loss value:  0.34893685579299927
Epoch:  460 Loss value:  0.3559054136276245
Epoch:  470 Loss value:  0.33497175574302673
Epoch:  480 Loss value:  0.33975037932395935
Epoch:  490 Loss value:  0.3556019067764282

# Data Scaling

In [38]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

In [39]:
X_scaled = scaler.fit_transform(X_tensors)
X_scaled

array([[ 1.0687974 , -0.34455075, -0.1016875 , ...,  0.47266656,
         0.04330197,  1.81036042],
       [ 0.93332887,  0.14061552, -0.14118477, ...,  0.39705111,
         0.73487264,  2.24205783],
       [ 0.25598625,  0.04964684, -0.08193887, ...,  0.4869538 ,
         1.7715104 ,  2.92106578],
       ...,
       [ 1.82742114, -0.61745677, -0.35841972, ..., -0.19123529,
        -0.13812017,  1.27141778],
       [ 1.80032743, -0.64777967, -0.27942519, ..., -0.86951795,
         0.37390363,  0.43154519],
       [ 1.44810927, -1.07230015, -0.35841972, ..., -0.49802014,
         0.40109603,  0.68200519]], shape=(2200, 7))

In [40]:
X_scaled_tensors = torch.tensor(X_scaled, dtype=torch.float)

- Now we have scaled our data .
- Lets apply train_test_split

In [41]:
X_train, X_test, y_train, y_test = train_test_split(X_scaled_tensors, y_tensors, test_size=0.2, random_state=42)

In [42]:
model = CropRecommendationModelReLU()
optimizer = torch.optim.Adam(model.parameters(), lr=0.001)

In [43]:

run = wandb.init(
    # Set the wandb entity where your project will be logged (generally your team name).
    entity="aishwaryapatil845-aish-com",
    # Set the wandb project where this run will be logged.
    project="Crop_Recommendation",
    name="Model-epoch-500-scaled-data-new",
    # Track hyperparameters and run metadata.
    config={
        "learning_rate": 0.001,
        "architecture": "FNN",
        "dataset": "crop_recommndation",
        "epochs": 500,
    },
)

# Training loop 
epoches = 500

for epoch in range(epoches):
    model.train()

    out = model(X_train)
    loss = loss_function(out, y_train)

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    # accuracy
    model.eval()
    y_pred = model(X_test).argmax(dim=1)
    acc = accuracy_score(y_test, y_pred)

    if epoch % 10 == 0 :
        print("Epoch: ", epoch, "Loss value: ", loss.item())
        run.log({"loss": loss.item(), "epoch": epoch, "accuracy": acc})

Epoch:  0 Loss value:  3.092421770095825
Epoch:  10 Loss value:  3.0738091468811035
Epoch:  20 Loss value:  3.0420870780944824
Epoch:  30 Loss value:  2.974956750869751
Epoch:  40 Loss value:  2.8483693599700928
Epoch:  50 Loss value:  2.6604607105255127
Epoch:  60 Loss value:  2.436279535293579
Epoch:  70 Loss value:  2.208395004272461
Epoch:  80 Loss value:  1.9824732542037964
Epoch:  90 Loss value:  1.7815877199172974
Epoch:  100 Loss value:  1.635197639465332
Epoch:  110 Loss value:  1.5291986465454102
Epoch:  120 Loss value:  1.3977710008621216
Epoch:  130 Loss value:  1.28412663936615
Epoch:  140 Loss value:  1.2241555452346802
Epoch:  150 Loss value:  1.112443447113037
Epoch:  160 Loss value:  1.02720308303833
Epoch:  170 Loss value:  0.9277424812316895
Epoch:  180 Loss value:  0.866072416305542
Epoch:  190 Loss value:  0.8120380640029907
Epoch:  200 Loss value:  0.771253228187561
Epoch:  210 Loss value:  0.7209464311599731
Epoch:  220 Loss value:  0.7218647599220276
Epoch:  230 Loss value:  0.6774457097053528
Epoch:  240 Loss value:  0.6419382691383362
Epoch:  250 Loss value:  0.6343849897384644
Epoch:  260 Loss value:  0.6140629649162292
Epoch:  270 Loss value:  0.5727109313011169
Epoch:  280 Loss value:  0.5545496344566345
Epoch:  290 Loss value:  0.5591791868209839
Epoch:  300 Loss value:  0.5442107915878296
Epoch:  310 Loss value:  0.5300744771957397
Epoch:  320 Loss value:  0.49989253282546997
Epoch:  330 Loss value:  0.4865375757217407
Epoch:  340 Loss value:  0.4602050185203552
Epoch:  350 Loss value:  0.45338404178619385
Epoch:  360 Loss value:  0.42935165762901306
Epoch:  370 Loss value:  0.4394163191318512
Epoch:  380 Loss value:  0.41361042857170105
Epoch:  390 Loss value:  0.4173223674297333
Epoch:  400 Loss value:  0.43271708488464355
Epoch:  410 Loss value:  0.4015471339225769
Epoch:  420 Loss value:  0.39593467116355896
Epoch:  430 Loss value:  0.3566282391548157
Epoch:  440 Loss value:  0.39037656784057617
Epoch:  450 Loss value:  0.33897048234939575
Epoch:  460 Loss value:  0.34792324900627136
Epoch:  470 Loss value:  0.309848427772522
Epoch:  480 Loss value:  0.32976430654525757
Epoch:  490 Loss value:  0.3036094307899475

## Increase hidden layer

In [44]:
X_train, X_test, y_train, y_test = train_test_split(X_scaled_tensors, y_tensors, test_size=0.2, random_state=42)

In [45]:
class CropRecommendationModelMoreNeurons(nn.Module):
    def __init__(self):
        super(CropRecommendationModelMoreNeurons, self).__init__()

        # layers
        self.fc1 = nn.Linear(7, 14)
        self.relu1 = nn.ReLU()
        
        # ------ hidden layer
        self.fc2 = nn.Linear(14, 28)
        self.relu2 = nn.ReLU()
        self.do1 = nn.Dropout(0.2)
        
        self.fc3 = nn.Linear(28, 56)
        self.relu3 = nn.ReLU()
        self.do2 = nn.Dropout(0.2)
        
        self.fc4 = nn.Linear(56, 112)
        self.relu4 = nn.ReLU()
        self.do3 = nn.Dropout(0.2)
        # -------
        self.fc5 = nn.Linear(112, 56) 
        self.relu5 = nn.ReLU()
        self.do4 = nn.Dropout(0.1)

        self.fc6 = nn.Linear(56, 34)
        self.relu6 = nn.ReLU()
        self.do5 = nn.Dropout(0.1)

        # ------
        self.fc7 = nn.Linear(34, 22) # output layer
        
    def forward(self, x):
        x = self.fc1(x) # input layer
        x = self.relu1(x)
        

        # hidden layer
        x = self.fc2(x)
        x = self.relu2(x)
        x = self.do1(x)
        
        x = self.fc3(x)
        x = self.relu3(x)
        x = self.do2(x)
        
        x = self.fc4(x)
        x = self.relu4(x)
        x = self.do3(x)

        x = self.fc5(x)
        x = self.relu5(x)
        x = self.do4(x)

        x = self.fc6(x)
        x = self.relu6(x)
        x = self.do5(x)

        x = self.fc7(x) # output layer

        return x

In [46]:
model = CropRecommendationModelMoreNeurons()
optimizer = torch.optim.Adam(model.parameters(), lr=0.001)

In [47]:

run = wandb.init(
    # Set the wandb entity where your project will be logged (generally your team name).
    entity="aishwaryapatil845-aish-com",
    # Set the wandb project where this run will be logged.
    project="Crop_Recommendation",
    name="Model-epoch-500-more-neurons",
    # Track hyperparameters and run metadata.
    config={
        "learning_rate": 0.001,
        "architecture": "FNN",
        "dataset": "crop_recommndation",
        "epochs": 500,
    },
)

# Training loop 
epoches = 500

for epoch in range(epoches):
    model.train()

    out = model(X_train)
    loss = loss_function(out, y_train)

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    # accuracy
    model.eval()
    y_pred = model(X_test).argmax(dim=1)
    acc = accuracy_score(y_test, y_pred)

    if epoch % 10 == 0 :
        print("Epoch: ", epoch, "Loss value: ", loss.item())
        run.log({"loss": loss.item(), "epoch": epoch, "accuracy": acc})

Epoch:  0 Loss value:  3.098057985305786
Epoch:  10 Loss value:  3.086609125137329
Epoch:  20 Loss value:  3.0460453033447266
Epoch:  30 Loss value:  2.9059667587280273
Epoch:  40 Loss value:  2.650160551071167
Epoch:  50 Loss value:  2.390608072280884
Epoch:  60 Loss value:  2.126918077468872
Epoch:  70 Loss value:  1.8408361673355103
Epoch:  80 Loss value:  1.6406961679458618
Epoch:  90 Loss value:  1.398672342300415
Epoch:  100 Loss value:  1.2572458982467651
Epoch:  110 Loss value:  1.1190067529678345
Epoch:  120 Loss value:  1.0295072793960571
Epoch:  130 Loss value:  0.9510139226913452
Epoch:  140 Loss value:  0.9158233404159546
Epoch:  150 Loss value:  0.8625760078430176
Epoch:  160 Loss value:  0.8264829516410828
Epoch:  170 Loss value:  0.7359643578529358
Epoch:  180 Loss value:  0.7268385887145996
Epoch:  190 Loss value:  0.6998481750488281
Epoch:  200 Loss value:  0.6633797287940979
Epoch:  210 Loss value:  0.6256534457206726
Epoch:  220 Loss value:  0.5862194299697876
Epoch:  230 Loss value:  0.5704739093780518
Epoch:  240 Loss value:  0.5261526107788086
Epoch:  250 Loss value:  0.5290842056274414
Epoch:  260 Loss value:  0.506589412689209
Epoch:  270 Loss value:  0.5001280903816223
Epoch:  280 Loss value:  0.4714016318321228
Epoch:  290 Loss value:  0.46178704500198364
Epoch:  300 Loss value:  0.4670126736164093
Epoch:  310 Loss value:  0.4251537621021271
Epoch:  320 Loss value:  0.4264151453971863
Epoch:  330 Loss value:  0.3842901289463043
Epoch:  340 Loss value:  0.3558569550514221
Epoch:  350 Loss value:  0.3646141290664673
Epoch:  360 Loss value:  0.37207862734794617
Epoch:  370 Loss value:  0.34974420070648193
Epoch:  380 Loss value:  0.32813313603401184
Epoch:  390 Loss value:  0.343215674161911
Epoch:  400 Loss value:  0.2889246642589569
Epoch:  410 Loss value:  0.3154790997505188
Epoch:  420 Loss value:  0.29590824246406555
Epoch:  430 Loss value:  0.30784884095191956
Epoch:  440 Loss value:  0.3246590793132782
Epoch:  450 Loss value:  0.2766059935092926
Epoch:  460 Loss value:  0.27940842509269714
Epoch:  470 Loss value:  0.2977026402950287
Epoch:  480 Loss value:  0.26630154252052307
Epoch:  490 Loss value:  0.2518894672393799

# Using different optimizer -SGD

In [49]:
model = CropRecommendationModelMoreNeurons()

optimizer = torch.optim.SGD(model.parameters(), lr=0.001, momentum=0.9)

In [50]:

run = wandb.init(
    # Set the wandb entity where your project will be logged (generally your team name).
    entity="aishwaryapatil845-aish-com",
    # Set the wandb project where this run will be logged.
    project="Crop_Recommendation",
    name="Model-epoch-500-SGD",
    # Track hyperparameters and run metadata.
    config={
        "learning_rate": 0.001,
        "momentum": 0.9,
        "architecture": "FNN",
        "dataset": "crop_recommndation",
        "epochs": 500,
    },
)

# Training loop 
epoches = 500

for epoch in range(epoches):
    model.train()

    out = model(X_train)
    loss = loss_function(out, y_train)

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    # accuracy
    model.eval()
    y_pred = model(X_test).argmax(dim=1)
    acc = accuracy_score(y_test, y_pred)

    if epoch % 10 == 0 :
        print("Epoch: ", epoch, "Loss value: ", loss.item())
        run.log({"loss": loss.item(), "epoch": epoch, "accuracy": acc})

wandb: W&B API key is configured. Use `wandb login --relogin` to force relogin

Epoch:  0 Loss value:  3.09574031829834
Epoch:  10 Loss value:  3.095754623413086
Epoch:  20 Loss value:  3.094839096069336
Epoch:  30 Loss value:  3.0953896045684814
Epoch:  40 Loss value:  3.0955963134765625
Epoch:  50 Loss value:  3.095043182373047
Epoch:  60 Loss value:  3.095336675643921
Epoch:  70 Loss value:  3.094695806503296
Epoch:  80 Loss value:  3.0952813625335693
Epoch:  90 Loss value:  3.0944674015045166
Epoch:  100 Loss value:  3.094524383544922
Epoch:  110 Loss value:  3.094365358352661
Epoch:  120 Loss value:  3.0949013233184814
Epoch:  130 Loss value:  3.0942022800445557
Epoch:  140 Loss value:  3.0949060916900635
Epoch:  150 Loss value:  3.0946500301361084
Epoch:  160 Loss value:  3.0943875312805176
Epoch:  170 Loss value:  3.093703508377075
Epoch:  180 Loss value:  3.094310998916626
Epoch:  190 Loss value:  3.0940537452697754
Epoch:  200 Loss value:  3.0940821170806885
Epoch:  210 Loss value:  3.0938727855682373
Epoch:  220 Loss value:  3.0940427780151367
Epoch:  230 Loss value:  3.0939199924468994
Epoch:  240 Loss value:  3.093867540359497
Epoch:  250 Loss value:  3.093904733657837
Epoch:  260 Loss value:  3.093930959701538
Epoch:  270 Loss value:  3.093968629837036
Epoch:  280 Loss value:  3.0937387943267822
Epoch:  290 Loss value:  3.093311071395874
Epoch:  300 Loss value:  3.093407154083252
Epoch:  310 Loss value:  3.09335994720459
Epoch:  320 Loss value:  3.093153238296509
Epoch:  330 Loss value:  3.093360185623169
Epoch:  340 Loss value:  3.0932888984680176
Epoch:  350 Loss value:  3.0933570861816406
Epoch:  360 Loss value:  3.0930750370025635
Epoch:  370 Loss value:  3.0929272174835205
Epoch:  380 Loss value:  3.093137502670288
Epoch:  390 Loss value:  3.0928447246551514
Epoch:  400 Loss value:  3.0923800468444824
Epoch:  410 Loss value:  3.092726230621338
Epoch:  420 Loss value:  3.0927839279174805
Epoch:  430 Loss value:  3.0925254821777344
Epoch:  440 Loss value:  3.092550277709961
Epoch:  450 Loss value:  3.0929059982299805
Epoch:  460 Loss value:  3.0923585891723633
Epoch:  470 Loss value:  3.092784881591797
Epoch:  480 Loss value:  3.0923218727111816
Epoch:  490 Loss value:  3.0923044681549072

# Saving Model
- The best model with the scaled data
- Lets save scaled model

In [51]:
model = CropRecommendationModelReLU()
optimizer = torch.optim.Adam(model.parameters(), lr=0.001)

In [52]:


# Training loop 
epoches = 501

for epoch in range(epoches):
    model.train()

    out = model(X_train)
    loss = loss_function(out, y_train)

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    # accuracy
    model.eval()
    y_pred = model(X_test).argmax(dim=1)
    acc = accuracy_score(y_test, y_pred)

    if epoch % 10 == 0 :
        print("Epoch: ", epoch, " Loss value: ", loss.item(), " Accuracy: ", acc)

Epoch:  0  Loss value:  3.0956883430480957  Accuracy:  0.05909090909090909
Epoch:  10  Loss value:  3.075613021850586  Accuracy:  0.11136363636363636
Epoch:  20  Loss value:  3.0427277088165283  Accuracy:  0.11818181818181818
Epoch:  30  Loss value:  2.986079454421997  Accuracy:  0.15227272727272728
Epoch:  40  Loss value:  2.874899387359619  Accuracy:  0.18181818181818182
Epoch:  50  Loss value:  2.7138099670410156  Accuracy:  0.20454545454545456
Epoch:  60  Loss value:  2.5181477069854736  Accuracy:  0.24772727272727274
Epoch:  70  Loss value:  2.306511163711548  Accuracy:  0.3068181818181818
Epoch:  80  Loss value:  2.0623977184295654  Accuracy:  0.42727272727272725
Epoch:  90  Loss value:  1.8253499269485474  Accuracy:  0.4954545454545455
Epoch:  100  Loss value:  1.6318392753601074  Accuracy:  0.5522727272727272
Epoch:  110  Loss value:  1.4768187999725342  Accuracy:  0.6136363636363636
Epoch:  120  Loss value:  1.3357040882110596  Accuracy:  0.6772727272727272
Epoch:  130  Loss value:  1.2199827432632446  Accuracy:  0.7363636363636363
Epoch:  140  Loss value:  1.0871087312698364  Accuracy:  0.7681818181818182
Epoch:  150  Loss value:  1.0197899341583252  Accuracy:  0.8045454545454546
Epoch:  160  Loss value:  0.9391739368438721  Accuracy:  0.8113636363636364
Epoch:  170  Loss value:  0.8467421531677246  Accuracy:  0.8318181818181818
Epoch:  180  Loss value:  0.8073984980583191  Accuracy:  0.8454545454545455
Epoch:  190  Loss value:  0.753427267074585  Accuracy:  0.8568181818181818
Epoch:  200  Loss value:  0.714442789554596  Accuracy:  0.8727272727272727
Epoch:  210  Loss value:  0.6813705563545227  Accuracy:  0.8909090909090909
Epoch:  220  Loss value:  0.6381961703300476  Accuracy:  0.8886363636363637
Epoch:  230  Loss value:  0.5992602705955505  Accuracy:  0.8909090909090909
Epoch:  240  Loss value:  0.5682854652404785  Accuracy:  0.8886363636363637
Epoch:  250  Loss value:  0.544377326965332  Accuracy:  0.8954545454545455
Epoch:  260  Loss value:  0.5441359281539917  Accuracy:  0.9068181818181819
Epoch:  270  Loss value:  0.49909988045692444  Accuracy:  0.8977272727272727
Epoch:  280  Loss value:  0.49927887320518494  Accuracy:  0.9022727272727272
Epoch:  290  Loss value:  0.4872485399246216  Accuracy:  0.9136363636363637
Epoch:  300  Loss value:  0.46004968881607056  Accuracy:  0.9090909090909091
Epoch:  310  Loss value:  0.42984047532081604  Accuracy:  0.9204545454545454
Epoch:  320  Loss value:  0.42385879158973694  Accuracy:  0.9204545454545454
Epoch:  330  Loss value:  0.43287286162376404  Accuracy:  0.9227272727272727
Epoch:  340  Loss value:  0.40316158533096313  Accuracy:  0.9227272727272727
Epoch:  350  Loss value:  0.42934468388557434  Accuracy:  0.9295454545454546
Epoch:  360  Loss value:  0.4112365245819092  Accuracy:  0.9318181818181818
Epoch:  370  Loss value:  0.358366459608078  Accuracy:  0.9272727272727272
Epoch:  380  Loss value:  0.376276433467865  Accuracy:  0.9272727272727272
Epoch:  390  Loss value:  0.35150933265686035  Accuracy:  0.9295454545454546
Epoch:  400  Loss value:  0.35827380418777466  Accuracy:  0.9340909090909091
Epoch:  410  Loss value:  0.3176451325416565  Accuracy:  0.9318181818181818
Epoch:  420  Loss value:  0.3121407628059387  Accuracy:  0.9409090909090909
Epoch:  430  Loss value:  0.33010244369506836  Accuracy:  0.9340909090909091
Epoch:  440  Loss value:  0.3188196122646332  Accuracy:  0.9454545454545454
Epoch:  450  Loss value:  0.3202580511569977  Accuracy:  0.9431818181818182
Epoch:  460  Loss value:  0.29181399941444397  Accuracy:  0.9431818181818182
Epoch:  470  Loss value:  0.30491551756858826  Accuracy:  0.9477272727272728
Epoch:  480  Loss value:  0.273995578289032  Accuracy:  0.9477272727272728
Epoch:  490  Loss value:  0.2796081602573395  Accuracy:  0.95
Epoch:  500  Loss value:  0.3012305498123169  Accuracy:  0.9477272727272728

In [53]:
from sklearn.metrics import classification_report

In [55]:
X_test

tensor([[ 1.3668, -1.1026, -0.0227,  ...,  1.0444, -0.3676, -1.4042],
        [ 1.2855, -1.3755,  0.0563,  ...,  0.6757, -0.2716, -0.9834],
        [ 0.2289,  0.2619,  0.0168,  ...,  0.9825,  0.6100,  0.2059],
        ...,
        [ 1.9087, -0.1929, -0.6349,  ...,  0.3511,  1.6203, -0.5636],
        [ 1.7732, -0.0413, -0.5757,  ...,  0.1748, -0.4587, -0.6622],
        [-1.2342,  0.4438, -0.5559,  ..., -1.7240, -0.4495,  0.9447]])

In [54]:
y_pred = model(X_test).argmax(dim=1)
y_pred

tensor([15, 21, 17, 17,  0, 12,  0, 13, 14, 10,  2,  4, 19,  8,  4, 19,  0, 11,
        17, 15,  5, 17, 16, 17,  3,  8, 14, 16, 18, 20, 19, 10,  8, 10,  8,  2,
         8,  3,  3,  3, 17, 12,  2, 11, 14, 11, 18,  4, 15, 11,  2,  5,  7, 14,
         5,  9,  6,  0,  1, 10, 21,  4, 10, 16, 17,  2, 16, 20, 15, 18, 15,  4,
         8,  1,  2, 17,  1,  6, 21, 16,  5,  3,  8, 13, 16, 12,  5, 13,  2, 19,
        11, 13,  6, 17, 18,  9,  9,  5, 10, 10,  4, 20, 16, 15, 21,  9, 21,  1,
        18, 13,  1, 20, 11, 19, 18,  3, 11,  4, 19, 20, 18,  7,  2,  4,  3,  2,
         4, 11,  1, 13,  1,  9, 19,  3,  4, 16, 18,  1,  1,  0,  9, 15, 14, 13,
         4,  6,  0,  4,  9, 13, 14,  2, 21, 14, 18, 18, 18,  9, 11,  8,  3,  0,
        16,  6, 20,  4,  7, 10, 21,  7,  7,  2, 19,  3,  4, 11, 10,  7, 21,  8,
         5,  5,  9,  8, 13,  9,  1,  9,  4, 17, 17, 14, 12, 19, 21, 18, 11,  0,
         2,  3,  7,  7,  1,  6, 20, 19, 14,  1,  8, 14,  6,  3,  3,  3,  0, 20,
         9, 17,  5,  2,  9, 12, 12,  4, 17,  0,  3, 19,  3, 15,  0, 15, 15, 12,
        12,  6,  4, 19, 20, 15,  5, 17, 13, 11, 12, 15, 18, 14,  5,  7,  4,  6,
        18, 20,  0, 19,  5,  3,  6,  8, 12,  1, 17,  0,  3, 20, 18, 13, 14,  8,
        19,  7, 13, 17, 11,  4, 11,  3,  1,  8,  4,  8, 12, 15,  0,  1, 18,  2,
        16,  3, 21,  1,  0,  3,  5, 18, 16,  0,  4, 17, 21, 13, 17,  3, 19,  3,
        17, 10,  0, 19,  3, 12,  3, 19, 21,  9, 14, 15, 21,  9, 15, 12,  8, 10,
         3,  1,  2, 18, 17,  9, 14,  4,  6,  7,  0, 10,  1,  8,  0, 19,  0, 14,
        15,  5,  8, 18,  8,  9,  1, 11,  8, 11, 18, 12,  9, 19, 21,  2, 11, 20,
        13,  9, 12,  6, 17, 13,  6, 14, 16,  8, 10, 14,  5,  1, 18, 17,  0, 19,
        11, 12,  4,  0, 10,  8, 13, 10,  4,  2,  8, 14,  6, 21,  0,  7,  4,  7,
        21,  8, 12, 12,  5, 19,  1,  7,  8, 16,  6, 12, 17, 15, 13,  8,  3, 13,
        19, 21, 13,  6, 17, 21, 13, 20,  4, 13, 13, 11, 20,  6,  4, 16, 19,  9,
        21, 14,  2, 20, 20,  6,  6,  9])

In [56]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        23
           1       1.00      1.00      1.00        21
           2       0.89      0.80      0.84        20
           3       0.96      1.00      0.98        26
           4       1.00      1.00      1.00        27
           5       1.00      0.94      0.97        17
           6       0.84      0.94      0.89        17
           7       1.00      1.00      1.00        14
           8       0.81      0.91      0.86        23
           9       0.86      0.90      0.88        20
          10       0.67      0.91      0.77        11
          11       0.95      0.86      0.90        21
          12       1.00      1.00      1.00        19
          13       1.00      0.92      0.96        24
          14       1.00      1.00      1.00        19
          15       1.00      1.00      1.00        17
          16       1.00      1.00      1.00        14
          17       0.96      1.00      0.98        23
          18       0.95      0.87      0.91        23
          19       1.00      1.00      1.00        23
          20       0.94      0.79      0.86        19
          21       1.00      1.00      1.00        19

    accuracy                           0.95       440
   macro avg       0.95      0.95      0.94       440
weighted avg       0.95      0.95      0.95       440

In [57]:
X.columns

Index(['N', 'P', 'K', 'temperature', 'humidity', 'ph', 'rainfall'], dtype='str')

In [58]:
import numpy as np

In [59]:
user_X = np.array([[100, 112, 130, 45, 100, 7, 100]])
user_X_tensors = torch.tensor(user_X, dtype=torch.float)

scaler.fit_transform(user_X_tensors)

array([[0., 0., 0., 0., 0., 0., 0.]])

In [61]:
model(user_X_tensors).argmax(dim=1)

tensor([0])

In [62]:
label_names[0]

'cotton'

- saving our model using safetensors

In [63]:
!uv add safetensors

Resolved 23 packages in 1.39s
Prepared 1 package in 697ms
Installed 1 package in 4ms
 + safetensors==0.7.0

In [65]:
from safetensors.torch import save_file

In [66]:
model

CropRecommendationModelReLU(
  (fc1): Linear(in_features=7, out_features=14, bias=True)
  (relu1): ReLU()
  (fc2): Linear(in_features=14, out_features=28, bias=True)
  (relu2): ReLU()
  (do1): Dropout(p=0.2, inplace=False)
  (fc3): Linear(in_features=28, out_features=56, bias=True)
  (relu3): ReLU()
  (do2): Dropout(p=0.2, inplace=False)
  (fc4): Linear(in_features=56, out_features=34, bias=True)
  (relu4): ReLU()
  (do3): Dropout(p=0.1, inplace=False)
  (fc5): Linear(in_features=34, out_features=22, bias=True)
)

- print all layers weights and biases using `.state_dict()`

In [68]:
model.state_dict()

OrderedDict([('fc1.weight',
              tensor([[-0.2111,  0.2640,  0.1059,  0.3019, -0.5774,  0.0949, -0.3287],
                      [ 0.5342,  0.2489, -0.3143, -0.1934, -0.2043, -0.1657,  0.3539],
                      [-0.0987,  0.0512,  0.1112, -0.4442, -0.5137,  0.1988, -0.6578],
                      [ 0.3090,  0.3631,  0.1529,  0.0749,  0.7331,  0.0367,  0.1350],
                      [-0.0265,  0.5092,  0.0579, -0.3406,  0.4989, -0.1896,  0.5193],
                      [ 0.0211, -0.1412, -0.8118,  0.0179,  0.1731,  0.0084, -0.5765],
                      [ 0.2999,  0.4515,  0.4202,  0.3438,  0.0781,  0.0360,  0.1128],
                      [-0.4441,  0.3580,  0.0292, -0.0565, -0.4620, -0.2939,  0.1981],
                      [-0.1167,  0.7132,  0.0020,  0.1216,  0.2457, -0.0202, -0.1981],
                      [-0.1079, -0.6614,  0.0777,  0.0875,  0.2595, -0.3969, -0.4950],
                      [-0.5201,  0.3542, -0.5107,  0.0942,  0.7402,  0.0195,  0.0848],
                      [-0.1501,  0.2259,  0.0337,  0.4586,  0.3139,  0.2341, -0.4680],
                      [-0.1404,  0.2331, -0.4775, -0.4176, -0.1677, -0.0721, -0.2596],
                      [ 0.3117,  0.5362, -0.5501, -0.1099,  0.2543, -0.1459, -0.5055]])),
             ('fc1.bias',
              tensor([ 0.4469,  0.2185, -0.3645,  0.0142,  0.1343, -0.1826,  0.3933,  0.1380,
                       0.3635,  0.2131,  0.2194,  0.1017,  0.5438,  0.4990])),
             ('fc2.weight',
              tensor([[-5.2638e-01, -2.5912e-01, -2.4427e-02,  5.2095e-01,  2.1916e-01,
                       -2.5193e-01,  6.3306e-02, -4.3505e-01, -2.5599e-01,  2.0097e-01,
                        5.2594e-01,  2.6560e-01, -5.1939e-02, -1.2425e-01],
                      [ 1.4605e-02,  1.7610e-01, -1.2075e-02, -1.2849e-01, -4.2089e-01,
                        3.3393e-01, -3.5615e-01,  2.8116e-02,  4.0029e-02,  1.5113e-01,
                        4.8044e-02, -5.9054e-02,  1.1189e-01,  5.1547e-01],
                      [ 2.9047e-01,  2.8248e-01, -4.8139e-01, -2.2036e-01,  4.9483e-02,
                       -5.6446e-01,  1.2235e-01,  3.3988e-01,  7.4417e-02, -8.1241e-02,
                        3.1680e-01, -2.6278e-01, -1.4082e-01, -6.0006e-02],
                      [ 1.5530e-02,  2.9451e-01, -6.0439e-01,  1.7975e-01,  2.3831e-01,
                       -5.7272e-01,  3.0017e-01,  3.5708e-01,  5.1838e-01, -4.7168e-01,
                       -2.8250e-01,  3.4080e-01,  1.8321e-01,  9.1118e-02],
                      [ 3.5184e-01, -1.0334e-01,  4.8825e-01,  1.1966e-01,  1.6139e-01,
                        6.2275e-01,  4.2438e-02, -1.3798e-01,  2.2478e-01, -6.2026e-03,
                        4.5057e-01,  4.5967e-01, -6.8648e-02, -1.8950e-01],
                      [-4.3647e-01, -9.3399e-02, -1.0925e-01,  3.7098e-01, -5.0985e-01,
                       -5.9728e-02,  3.9960e-01, -3.9168e-01, -3.2532e-01,  1.4828e-01,
                        2.6035e-01,  4.0471e-02,  7.3898e-02,  1.8239e-01],
                      [-3.8077e-01,  1.5486e-01, -7.7869e-02, -2.4472e-01, -4.3976e-01,
                       -4.9486e-01,  3.0187e-01, -5.1275e-01, -2.2311e-01,  4.9314e-02,
                       -1.4720e-01, -3.8086e-01,  3.1865e-01,  1.3039e-01],
                      [ 3.9776e-01,  3.8604e-01,  8.7130e-02, -6.9523e-02,  5.4964e-02,
                       -4.2367e-01, -8.8184e-02,  2.7329e-01, -1.1731e-01,  3.5730e-01,
                       -3.1602e-01, -1.2773e-01, -2.2756e-02, -4.2398e-01],
                      [ 7.3749e-02, -1.3420e-01, -1.9050e-01,  1.3902e-01,  3.8562e-01,
                        3.3080e-01,  3.7220e-01,  4.0524e-01,  1.1421e-01,  1.6541e-01,
                       -1.9079e-01,  3.4616e-01, -1.9786e-01,  2.3672e-01],
                      [-1.6918e-02,  3.5204e-02, -1.1155e-01, -2.2553e-01,  1.7722e-01,
                       -1.0583e-01, -1.1597e-01, -1.0023e-01, -2.5632e-01, -1.4412e-01,
                       -5.8310e-04, -6.3663e-02, -8.0616e-02, -5.8336e-02],
                      [ 4.1313e-02,  5.2910e-01, -5.2168e-02, -9.0327e-02, -2.9695e-01,
                       -2.5263e-01,  2.9374e-01,  1.3717e-01,  1.2759e-01, -5.6306e-01,
                       -1.0478e-01, -1.4780e-01,  3.0850e-01,  3.5530e-01],
                      [-1.4541e-01,  5.3883e-01, -1.5000e-02, -2.2748e-01, -5.4125e-01,
                        1.8808e-01,  1.3393e-01,  1.2833e-01,  3.6146e-01, -4.2595e-01,
                       -9.0578e-02, -3.6115e-01,  4.0989e-01,  2.7907e-01],
                      [ 4.3449e-01, -3.5919e-01,  3.5508e-01,  1.3151e-01,  3.3069e-01,
                        1.5844e-01, -1.0166e-01, -1.3220e-01,  3.4724e-02,  8.8087e-02,
                        3.5292e-01,  4.4533e-01, -3.2896e-02, -1.0885e-01],
                      [ 2.5890e-01,  1.7476e-01, -3.6652e-01,  3.9932e-01,  4.5257e-01,
                       -4.0091e-01, -2.9780e-02,  3.6113e-02, -6.0173e-02,  3.6063e-01,
                       -3.9690e-01,  6.1023e-02, -5.0005e-01,  1.6552e-01],
                      [ 3.3138e-02,  1.2598e-01, -3.3933e-01,  9.6145e-02,  1.3530e-01,
                       -6.2916e-01,  1.1221e-01,  2.3585e-01, -3.1206e-01,  2.4576e-01,
                        3.2785e-01, -8.4328e-02, -3.9331e-01, -1.5319e-01],
                      [-4.8377e-01,  1.5380e-01, -2.5787e-01,  4.7243e-01,  3.9620e-01,
                       -4.4857e-01,  1.9952e-01, -1.6706e-01, -1.6332e-01,  1.4020e-01,
                        4.2099e-01, -1.5888e-01, -6.3982e-01, -4.6361e-01],
                      [-9.0609e-02,  2.5965e-03, -4.0349e-01,  2.1647e-01,  2.5262e-01,
                        2.9387e-01,  3.6626e-01,  4.5653e-01,  2.4567e-01,  2.4039e-02,
                       -1.1602e-01,  3.0459e-01, -9.1647e-02,  1.3868e-01],
                      [ 3.2695e-01,  2.6880e-01,  4.2855e-01, -2.6497e-01, -5.8840e-02,
                       -1.7458e-01, -4.4175e-01,  9.3515e-02, -2.6483e-01,  3.3690e-01,
                        3.2756e-02, -9.4261e-02,  2.5972e-01, -4.5306e-01],
                      [ 1.1470e-01, -1.3998e-01, -1.6252e-01, -4.6218e-01,  6.1105e-02,
                        5.2487e-01,  1.2697e-01,  3.6685e-01, -3.9497e-02,  4.0179e-01,
                       -4.2251e-01,  4.6248e-01,  3.3190e-01,  2.3929e-01],
                      [ 1.1051e-01,  2.2296e-03,  3.4519e-02, -2.1145e-03, -4.4269e-01,
                        1.0145e-01,  1.3867e-01,  7.0777e-02,  3.9402e-01, -6.1902e-01,
                       -2.5856e-01, -1.8153e-01,  4.3533e-01,  4.8901e-01],
                      [ 1.1059e-03, -1.5544e-01, -3.3912e-01,  4.1864e-01,  2.1064e-01,
                       -2.8904e-01,  3.0251e-01,  2.7851e-01,  3.9926e-01, -5.8448e-01,
                        2.1556e-01,  1.3478e-02,  1.3801e-01,  4.2125e-01],
                      [ 4.7881e-01,  1.6454e-01,  2.9319e-01, -3.0806e-01, -3.2941e-02,
                       -2.0230e-01,  3.2199e-01,  8.6327e-02, -7.1976e-02,  2.3025e-01,
                       -3.7664e-01, -1.3741e-01,  3.3132e-01, -3.0123e-01],
                      [ 1.3107e-01, -1.0625e-01, -9.4811e-02, -7.9741e-02,  1.8769e-02,
                       -5.4225e-01, -4.5226e-01,  1.9815e-01, -3.4749e-01,  3.3268e-01,
                        2.6536e-01,  1.1892e-01, -4.0516e-01, -3.8996e-01],
                      [-6.6845e-02, -3.7060e-01, -2.9475e-01,  2.3612e-01,  3.3613e-01,
                       -2.6884e-01,  6.0450e-01, -5.3833e-01,  8.0526e-02, -2.6906e-01,
                       -1.3388e-01,  2.4040e-01, -2.1117e-01,  5.3009e-01],
                      [-4.7481e-01, -2.1552e-02, -3.3016e-01,  5.6002e-02, -4.4369e-01,
                        2.4937e-01,  2.6191e-01, -4.8293e-01,  1.5657e-01, -9.6757e-03,
                        5.4029e-01, -1.5204e-01,  2.2368e-01,  3.7081e-01],
                      [-7.8534e-02, -1.5928e-01,  4.2725e-02,  1.8247e-01, -3.0503e-01,
                        6.2261e-01, -3.0440e-01, -1.5019e-01,  1.2424e-01,  1.6529e-01,
                        1.7475e-01,  4.4122e-01,  2.9366e-01,  3.4452e-01],
                      [ 2.1571e-01, -5.2812e-02, -1.7946e-01,  3.1184e-02,  4.3837e-01,
                       -2.3739e-01,  3.5996e-01,  1.2999e-01,  5.0923e-01, -2.3638e-01,
                       -1.4400e-01, -1.7004e-02, -1.1586e-01, -2.6235e-01],
                      [-5.2671e-01,  4.4691e-01,  1.6190e-01,  3.0111e-01,  7.7024e-02,
                        1.2338e-01,  2.3536e-01, -3.4166e-01, -5.1627e-01,  3.9316e-01,
                       -5.3345e-01,  2.2208e-01, -1.2302e-01,  1.7030e-01]])),
             ('fc2.bias',
              tensor([ 0.2084, -0.3155,  0.1008, -0.0746, -0.4965,  0.4164,  0.5617,  0.4335,
                      -0.3739, -0.2354, -0.0505, -0.0923, -0.2931,  0.2643,  0.3657, -0.2179,
                      -0.3888,  0.2260, -0.2944, -0.2426, -0.0798,  0.1877,  0.1745, -0.0450,
                       0.3444, -0.3756,  0.2647,  0.0670])),
             ('fc3.weight',
              tensor([[ 0.1724, -0.4738,  0.0457,  ..., -0.0635,  0.0796,  0.0990],
                      [ 0.1743,  0.4002, -0.3903,  ...,  0.2323, -0.1092,  0.3524],
                      [ 0.3598, -0.0292, -0.1633,  ..., -0.0154,  0.2624,  0.4353],
                      ...,
                      [ 0.0007, -0.0048, -0.0238,  ..., -0.0815, -0.1573,  0.1987],
                      [-0.0311, -0.4576,  0.3807,  ...,  0.0095,  0.4097, -0.1944],
                      [-0.5759,  0.0528,  0.3764,  ...,  0.0400,  0.0044, -0.5279]])),
             ('fc3.bias',
              tensor([ 0.2646,  0.2683, -0.1153, -0.3050, -0.0319, -0.2264, -0.2215, -0.1361,
                       0.0138,  0.0265, -0.0724, -0.0444, -0.2296, -0.0309, -0.1953,  0.2382,
                       0.0268,  0.1677, -0.0388,  0.2531,  0.2265,  0.2134, -0.0861,  0.2334,
                       0.1804,  0.1606,  0.4061, -0.2557, -0.3161, -0.1748, -0.0572,  0.3865,
                       0.1682, -0.2411, -0.2953,  0.3305,  0.4141, -0.2936,  0.0051, -0.3050,
                       0.3476,  0.1581,  0.2119,  0.1575,  0.3264,  0.3188,  0.3097,  0.3855,
                      -0.2994,  0.3004, -0.0807,  0.3060, -0.0387,  0.3033,  0.4182, -0.0280])),
             ('fc4.weight',
              tensor([[-0.3404, -0.1060,  0.0459,  ..., -0.2821,  0.1832,  0.1510],
                      [ 0.1529, -0.3584, -0.0340,  ..., -0.1151, -0.1685,  0.2877],
                      [-0.2023,  0.1478,  0.3323,  ...,  0.3322,  0.1540, -0.2612],
                      ...,
                      [ 0.3923,  0.2261,  0.1738,  ...,  0.0817,  0.0238, -0.1670],
                      [-0.3444,  0.0543,  0.1976,  ...,  0.2634,  0.0972,  0.0862],
                      [-0.1797, -0.0801,  0.0760,  ..., -0.0429,  0.1264,  0.3009]])),
             ('fc4.bias',
              tensor([-0.3085, -0.1401, -0.0660, -0.1861,  0.0349,  0.2225, -0.1238, -0.0595,
                       0.1341,  0.2129,  0.0119, -0.2152,  0.1712,  0.2169,  0.1832,  0.1624,
                       0.2143,  0.2712,  0.1973, -0.0258,  0.2091, -0.0683, -0.2799,  0.1959,
                      -0.0053, -0.1871, -0.0034,  0.1631, -0.1204,  0.1733, -0.3950,  0.1344,
                      -0.1821, -0.1410])),
             ('fc5.weight',
              tensor([[ 0.1427,  0.0219,  0.1774, -0.3542, -0.2165, -0.3413, -0.4347,  0.1378,
                        0.1959, -0.2177, -0.0628,  0.2581, -0.3144, -0.2523, -0.1861,  0.1275,
                       -0.2203, -0.1064,  0.1200,  0.1696, -0.3240,  0.1358,  0.1111, -0.3144,
                       -0.0406,  0.0644, -0.4070, -0.1486,  0.1790, -0.2074, -0.0726,  0.2770,
                        0.0966,  0.2500],
                      [ 0.0762, -0.1951,  0.2186,  0.1162, -0.2468, -0.0850, -0.3356, -0.0504,
                        0.1739, -0.1679,  0.1918,  0.1944,  0.2265, -0.2881, -0.4217,  0.0038,
                       -0.0551, -0.1363, -0.4081,  0.1659,  0.0485,  0.1108,  0.2674,  0.2009,
                        0.2253, -0.0246, -0.0197, -0.3351,  0.1967, -0.0102, -0.2395, -0.2118,
                        0.0618,  0.1721],
                      [ 0.2052, -0.0537, -0.0582,  0.1880, -0.1323, -0.1423,  0.1709,  0.0538,
                        0.1146, -0.3969,  0.0964,  0.1932,  0.0710,  0.1344,  0.0629,  0.0974,
                       -0.4195,  0.2642, -0.2816, -0.2684, -0.3987,  0.0729, -0.4514, -0.2830,
                        0.1715,  0.1360,  0.1628,  0.2252,  0.2900, -0.0470, -0.1133, -0.3141,
                        0.0392,  0.0188],
                      [-0.3681,  0.2393, -0.1890,  0.1740,  0.1575, -0.3650,  0.0802,  0.1748,
                       -0.0418,  0.1654, -0.1826, -0.1712, -0.2437,  0.3086, -0.3974,  0.1208,
                        0.1073, -0.2026,  0.1192, -0.5033, -0.2873, -0.1915, -0.0154, -0.0714,
                       -0.2177,  0.3067,  0.0320,  0.2830, -0.3090, -0.5426,  0.2300, -0.1320,
                        0.1545, -0.1133],
                      [-0.1480, -0.3824, -0.4398, -0.2530,  0.0840,  0.2493, -0.3703, -0.0517,
                       -0.0837,  0.2971, -0.2597, -0.1505, -0.1187, -0.3296, -0.2603,  0.1749,
                        0.2035,  0.2426,  0.3209,  0.2829,  0.2411, -0.0418, -0.2795, -0.3254,
                       -0.3169, -0.4500, -0.4173, -0.1802, -0.3083,  0.1916, -0.2444,  0.3845,
                       -0.2821, -0.1681],
                      [-0.3864, -0.1052, -0.0936,  0.2356, -0.4201,  0.2453, -0.3301, -0.4377,
                       -0.2777,  0.2769, -0.2625, -0.1871,  0.3122, -0.4421, -0.4688, -0.1058,
                        0.4030, -0.2008,  0.0205,  0.1646,  0.3049,  0.0777, -0.1302,  0.3252,
                        0.0900,  0.1379,  0.0286, -0.2970, -0.1873, -0.0492, -0.4658, -0.1856,
                        0.0496, -0.4169],
                      [-0.2360, -0.1328,  0.2014,  0.2112, -0.3088,  0.0172,  0.0200, -0.4878,
                        0.1138, -0.1913,  0.2076,  0.1466,  0.2824, -0.1438,  0.1224, -0.4413,
                       -0.3631,  0.0363, -0.2604, -0.2334,  0.2672, -0.1463,  0.1665,  0.2035,
                        0.3056,  0.0401,  0.1333, -0.3568,  0.1412,  0.1770, -0.3533, -0.2975,
                        0.0523, -0.3009],
                      [ 0.1535,  0.1850,  0.1452, -0.0034, -0.0936, -0.2385,  0.0222,  0.1225,
                        0.1550, -0.3610,  0.0457,  0.2679, -0.2847, -0.2420, -0.2448,  0.0732,
                       -0.1882, -0.2588,  0.0651,  0.1095, -0.0757,  0.1263,  0.0341, -0.1521,
                       -0.3316,  0.2494,  0.0573, -0.1481,  0.1831, -0.2749, -0.2677, -0.3478,
                        0.1238,  0.2475],
                      [-0.3619, -0.2787,  0.2467,  0.0220, -0.3594,  0.1745, -0.0764, -0.2063,
                        0.2311,  0.1251, -0.1518, -0.2353,  0.2887, -0.2322, -0.3765,  0.0049,
                        0.2971, -0.0494,  0.0128,  0.2649,  0.2665,  0.1671,  0.1327,  0.2384,
                       -0.1535, -0.3668, -0.3227, -0.3710,  0.1224,  0.0587, -0.3612,  0.2228,
                       -0.0826, -0.0221],
                      [-0.0328,  0.2039, -0.2946,  0.2160, -0.1158, -0.4241,  0.0913, -0.1334,
                       -0.1974,  0.1568, -0.3043, -0.2494,  0.1373,  0.2121, -0.2750, -0.1821,
                        0.1570, -0.3593,  0.0899, -0.1238, -0.2455,  0.0688, -0.2628, -0.1530,
                       -0.1963,  0.3177,  0.0941,  0.0664,  0.1364, -0.1375,  0.2312, -0.2078,
                        0.1601,  0.0872],
                      [ 0.1217, -0.0072, -0.3475,  0.1981,  0.0885, -0.3698,  0.1886, -0.1204,
                       -0.2072, -0.4041, -0.0074,  0.2284,  0.0223,  0.2504,  0.1795, -0.0488,
                       -0.2844,  0.2844, -0.4721, -0.0721, -0.1340, -0.2039, -0.1768, -0.2997,
                        0.2016,  0.2020,  0.1784,  0.3196,  0.2209, -0.0161,  0.2297, -0.2058,
                        0.0380, -0.1357],
                      [-0.4197, -0.3134, -0.0559,  0.2449, -0.0846,  0.0231,  0.0669, -0.4356,
                       -0.3867,  0.0923,  0.1239, -0.2662,  0.2940, -0.1156,  0.1030, -0.5285,
                        0.2700,  0.1558, -0.2457, -0.3305,  0.2531, -0.3085, -0.1883,  0.2301,
                        0.2812,  0.3074,  0.1720, -0.1114, -0.0231,  0.1217,  0.0386, -0.4305,
                        0.0736, -0.2589],
                      [-0.4340,  0.2838, -0.1653, -0.3519,  0.2300,  0.1822, -0.0200,  0.0124,
                       -0.1774,  0.3220, -0.2450, -0.1075, -0.2721,  0.2235, -0.1783,  0.2152,
                        0.2595, -0.2684,  0.3637, -0.1156, -0.2289,  0.0967, -0.0989, -0.1805,
                       -0.3222,  0.2052, -0.1720,  0.1307, -0.3479,  0.0466, -0.5390, -0.1374,
                       -0.0899, -0.3201],
                      [ 0.0381,  0.1829, -0.1142, -0.0163,  0.2999, -0.1182,  0.1926,  0.0355,
                       -0.4065,  0.1395, -0.2312,  0.1630, -0.1742,  0.2627,  0.3027, -0.1145,
                       -0.1720,  0.0172,  0.0881, -0.3239, -0.2509, -0.1508,  0.1013,  0.1264,
                       -0.2350,  0.2432,  0.0752,  0.2745, -0.0830,  0.0294,  0.1456, -0.4316,
                        0.0522, -0.2110],
                      [-0.0761, -0.3682, -0.1810, -0.4187,  0.1196, -0.0177,  0.1719,  0.0850,
                        0.1839, -0.4180,  0.2676,  0.2600, -0.1682,  0.1196,  0.2919, -0.0761,
                       -0.3256,  0.2961, -0.4549, -0.1558,  0.0989, -0.1735, -0.2908, -0.1731,
                        0.1866, -0.2470, -0.0229,  0.3167, -0.2098,  0.1695,  0.3234, -0.1265,
                       -0.1610, -0.3800],
                      [ 0.0636,  0.0229, -0.0447, -0.5276,  0.1880,  0.0077,  0.1849,  0.1018,
                        0.2260, -0.3567,  0.2862,  0.2209, -0.2299, -0.3618,  0.2875, -0.3891,
                       -0.2835, -0.2308, -0.0719, -0.1816,  0.2012, -0.2142,  0.3520,  0.2320,
                        0.1766, -0.1977, -0.1358, -0.1679, -0.0750,  0.1975, -0.1300,  0.1913,
                       -0.3815, -0.0616],
                      [-0.6528, -0.2601, -0.2966, -0.1762,  0.2551,  0.1503,  0.0339, -0.1213,
                        0.1308,  0.1983,  0.0434, -0.2711,  0.1174,  0.3809,  0.2397,  0.0588,
                       -0.0901,  0.3562,  0.0344, -0.5449,  0.1520, -0.4488, -0.4376, -0.0591,
                        0.0507, -0.1487, -0.0424,  0.3367, -0.2314,  0.2542, -0.4307,  0.2313,
                       -0.4030, -0.3717],
                      [ 0.0496, -0.5152,  0.0615, -0.4054, -0.0514,  0.1342, -0.0771,  0.2071,
                        0.2260, -0.2416,  0.2559,  0.1691, -0.2469, -0.3256,  0.0854,  0.1834,
                       -0.0746,  0.2872,  0.0318,  0.1885,  0.0514,  0.1089,  0.0008, -0.2375,
                        0.1581, -0.3770, -0.1234, -0.0882,  0.0755,  0.1325, -0.2985,  0.3246,
                       -0.0261,  0.1539],
                      [ 0.0805,  0.1557, -0.1640,  0.1349, -0.3301, -0.2158,  0.0300,  0.1059,
                       -0.1238,  0.1532, -0.0690, -0.0567, -0.0485,  0.0021, -0.1514,  0.1183,
                        0.1804, -0.1236,  0.2353,  0.1628, -0.2807,  0.1433, -0.2198, -0.1532,
                       -0.0890,  0.2745,  0.0714, -0.1785,  0.2267, -0.3036, -0.2223, -0.2035,
                        0.1308,  0.1668],
                      [-0.2322, -0.2171, -0.2395, -0.3768,  0.1853,  0.2721, -0.5577, -0.6452,
                       -0.4779,  0.3626, -0.4741, -0.2792,  0.1765,  0.0922,  0.1699, -0.0498,
                        0.2825,  0.2406,  0.2476, -0.1791,  0.3044, -0.5054, -0.4129,  0.1316,
                       -0.0047, -0.3081, -0.3663,  0.2442, -0.2341,  0.2496, -0.3317,  0.2972,
                       -0.3811, -0.0449],
                      [-0.3031, -0.0434,  0.2130, -0.3012, -0.3124,  0.0633, -0.1514, -0.0627,
                        0.2461,  0.1544, -0.3497, -0.2449, -0.2602, -0.1591, -0.0663,  0.0034,
                        0.2406, -0.3234,  0.1176,  0.2696,  0.1691,  0.1875,  0.3283,  0.2582,

In [69]:
tensors = model.state_dict()

In [70]:
save_file(tensors, "Models/crop_recommendation.safetensors")

### Load save safetensors models

- First load model architecture

In [75]:
class CropRecommendationModelLoad(nn.Module):
    def __init__(self):
        super(CropRecommendationModelLoad, self).__init__()

        # layers
        self.fc1 = nn.Linear(7, 14)
        self.relu1 = nn.ReLU()
        
        # ------ hidden layer
        self.fc2 = nn.Linear(14, 28)
        self.relu2 = nn.ReLU()
        self.do1 = nn.Dropout(0.2)
        
        self.fc3 = nn.Linear(28, 56)
        self.relu3 = nn.ReLU()
        self.do2 = nn.Dropout(0.2)
        
        self.fc4 = nn.Linear(56, 34)
        self.relu4 = nn.ReLU()
        self.do3 = nn.Dropout(0.1)
        # -------
        self.fc5 = nn.Linear(34, 22) # output layer

    def forward(self, x):
        x = self.fc1(x) # input layer
        x = self.relu1(x)
        

        # hidden layer
        x = self.fc2(x)
        x = self.relu2(x)
        x = self.do1(x)
        
        x = self.fc3(x)
        x = self.relu3(x)
        x = self.do2(x)
        
        x = self.fc4(x)
        x = self.relu4(x)
        x = self.do3(x)

        x = self.fc5(x) # output layer

        return x

In [76]:
loaded_model = CropRecommendationModelLoad()
loaded_model

CropRecommendationModelLoad(
  (fc1): Linear(in_features=7, out_features=14, bias=True)
  (relu1): ReLU()
  (fc2): Linear(in_features=14, out_features=28, bias=True)
  (relu2): ReLU()
  (do1): Dropout(p=0.2, inplace=False)
  (fc3): Linear(in_features=28, out_features=56, bias=True)
  (relu3): ReLU()
  (do2): Dropout(p=0.2, inplace=False)
  (fc4): Linear(in_features=56, out_features=34, bias=True)
  (relu4): ReLU()
  (do3): Dropout(p=0.1, inplace=False)
  (fc5): Linear(in_features=34, out_features=22, bias=True)
)

In [77]:
from safetensors.torch import load_file

In [78]:
tensors = load_file("Models/crop_recommendation.safetensors")
tensors

{'fc1.bias': tensor([ 0.4469,  0.2185, -0.3645,  0.0142,  0.1343, -0.1826,  0.3933,  0.1380,
          0.3635,  0.2131,  0.2194,  0.1017,  0.5438,  0.4990]),
 'fc1.weight': tensor([[-0.2111,  0.2640,  0.1059,  0.3019, -0.5774,  0.0949, -0.3287],
         [ 0.5342,  0.2489, -0.3143, -0.1934, -0.2043, -0.1657,  0.3539],
         [-0.0987,  0.0512,  0.1112, -0.4442, -0.5137,  0.1988, -0.6578],
         [ 0.3090,  0.3631,  0.1529,  0.0749,  0.7331,  0.0367,  0.1350],
         [-0.0265,  0.5092,  0.0579, -0.3406,  0.4989, -0.1896,  0.5193],
         [ 0.0211, -0.1412, -0.8118,  0.0179,  0.1731,  0.0084, -0.5765],
         [ 0.2999,  0.4515,  0.4202,  0.3438,  0.0781,  0.0360,  0.1128],
         [-0.4441,  0.3580,  0.0292, -0.0565, -0.4620, -0.2939,  0.1981],
         [-0.1167,  0.7132,  0.0020,  0.1216,  0.2457, -0.0202, -0.1981],
         [-0.1079, -0.6614,  0.0777,  0.0875,  0.2595, -0.3969, -0.4950],
         [-0.5201,  0.3542, -0.5107,  0.0942,  0.7402,  0.0195,  0.0848],
         [-0.1501,  0.2259,  0.0337,  0.4586,  0.3139,  0.2341, -0.4680],
         [-0.1404,  0.2331, -0.4775, -0.4176, -0.1677, -0.0721, -0.2596],
         [ 0.3117,  0.5362, -0.5501, -0.1099,  0.2543, -0.1459, -0.5055]]),
 'fc2.bias': tensor([ 0.2084, -0.3155,  0.1008, -0.0746, -0.4965,  0.4164,  0.5617,  0.4335,
         -0.3739, -0.2354, -0.0505, -0.0923, -0.2931,  0.2643,  0.3657, -0.2179,
         -0.3888,  0.2260, -0.2944, -0.2426, -0.0798,  0.1877,  0.1745, -0.0450,
          0.3444, -0.3756,  0.2647,  0.0670]),
 'fc2.weight': tensor([[-5.2638e-01, -2.5912e-01, -2.4427e-02,  5.2095e-01,  2.1916e-01,
          -2.5193e-01,  6.3306e-02, -4.3505e-01, -2.5599e-01,  2.0097e-01,
           5.2594e-01,  2.6560e-01, -5.1939e-02, -1.2425e-01],
         [ 1.4605e-02,  1.7610e-01, -1.2075e-02, -1.2849e-01, -4.2089e-01,
           3.3393e-01, -3.5615e-01,  2.8116e-02,  4.0029e-02,  1.5113e-01,
           4.8044e-02, -5.9054e-02,  1.1189e-01,  5.1547e-01],
         [ 2.9047e-01,  2.8248e-01, -4.8139e-01, -2.2036e-01,  4.9483e-02,
          -5.6446e-01,  1.2235e-01,  3.3988e-01,  7.4417e-02, -8.1241e-02,
           3.1680e-01, -2.6278e-01, -1.4082e-01, -6.0006e-02],
         [ 1.5530e-02,  2.9451e-01, -6.0439e-01,  1.7975e-01,  2.3831e-01,
          -5.7272e-01,  3.0017e-01,  3.5708e-01,  5.1838e-01, -4.7168e-01,
          -2.8250e-01,  3.4080e-01,  1.8321e-01,  9.1118e-02],
         [ 3.5184e-01, -1.0334e-01,  4.8825e-01,  1.1966e-01,  1.6139e-01,
           6.2275e-01,  4.2438e-02, -1.3798e-01,  2.2478e-01, -6.2026e-03,
           4.5057e-01,  4.5967e-01, -6.8648e-02, -1.8950e-01],
         [-4.3647e-01, -9.3399e-02, -1.0925e-01,  3.7098e-01, -5.0985e-01,
          -5.9728e-02,  3.9960e-01, -3.9168e-01, -3.2532e-01,  1.4828e-01,
           2.6035e-01,  4.0471e-02,  7.3898e-02,  1.8239e-01],
         [-3.8077e-01,  1.5486e-01, -7.7869e-02, -2.4472e-01, -4.3976e-01,
          -4.9486e-01,  3.0187e-01, -5.1275e-01, -2.2311e-01,  4.9314e-02,
          -1.4720e-01, -3.8086e-01,  3.1865e-01,  1.3039e-01],
         [ 3.9776e-01,  3.8604e-01,  8.7130e-02, -6.9523e-02,  5.4964e-02,
          -4.2367e-01, -8.8184e-02,  2.7329e-01, -1.1731e-01,  3.5730e-01,
          -3.1602e-01, -1.2773e-01, -2.2756e-02, -4.2398e-01],
         [ 7.3749e-02, -1.3420e-01, -1.9050e-01,  1.3902e-01,  3.8562e-01,
           3.3080e-01,  3.7220e-01,  4.0524e-01,  1.1421e-01,  1.6541e-01,
          -1.9079e-01,  3.4616e-01, -1.9786e-01,  2.3672e-01],
         [-1.6918e-02,  3.5204e-02, -1.1155e-01, -2.2553e-01,  1.7722e-01,
          -1.0583e-01, -1.1597e-01, -1.0023e-01, -2.5632e-01, -1.4412e-01,
          -5.8310e-04, -6.3663e-02, -8.0616e-02, -5.8336e-02],
         [ 4.1313e-02,  5.2910e-01, -5.2168e-02, -9.0327e-02, -2.9695e-01,
          -2.5263e-01,  2.9374e-01,  1.3717e-01,  1.2759e-01, -5.6306e-01,
          -1.0478e-01, -1.4780e-01,  3.0850e-01,  3.5530e-01],
         [-1.4541e-01,  5.3883e-01, -1.5000e-02, -2.2748e-01, -5.4125e-01,
           1.8808e-01,  1.3393e-01,  1.2833e-01,  3.6146e-01, -4.2595e-01,
          -9.0578e-02, -3.6115e-01,  4.0989e-01,  2.7907e-01],
         [ 4.3449e-01, -3.5919e-01,  3.5508e-01,  1.3151e-01,  3.3069e-01,
           1.5844e-01, -1.0166e-01, -1.3220e-01,  3.4724e-02,  8.8087e-02,
           3.5292e-01,  4.4533e-01, -3.2896e-02, -1.0885e-01],
         [ 2.5890e-01,  1.7476e-01, -3.6652e-01,  3.9932e-01,  4.5257e-01,
          -4.0091e-01, -2.9780e-02,  3.6113e-02, -6.0173e-02,  3.6063e-01,
          -3.9690e-01,  6.1023e-02, -5.0005e-01,  1.6552e-01],
         [ 3.3138e-02,  1.2598e-01, -3.3933e-01,  9.6145e-02,  1.3530e-01,
          -6.2916e-01,  1.1221e-01,  2.3585e-01, -3.1206e-01,  2.4576e-01,
           3.2785e-01, -8.4328e-02, -3.9331e-01, -1.5319e-01],
         [-4.8377e-01,  1.5380e-01, -2.5787e-01,  4.7243e-01,  3.9620e-01,
          -4.4857e-01,  1.9952e-01, -1.6706e-01, -1.6332e-01,  1.4020e-01,
           4.2099e-01, -1.5888e-01, -6.3982e-01, -4.6361e-01],
         [-9.0609e-02,  2.5965e-03, -4.0349e-01,  2.1647e-01,  2.5262e-01,
           2.9387e-01,  3.6626e-01,  4.5653e-01,  2.4567e-01,  2.4039e-02,
          -1.1602e-01,  3.0459e-01, -9.1647e-02,  1.3868e-01],
         [ 3.2695e-01,  2.6880e-01,  4.2855e-01, -2.6497e-01, -5.8840e-02,
          -1.7458e-01, -4.4175e-01,  9.3515e-02, -2.6483e-01,  3.3690e-01,
           3.2756e-02, -9.4261e-02,  2.5972e-01, -4.5306e-01],
         [ 1.1470e-01, -1.3998e-01, -1.6252e-01, -4.6218e-01,  6.1105e-02,
           5.2487e-01,  1.2697e-01,  3.6685e-01, -3.9497e-02,  4.0179e-01,
          -4.2251e-01,  4.6248e-01,  3.3190e-01,  2.3929e-01],
         [ 1.1051e-01,  2.2296e-03,  3.4519e-02, -2.1145e-03, -4.4269e-01,
           1.0145e-01,  1.3867e-01,  7.0777e-02,  3.9402e-01, -6.1902e-01,
          -2.5856e-01, -1.8153e-01,  4.3533e-01,  4.8901e-01],
         [ 1.1059e-03, -1.5544e-01, -3.3912e-01,  4.1864e-01,  2.1064e-01,
          -2.8904e-01,  3.0251e-01,  2.7851e-01,  3.9926e-01, -5.8448e-01,
           2.1556e-01,  1.3478e-02,  1.3801e-01,  4.2125e-01],
         [ 4.7881e-01,  1.6454e-01,  2.9319e-01, -3.0806e-01, -3.2941e-02,
          -2.0230e-01,  3.2199e-01,  8.6327e-02, -7.1976e-02,  2.3025e-01,
          -3.7664e-01, -1.3741e-01,  3.3132e-01, -3.0123e-01],
         [ 1.3107e-01, -1.0625e-01, -9.4811e-02, -7.9741e-02,  1.8769e-02,
          -5.4225e-01, -4.5226e-01,  1.9815e-01, -3.4749e-01,  3.3268e-01,
           2.6536e-01,  1.1892e-01, -4.0516e-01, -3.8996e-01],
         [-6.6845e-02, -3.7060e-01, -2.9475e-01,  2.3612e-01,  3.3613e-01,
          -2.6884e-01,  6.0450e-01, -5.3833e-01,  8.0526e-02, -2.6906e-01,
          -1.3388e-01,  2.4040e-01, -2.1117e-01,  5.3009e-01],
         [-4.7481e-01, -2.1552e-02, -3.3016e-01,  5.6002e-02, -4.4369e-01,
           2.4937e-01,  2.6191e-01, -4.8293e-01,  1.5657e-01, -9.6757e-03,
           5.4029e-01, -1.5204e-01,  2.2368e-01,  3.7081e-01],
         [-7.8534e-02, -1.5928e-01,  4.2725e-02,  1.8247e-01, -3.0503e-01,
           6.2261e-01, -3.0440e-01, -1.5019e-01,  1.2424e-01,  1.6529e-01,
           1.7475e-01,  4.4122e-01,  2.9366e-01,  3.4452e-01],
         [ 2.1571e-01, -5.2812e-02, -1.7946e-01,  3.1184e-02,  4.3837e-01,
          -2.3739e-01,  3.5996e-01,  1.2999e-01,  5.0923e-01, -2.3638e-01,
          -1.4400e-01, -1.7004e-02, -1.1586e-01, -2.6235e-01],
         [-5.2671e-01,  4.4691e-01,  1.6190e-01,  3.0111e-01,  7.7024e-02,
           1.2338e-01,  2.3536e-01, -3.4166e-01, -5.1627e-01,  3.9316e-01,
          -5.3345e-01,  2.2208e-01, -1.2302e-01,  1.7030e-01]]),
 'fc3.bias': tensor([ 0.2646,  0.2683, -0.1153, -0.3050, -0.0319, -0.2264, -0.2215, -0.1361,
          0.0138,  0.0265, -0.0724, -0.0444, -0.2296, -0.0309, -0.1953,  0.2382,
          0.0268,  0.1677, -0.0388,  0.2531,  0.2265,  0.2134, -0.0861,  0.2334,
          0.1804,  0.1606,  0.4061, -0.2557, -0.3161, -0.1748, -0.0572,  0.3865,
          0.1682, -0.2411, -0.2953,  0.3305,  0.4141, -0.2936,  0.0051, -0.3050,
          0.3476,  0.1581,  0.2119,  0.1575,  0.3264,  0.3188,  0.3097,  0.3855,
         -0.2994,  0.3004, -0.0807,  0.3060, -0.0387,  0.3033,  0.4182, -0.0280]),
 'fc3.weight': tensor([[ 0.1724, -0.4738,  0.0457,  ..., -0.0635,  0.0796,  0.0990],
         [ 0.1743,  0.4002, -0.3903,  ...,  0.2323, -0.1092,  0.3524],
         [ 0.3598, -0.0292, -0.1633,  ..., -0.0154,  0.2624,  0.4353],
         ...,
         [ 0.0007, -0.0048, -0.0238,  ..., -0.0815, -0.1573,  0.1987],
         [-0.0311, -0.4576,  0.3807,  ...,  0.0095,  0.4097, -0.1944],
         [-0.5759,  0.0528,  0.3764,  ...,  0.0400,  0.0044, -0.5279]]),
 'fc4.bias': tensor([-0.3085, -0.1401, -0.0660, -0.1861,  0.0349,  0.2225, -0.1238, -0.0595,
          0.1341,  0.2129,  0.0119, -0.2152,  0.1712,  0.2169,  0.1832,  0.1624,
          0.2143,  0.2712,  0.1973, -0.0258,  0.2091, -0.0683, -0.2799,  0.1959,
         -0.0053, -0.1871, -0.0034,  0.1631, -0.1204,  0.1733, -0.3950,  0.1344,
         -0.1821, -0.1410]),
 'fc4.weight': tensor([[-0.3404, -0.1060,  0.0459,  ..., -0.2821,  0.1832,  0.1510],
         [ 0.1529, -0.3584, -0.0340,  ..., -0.1151, -0.1685,  0.2877],
         [-0.2023,  0.1478,  0.3323,  ...,  0.3322,  0.1540, -0.2612],
         ...,
         [ 0.3923,  0.2261,  0.1738,  ...,  0.0817,  0.0238, -0.1670],
         [-0.3444,  0.0543,  0.1976,  ...,  0.2634,  0.0972,  0.0862],
         [-0.1797, -0.0801,  0.0760,  ..., -0.0429,  0.1264,  0.3009]]),
 'fc5.bias': tensor([-0.0875, -0.2991,  0.3926,  0.0409,  0.1068,  0.1275, -0.1766, -0.2001,
          0.1210, -0.1828, -0.2650, -0.0021,  0.3420,  0.0652,  0.0026, -0.2561,
          0.0513,  0.1469,  0.1025,  0.1907, -0.1172,  0.3409]),
 'fc5.weight': tensor([[ 0.1427,  0.0219,  0.1774, -0.3542, -0.2165, -0.3413, -0.4347,  0.1378,
           0.1959, -0.2177, -0.0628,  0.2581, -0.3144, -0.2523, -0.1861,  0.1275,
          -0.2203, -0.1064,  0.1200,  0.1696, -0.3240,  0.1358,  0.1111, -0.3144,
          -0.0406,  0.0644, -0.4070, -0.1486,  0.1790, -0.2074, -0.0726,  0.2770,
           0.0966,  0.2500],
         [ 0.0762, -0.1951,  0.2186,  0.1162, -0.2468, -0.0850, -0.3356, -0.0504,
           0.1739, -0.1679,  0.1918,  0.1944,  0.2265, -0.2881, -0.4217,  0.0038,
          -0.0551, -0.1363, -0.4081,  0.1659,  0.0485,  0.1108,  0.2674,  0.2009,
           0.2253, -0.0246, -0.0197, -0.3351,  0.1967, -0.0102, -0.2395, -0.2118,
           0.0618,  0.1721],
         [ 0.2052, -0.0537, -0.0582,  0.1880, -0.1323, -0.1423,  0.1709,  0.0538,
           0.1146, -0.3969,  0.0964,  0.1932,  0.0710,  0.1344,  0.0629,  0.0974,
          -0.4195,  0.2642, -0.2816, -0.2684, -0.3987,  0.0729, -0.4514, -0.2830,
           0.1715,  0.1360,  0.1628,  0.2252,  0.2900, -0.0470, -0.1133, -0.3141,
           0.0392,  0.0188],
         [-0.3681,  0.2393, -0.1890,  0.1740,  0.1575, -0.3650,  0.0802,  0.1748,
          -0.0418,  0.1654, -0.1826, -0.1712, -0.2437,  0.3086, -0.3974,  0.1208,
           0.1073, -0.2026,  0.1192, -0.5033, -0.2873, -0.1915, -0.0154, -0.0714,
          -0.2177,  0.3067,  0.0320,  0.2830, -0.3090, -0.5426,  0.2300, -0.1320,
           0.1545, -0.1133],
         [-0.1480, -0.3824, -0.4398, -0.2530,  0.0840,  0.2493, -0.3703, -0.0517,
          -0.0837,  0.2971, -0.2597, -0.1505, -0.1187, -0.3296, -0.2603,  0.1749,
           0.2035,  0.2426,  0.3209,  0.2829,  0.2411, -0.0418, -0.2795, -0.3254,
          -0.3169, -0.4500, -0.4173, -0.1802, -0.3083,  0.1916, -0.2444,  0.3845,
          -0.2821, -0.1681],
         [-0.3864, -0.1052, -0.0936,  0.2356, -0.4201,  0.2453, -0.3301, -0.4377,
          -0.2777,  0.2769, -0.2625, -0.1871,  0.3122, -0.4421, -0.4688, -0.1058,
           0.4030, -0.2008,  0.0205,  0.1646,  0.3049,  0.0777, -0.1302,  0.3252,
           0.0900,  0.1379,  0.0286, -0.2970, -0.1873, -0.0492, -0.4658, -0.1856,
           0.0496, -0.4169],
         [-0.2360, -0.1328,  0.2014,  0.2112, -0.3088,  0.0172,  0.0200, -0.4878,
           0.1138, -0.1913,  0.2076,  0.1466,  0.2824, -0.1438,  0.1224, -0.4413,
          -0.3631,  0.0363, -0.2604, -0.2334,  0.2672, -0.1463,  0.1665,  0.2035,
           0.3056,  0.0401,  0.1333, -0.3568,  0.1412,  0.1770, -0.3533, -0.2975,
           0.0523, -0.3009],
         [ 0.1535,  0.1850,  0.1452, -0.0034, -0.0936, -0.2385,  0.0222,  0.1225,
           0.1550, -0.3610,  0.0457,  0.2679, -0.2847, -0.2420, -0.2448,  0.0732,
          -0.1882, -0.2588,  0.0651,  0.1095, -0.0757,  0.1263,  0.0341, -0.1521,
          -0.3316,  0.2494,  0.0573, -0.1481,  0.1831, -0.2749, -0.2677, -0.3478,
           0.1238,  0.2475],
         [-0.3619, -0.2787,  0.2467,  0.0220, -0.3594,  0.1745, -0.0764, -0.2063,
           0.2311,  0.1251, -0.1518, -0.2353,  0.2887, -0.2322, -0.3765,  0.0049,
           0.2971, -0.0494,  0.0128,  0.2649,  0.2665,  0.1671,  0.1327,  0.2384,
          -0.1535, -0.3668, -0.3227, -0.3710,  0.1224,  0.0587, -0.3612,  0.2228,
          -0.0826, -0.0221],
         [-0.0328,  0.2039, -0.2946,  0.2160, -0.1158, -0.4241,  0.0913, -0.1334,
          -0.1974,  0.1568, -0.3043, -0.2494,  0.1373,  0.2121, -0.2750, -0.1821,
           0.1570, -0.3593,  0.0899, -0.1238, -0.2455,  0.0688, -0.2628, -0.1530,
          -0.1963,  0.3177,  0.0941,  0.0664,  0.1364, -0.1375,  0.2312, -0.2078,
           0.1601,  0.0872],
         [ 0.1217, -0.0072, -0.3475,  0.1981,  0.0885, -0.3698,  0.1886, -0.1204,
          -0.2072, -0.4041, -0.0074,  0.2284,  0.0223,  0.2504,  0.1795, -0.0488,
          -0.2844,  0.2844, -0.4721, -0.0721, -0.1340, -0.2039, -0.1768, -0.2997,
           0.2016,  0.2020,  0.1784,  0.3196,  0.2209, -0.0161,  0.2297, -0.2058,
           0.0380, -0.1357],
         [-0.4197, -0.3134, -0.0559,  0.2449, -0.0846,  0.0231,  0.0669, -0.4356,
          -0.3867,  0.0923,  0.1239, -0.2662,  0.2940, -0.1156,  0.1030, -0.5285,
           0.2700,  0.1558, -0.2457, -0.3305,  0.2531, -0.3085, -0.1883,  0.2301,
           0.2812,  0.3074,  0.1720, -0.1114, -0.0231,  0.1217,  0.0386, -0.4305,
           0.0736, -0.2589],
         [-0.4340,  0.2838, -0.1653, -0.3519,  0.2300,  0.1822, -0.0200,  0.0124,
          -0.1774,  0.3220, -0.2450, -0.1075, -0.2721,  0.2235, -0.1783,  0.2152,
           0.2595, -0.2684,  0.3637, -0.1156, -0.2289,  0.0967, -0.0989, -0.1805,
          -0.3222,  0.2052, -0.1720,  0.1307, -0.3479,  0.0466, -0.5390, -0.1374,
          -0.0899, -0.3201],
         [ 0.0381,  0.1829, -0.1142, -0.0163,  0.2999, -0.1182,  0.1926,  0.0355,
          -0.4065,  0.1395, -0.2312,  0.1630, -0.1742,  0.2627,  0.3027, -0.1145,
          -0.1720,  0.0172,  0.0881, -0.3239, -0.2509, -0.1508,  0.1013,  0.1264,
          -0.2350,  0.2432,  0.0752,  0.2745, -0.0830,  0.0294,  0.1456, -0.4316,
           0.0522, -0.2110],
         [-0.0761, -0.3682, -0.1810, -0.4187,  0.1196, -0.0177,  0.1719,  0.0850,
           0.1839, -0.4180,  0.2676,  0.2600, -0.1682,  0.1196,  0.2919, -0.0761,
          -0.3256,  0.2961, -0.4549, -0.1558,  0.0989, -0.1735, -0.2908, -0.1731,
           0.1866, -0.2470, -0.0229,  0.3167, -0.2098,  0.1695,  0.3234, -0.1265,
          -0.1610, -0.3800],
         [ 0.0636,  0.0229, -0.0447, -0.5276,  0.1880,  0.0077,  0.1849,  0.1018,
           0.2260, -0.3567,  0.2862,  0.2209, -0.2299, -0.3618,  0.2875, -0.3891,
          -0.2835, -0.2308, -0.0719, -0.1816,  0.2012, -0.2142,  0.3520,  0.2320,
           0.1766, -0.1977, -0.1358, -0.1679, -0.0750,  0.1975, -0.1300,  0.1913,
          -0.3815, -0.0616],
         [-0.6528, -0.2601, -0.2966, -0.1762,  0.2551,  0.1503,  0.0339, -0.1213,
           0.1308,  0.1983,  0.0434, -0.2711,  0.1174,  0.3809,  0.2397,  0.0588,
          -0.0901,  0.3562,  0.0344, -0.5449,  0.1520, -0.4488, -0.4376, -0.0591,
           0.0507, -0.1487, -0.0424,  0.3367, -0.2314,  0.2542, -0.4307,  0.2313,
          -0.4030, -0.3717],
         [ 0.0496, -0.5152,  0.0615, -0.4054, -0.0514,  0.1342, -0.0771,  0.2071,
           0.2260, -0.2416,  0.2559,  0.1691, -0.2469, -0.3256,  0.0854,  0.1834,
          -0.0746,  0.2872,  0.0318,  0.1885,  0.0514,  0.1089,  0.0008, -0.2375,
           0.1581, -0.3770, -0.1234, -0.0882,  0.0755,  0.1325, -0.2985,  0.3246,
          -0.0261,  0.1539],
         [ 0.0805,  0.1557, -0.1640,  0.1349, -0.3301, -0.2158,  0.0300,  0.1059,
          -0.1238,  0.1532, -0.0690, -0.0567, -0.0485,  0.0021, -0.1514,  0.1183,
           0.1804, -0.1236,  0.2353,  0.1628, -0.2807,  0.1433, -0.2198, -0.1532,
          -0.0890,  0.2745,  0.0714, -0.1785,  0.2267, -0.3036, -0.2223, -0.2035,
           0.1308,  0.1668],
         [-0.2322, -0.2171, -0.2395, -0.3768,  0.1853,  0.2721, -0.5577, -0.6452,
          -0.4779,  0.3626, -0.4741, -0.2792,  0.1765,  0.0922,  0.1699, -0.0498,
           0.2825,  0.2406,  0.2476, -0.1791,  0.3044, -0.5054, -0.4129,  0.1316,
          -0.0047, -0.3081, -0.3663,  0.2442, -0.2341,  0.2496, -0.3317,  0.2972,
          -0.3811, -0.0449],
         [-0.3031, -0.0434,  0.2130, -0.3012, -0.3124,  0.0633, -0.1514, -0.0627,
           0.2461,  0.1544, -0.3497, -0.2449, -0.2602, -0.1591, -0.0663,  0.0034,
           0.2406, -0.3234,  0.1176,  0.2696,  0.1691,  0.1875,  0.3283,  0.2582,
          -0.2339, -0.1904, -0.4090, -0.0964,  0.1167, -0.1616, -0.1797,  0.2758,
           0.0301,  0.1250],
         [-0.2884, -0.0469, -0.2041, -0.2778,  0.1727,  0.1461,  0.1061, -0.4014,
           0.1445,  0.2214,  0.2346, -0.1038,  0.1501, -0.3917,  0.2658, -0.3861,
          -0.3325, -0.2953, -0.0840, -0.3450,  0.2862, -0.1992,  0.2578,  0.3355,
           0.2222, -0.2349,  0.0130, -0.2830, -0.2701,  0.2047, -0.2088,  0.1553,
          -0.3938, -0.2209]])}

In [79]:
loaded_model.load_state_dict(tensors)

In [80]:
loaded_model.eval()

y_pred = loaded_model(X_test).argmax(dim=1)
acc = accuracy_score(y_test, y_pred)

In [81]:
acc

0.9477272727272728

In [82]:


# Training loop 
epoches = 101

for epoch in range(epoches):
    loaded_model.train()

    out = loaded_model(X_train)
    loss = loss_function(out, y_train)

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    # accuracy
    loaded_model.eval()
    y_pred = loaded_model(X_test).argmax(dim=1)
    acc = accuracy_score(y_test, y_pred)

    if epoch % 10 == 0 :
        print("Epoch: ", epoch, " Loss value: ", loss.item(), " Accuracy: ", acc)

Epoch:  0  Loss value:  0.2816063165664673  Accuracy:  0.9477272727272728
Epoch:  10  Loss value:  0.27972960472106934  Accuracy:  0.9477272727272728
Epoch:  20  Loss value:  0.2761676013469696  Accuracy:  0.9477272727272728
Epoch:  30  Loss value:  0.272148996591568  Accuracy:  0.9477272727272728
Epoch:  40  Loss value:  0.2679167091846466  Accuracy:  0.9477272727272728
Epoch:  50  Loss value:  0.2637617588043213  Accuracy:  0.9477272727272728
Epoch:  60  Loss value:  0.24940131604671478  Accuracy:  0.9477272727272728
Epoch:  70  Loss value:  0.2827868163585663  Accuracy:  0.9477272727272728
Epoch:  80  Loss value:  0.2593800127506256  Accuracy:  0.9477272727272728
Epoch:  90  Loss value:  0.27890193462371826  Accuracy:  0.9477272727272728
Epoch:  100  Loss value:  0.28055354952812195  Accuracy:  0.9477272727272728

## Deploying model on hugging face

In [92]:
!uv add huggingface_hub

Resolved 39 packages in 2ms
Audited 37 packages in 0.53ms

In [93]:
!huggingface-cli login

/bin/bash: line 1: huggingface-cli: command not found

In [94]:
from huggingface_hub import login

In [95]:
login()

In [101]:
from huggingface_hub import HfApi, create_repo

In [102]:
api = HfApi()

In [103]:
# create a repo for our model on hugging face
create_repo(repo_id="Aishwarya240/Crop_Recommendation_Model", repo_type="model", exist_ok=True)

RepoUrl('https://huggingface.co/Aishwarya240/Crop_Recommendation_Model', endpoint='https://huggingface.co', repo_type='model', repo_id='Aishwarya240/Crop_Recommendation_Model')

In [104]:
api.upload_file(
    path_or_fileobj="Models/crop_recommendation.safetensors",
    path_in_repo="crop_recommendation.safetensors",
    repo_id="Aishwarya240/Crop_Recommendation_Model",
    repo_type="model",
)

Processing Files (0 / 0): |          |  0.00B /  0.00B

New Data Upload: |          |  0.00B /  0.00B

CommitInfo(commit_url='https://huggingface.co/Aishwarya240/Crop_Recommendation_Model/commit/d054d8d20accc01e956e765a5ce6d63dfbafaca3', commit_message='Upload crop_recommendation.safetensors with huggingface_hub', commit_description='', oid='d054d8d20accc01e956e765a5ce6d63dfbafaca3', pr_url=None, repo_url=RepoUrl('https://huggingface.co/Aishwarya240/Crop_Recommendation_Model', endpoint='https://huggingface.co', repo_type='model', repo_id='Aishwarya240/Crop_Recommendation_Model'), pr_revision=None, pr_num=None)

## Using uploaded huggingface model

In [105]:
from huggingface_hub import hf_hub_download

In [106]:
file_path = hf_hub_download(repo_id="Sakib-Dalal/Crop_Recommendation_model", filename="crop_recommendation.safetensors")

crop_recommendation.safetensors:   0%|          | 0.00/20.2k [00:00<?, ?B/s]

In [107]:
file_path

'/home/aishwarya/.cache/huggingface/hub/models--Sakib-Dalal--Crop_Recommendation_model/snapshots/745702e83ffd74ff7e0d8335fff82b0f17bfaa01/crop_recommendation.safetensors'

In [108]:
from safetensors.torch import load_file

In [109]:
tensors = load_file(file_path)

In [110]:
tensors

{'fc1.bias': tensor([ 0.1682,  0.2715,  0.3995,  0.0408,  0.6122,  0.2638, -0.3094, -0.3033,
          0.4330,  0.0684, -0.0122, -0.0788,  0.6186,  0.5966]),
 'fc1.weight': tensor([[-0.4099,  0.1586, -0.1997, -0.0978,  0.5617, -0.1307,  0.5204],
         [-0.2615,  0.3210,  0.1499,  0.0720, -0.2259, -0.4872, -0.5836],
         [-0.3312,  0.1528, -0.8624, -0.0855, -0.1428, -0.0802, -0.2462],
         [-0.2278, -0.2462, -0.5358,  0.0399, -0.5327, -0.0098,  0.5400],
         [-0.1217, -0.1039,  0.4865, -0.1106,  0.5684, -0.1610, -0.1555],
         [-0.0585, -0.0673,  0.4725,  0.6143, -0.1365,  0.1546, -0.3258],
         [ 0.3914, -0.2846,  0.1439,  0.1654,  0.3906,  0.1638, -0.6746],
         [-0.2153, -0.2979, -0.5354, -0.0987,  0.2251, -0.0177,  0.0010],
         [-0.1484, -0.0718, -0.7016, -0.0033,  0.3152,  0.2956, -0.0331],
         [-0.2977, -0.6102, -0.0704,  0.2466, -0.0431, -0.4303, -0.0941],
         [ 0.5524, -0.3058, -0.0865, -0.0255, -0.1212,  0.1358, -0.0978],
         [-0.2026,  0.1682,  0.4287, -0.2389, -0.5240,  0.3113, -0.4663],
         [ 0.2653, -0.1294, -0.7108, -0.2422, -0.2852, -0.2151,  0.4630],
         [ 0.0147,  0.5393, -0.0716,  0.4392,  0.4249, -0.0310,  0.3603]]),
 'fc2.bias': tensor([-0.2033, -0.1620,  0.4118,  0.3384, -0.1775, -0.1360,  0.0971, -0.1695,
          0.3360, -0.3572,  0.3031, -0.0146, -0.1432,  0.2032, -0.1542,  0.0593,
         -0.0922,  0.1780,  0.3881,  0.3261, -0.3264,  0.1886, -0.3294,  0.1631,
          0.0339, -0.2365, -0.0895,  0.0207]),
 'fc2.weight': tensor([[-1.4221e-01, -1.6774e-01, -2.6398e-01, -2.0238e-01, -1.7677e-01,
          -1.4254e-02,  6.3772e-02, -1.7976e-01, -1.3650e-01, -1.2756e-01,
          -1.2038e-02,  1.1888e-01, -1.0040e-01,  1.9208e-01],
         [-8.1728e-02,  1.2103e-01,  3.9624e-02,  3.3152e-01, -3.7399e-01,
           6.2675e-01,  2.0817e-01, -1.7671e-01, -9.7532e-02,  2.4015e-01,
          -2.6114e-01,  6.1834e-02,  3.6701e-01, -5.8149e-02],
         [-3.0076e-01, -1.8818e-01, -2.4747e-01,  3.8398e-02,  2.3172e-01,
           1.5735e-01,  1.2873e-02, -1.3814e-01, -9.2083e-02,  4.7107e-01,
           2.3774e-01,  5.0314e-01, -1.8060e-02, -6.4376e-01],
         [-3.0551e-02,  3.6903e-01, -3.9266e-01, -3.6397e-01, -1.0139e-01,
           1.2888e-01, -2.1111e-01, -6.5077e-01,  6.2561e-03, -4.4929e-01,
          -3.9419e-01,  1.1736e-01,  1.2808e-02,  5.6561e-01],
         [ 2.0371e-01, -6.9883e-02, -3.1525e-01,  5.2092e-01,  3.6537e-01,
          -2.1895e-01,  4.5207e-01, -3.0335e-01, -1.5742e-01,  1.4806e-01,
           4.0090e-01, -3.0047e-01, -1.2294e-01,  3.4262e-01],
         [ 3.5175e-01,  3.1839e-01,  1.6174e-01,  4.4945e-01, -2.9797e-01,
           5.2319e-01,  3.8416e-01, -3.7446e-01,  1.0334e-01,  2.5996e-01,
          -3.9215e-01,  8.6879e-02, -2.4205e-01,  2.5178e-02],
         [-4.0457e-02, -1.0623e-01, -4.3043e-02,  4.7160e-01, -4.2127e-01,
           8.6316e-02, -3.6239e-02,  1.8271e-01,  1.2135e-02, -2.4875e-04,
          -4.7649e-01, -2.4681e-01,  4.1665e-01,  2.4027e-01],
         [ 3.7908e-01, -2.6091e-01,  4.3240e-01, -3.3502e-01,  2.9122e-01,
          -2.7967e-01,  9.1293e-02,  9.0494e-02,  2.6407e-01,  1.4638e-02,
          -3.0251e-01, -2.3022e-01,  2.6976e-01,  3.9285e-01],
         [-5.0440e-01,  1.1209e-01, -4.8349e-01,  1.9236e-01, -1.4298e-02,
          -1.3063e-01,  3.4960e-01, -3.7286e-01, -4.6039e-01, -4.2554e-01,
           4.0825e-01,  3.8293e-01,  2.2435e-01,  2.1001e-01],
         [ 2.7819e-01, -1.7305e-01,  2.0502e-01,  4.3450e-01, -2.4073e-02,
           5.6395e-02,  5.1935e-01,  4.0844e-01, -1.4894e-02,  9.9259e-02,
          -2.6893e-01, -2.0348e-01, -1.9809e-01,  3.3390e-01],
         [-6.8579e-01,  1.5308e-01,  1.8072e-01, -4.5451e-01, -1.2993e-01,
          -4.1728e-02, -1.5271e-01, -4.8501e-01, -6.0611e-02, -2.7406e-01,
          -4.3991e-01,  4.5449e-01,  2.4901e-01, -2.0064e-02],
         [ 2.7687e-01,  2.5937e-01,  3.0035e-01, -5.2445e-01,  2.9952e-01,
           1.4422e-01,  6.8782e-02, -3.7146e-01,  8.2348e-02, -4.2348e-01,
          -2.5140e-01,  2.7136e-01, -5.0437e-01,  3.5120e-01],
         [ 7.9212e-02,  2.1647e-01,  4.0039e-01,  3.2002e-01, -3.4831e-01,
           4.7734e-01,  4.5546e-01, -1.3672e-01,  1.7477e-01,  8.7592e-02,
          -4.6242e-01,  1.4915e-01, -1.8491e-01, -1.8222e-02],
         [-1.6643e-01,  1.7219e-01,  6.8716e-02, -3.6391e-01, -4.2488e-01,
           3.4084e-02, -2.0847e-01, -1.5946e-01, -2.8314e-01, -3.7266e-01,
          -2.2855e-01,  2.0071e-01,  4.6165e-01,  5.1253e-01],
         [ 1.6616e-01,  7.0610e-02, -8.5979e-03,  6.7868e-02, -1.3141e-02,
          -6.2563e-02, -1.1819e-01,  1.1550e-01, -1.5908e-02, -2.2517e-01,
          -1.4189e-01, -1.4538e-01, -2.2505e-01, -5.1031e-02],
         [ 1.5937e-01,  1.7067e-01, -3.3927e-01, -6.6216e-02,  3.9031e-01,
           2.1515e-01,  1.5874e-01, -2.3153e-01, -4.1805e-01, -2.9760e-01,
          -1.8654e-01,  4.2354e-01, -3.9312e-01,  4.2144e-01],
         [-1.5387e-01,  2.9375e-01,  4.1783e-01,  2.9839e-01, -3.5414e-01,
           4.0645e-01,  2.5013e-02, -2.7280e-03,  2.8863e-01,  1.0041e-01,
          -2.6926e-01,  2.0261e-01, -1.0000e-02, -7.7540e-02],
         [ 2.7755e-01, -3.7755e-01,  9.1048e-02,  1.1017e-01,  3.7415e-01,
          -3.1126e-01,  2.5659e-01,  5.2326e-03,  2.6589e-01,  4.3790e-02,
          -3.7809e-01, -3.5267e-01, -1.9760e-01,  4.3258e-01],
         [-3.5512e-01,  9.1059e-02,  8.9825e-02,  3.1439e-01, -2.2611e-01,
          -4.6205e-02, -2.2687e-01, -4.6824e-01, -2.2358e-01, -2.3683e-01,
          -2.6305e-01,  2.6284e-01,  4.1345e-01,  4.9977e-02],
         [ 4.0415e-01, -2.8585e-01, -1.8469e-01, -3.1134e-01,  3.0515e-02,
           2.1838e-03, -1.3538e-01,  9.1179e-02,  2.3929e-01, -5.0222e-02,
          -2.5834e-01, -2.6406e-01, -1.1886e-01,  3.7940e-01],
         [-1.9704e-01, -2.6827e-01,  2.1127e-01,  4.6405e-01, -2.9989e-01,
          -3.3215e-01,  1.8616e-01,  2.9476e-01,  4.2854e-01,  4.4246e-01,
           2.1709e-01, -1.2036e-01,  4.5088e-01, -1.5622e-01],
         [-4.3310e-01,  1.5487e-01,  3.2741e-01, -7.2356e-01, -3.0382e-01,
          -3.2623e-01,  2.4670e-02,  3.9365e-01,  5.8354e-01,  1.5567e-01,
          -3.4486e-02, -3.5442e-01,  1.0842e-01, -1.3257e-01],
         [ 4.1352e-01,  1.9077e-02, -1.0727e-01,  4.5119e-01, -3.2138e-01,
           1.2600e-01, -3.8292e-01, -3.4223e-03,  5.5521e-02, -6.2421e-02,
          -1.1563e-01, -1.9420e-01,  4.2734e-01,  1.0463e-01],
         [-6.9538e-01,  2.0245e-01, -1.2358e-01, -2.8300e-01,  4.2713e-01,
          -1.1682e-01, -5.0855e-02, -2.1897e-01, -3.7884e-01, -2.3254e-01,
           3.5703e-01,  4.7325e-01,  2.9090e-01, -6.7170e-02],
         [ 2.2207e-01,  2.2952e-01, -3.0521e-01,  2.5528e-02,  5.1103e-01,
           2.9055e-01,  2.7825e-01,  8.1675e-02, -2.7642e-01,  4.7489e-01,
          -5.0189e-02, -1.5246e-01, -4.1827e-01,  1.0470e-01],
         [ 5.4579e-02, -1.6115e-01,  2.3403e-02,  3.8961e-01,  3.2281e-01,
           3.1228e-01,  4.0395e-01,  6.8833e-02,  1.7223e-01,  5.4139e-01,
          -3.1297e-01, -6.9247e-02, -2.7938e-01,  1.1490e-02],
         [-1.6506e-01,  2.6765e-01,  2.7167e-01, -5.9160e-01,  5.8118e-01,
           2.4833e-01, -3.8113e-01, -4.0633e-02,  1.3785e-02,  2.5311e-01,
          -2.8842e-01,  2.5876e-01, -4.4245e-01, -5.5662e-01],
         [ 4.2966e-02, -3.0567e-01, -6.1754e-01,  4.3351e-01,  3.5381e-02,
          -1.4471e-01,  4.1443e-01, -1.4932e-01,  1.3702e-01,  1.3123e-01,
           2.8491e-01, -3.0706e-01, -1.1620e-03,  3.1646e-01]]),
 'fc3.bias': tensor([-0.2623,  0.2572, -0.2494, -0.0767,  0.0114, -0.3346,  0.0646,  0.3485,
         -0.1246,  0.2592,  0.1646,  0.4003, -0.1141,  0.1770,  0.1370,  0.1006,
         -0.2805,  0.2803,  0.1436,  0.1373,  0.0232,  0.2036,  0.3532,  0.2875,
          0.3567,  0.3255,  0.1688,  0.1775, -0.2304,  0.3041,  0.0183, -0.3250,
         -0.1549,  0.1958,  0.4012,  0.2688, -0.0521, -0.0861,  0.4376,  0.1254,
         -0.1784, -0.2827,  0.1221,  0.0564,  0.3346,  0.0103, -0.2264, -0.0126,
          0.0054,  0.2665,  0.2052, -0.3354, -0.3242, -0.3100,  0.0400, -0.3989]),
 'fc3.weight': tensor([[-0.0938,  0.0374,  0.1307,  ...,  0.0199,  0.1241, -0.1403],
         [-0.0661,  0.2519,  0.1207,  ..., -0.0426, -0.3628,  0.1748],
         [-0.1396,  0.3085,  0.2855,  ...,  0.0470,  0.1693, -0.0254],
         ...,
         [-0.1661,  0.1404, -0.3685,  ...,  0.1004, -0.2760,  0.2443],
         [ 0.1161,  0.2349,  0.0555,  ...,  0.1647,  0.1142, -0.1625],
         [ 0.1600,  0.2417,  0.4181,  ..., -0.0358,  0.3663, -0.2381]]),
 'fc4.bias': tensor([ 0.2784, -0.2556, -0.0938, -0.0039,  0.3821, -0.1551,  0.2486, -0.1543,
         -0.0863,  0.2411, -0.0708, -0.0318, -0.0173,  0.0616,  0.0424,  0.2472,
          0.1103, -0.1897,  0.0784,  0.0939, -0.0580,  0.1770, -0.1314, -0.2240,
         -0.0181, -0.2446, -0.2485,  0.0930,  0.2596, -0.0169,  0.2492,  0.0421,
          0.1921, -0.2509]),
 'fc4.weight': tensor([[-0.4046,  0.1522, -0.2614,  ..., -0.2168,  0.1933, -0.3159],
         [-0.2101,  0.1053, -0.0197,  ...,  0.2826,  0.1007, -0.2262],
         [ 0.3544, -0.2124,  0.3381,  ...,  0.2944,  0.0542, -0.0337],
         ...,
         [-0.1635, -0.0801, -0.0787,  ...,  0.0361, -0.0140, -0.2164],
         [ 0.1282,  0.3288,  0.1602,  ...,  0.0930, -0.2732,  0.1164],
         [ 0.3467, -0.2117,  0.4347,  ...,  0.1371,  0.1604,  0.2761]]),
 'fc5.bias': tensor([-0.1957,  0.1280,  0.3580, -0.2437, -0.2661,  0.0268,  0.1602, -0.1882,
          0.3262, -0.2940, -0.0078,  0.2507,  0.0946, -0.0424, -0.0132, -0.3033,
          0.0433, -0.2318, -0.0139,  0.2104, -0.3315,  0.1951]),
 'fc5.weight': tensor([[-1.8164e-01, -1.4335e-01,  2.4540e-01,  1.3833e-01,  6.1709e-02,
          -1.0484e-02, -3.9262e-01, -3.4271e-01,  4.7146e-02, -1.3883e-01,
           6.5973e-02, -1.4994e-01, -1.5077e-02,  1.5681e-01,  3.5649e-02,
          -7.4269e-03,  2.1257e-01,  7.5520e-02, -2.8869e-01,  2.1606e-02,
          -6.7306e-02, -2.3914e-01, -9.4732e-02,  7.9998e-02,  2.2207e-01,
           5.8700e-02, -3.2749e-01,  2.3720e-01, -7.2447e-02,  1.5619e-01,
          -3.7585e-01, -3.4145e-02,  1.1810e-01,  2.6481e-01],
         [-2.7808e-01, -5.5266e-01,  2.1066e-01,  1.6893e-02,  2.7139e-01,
           6.7125e-03, -3.5017e-01, -4.0684e-01,  5.2521e-02,  6.4797e-02,
           2.0832e-01, -4.1619e-01, -3.1737e-01,  1.9171e-01, -2.0166e-01,
           1.8193e-01,  5.9435e-02, -2.2841e-01, -1.4297e-01,  9.1084e-02,
           3.5254e-02, -2.3415e-02,  1.5354e-01, -3.0341e-01,  1.1952e-01,
          -3.5940e-02, -5.3788e-01,  2.3668e-01,  2.4017e-01, -1.5047e-01,
           4.7162e-02, -1.7152e-01,  2.0562e-01,  1.6245e-01],
         [ 1.3072e-01, -8.1725e-02,  2.9158e-01, -5.3644e-01,  1.1558e-01,
           2.3763e-01,  1.4391e-01,  2.5132e-01,  2.4779e-01,  3.4202e-02,
           5.0984e-02,  5.7696e-02,  1.0557e-01, -2.6775e-01, -3.3843e-01,
           6.7628e-02, -3.7299e-01,  6.5389e-03,  2.7481e-01, -2.1156e-01,
          -2.3924e-01, -3.8191e-01, -3.2630e-01,  6.6175e-02, -1.9904e-02,
           1.6406e-01, -1.2912e-01, -1.8606e-02,  9.1029e-02,  2.1911e-01,
          -1.5758e-01, -9.6009e-02, -3.8524e-01,  1.2115e-01],
         [-3.2713e-01, -2.0330e-01,  3.5949e-02,  1.5985e-01,  4.4467e-02,
           2.4733e-01, -1.9320e-01,  1.7586e-01,  1.9452e-01, -1.8610e-02,
          -1.8925e-03,  2.8475e-01, -3.0712e-01, -1.9902e-01,  3.1906e-01,
          -4.1256e-01, -3.6900e-01,  1.1482e-01,  3.0419e-02, -2.1100e-01,
           3.5245e-01,  5.2142e-02, -2.1138e-01, -2.6978e-01,  1.2249e-01,
           1.1076e-01, -3.1268e-01, -3.7857e-01,  1.4543e-02, -2.2322e-01,
           3.5856e-02, -3.3626e-01, -1.0258e-01,  2.4340e-01],
         [ 7.4742e-02,  1.9177e-01, -1.1915e-01, -2.5421e-01, -4.2224e-01,
          -3.6853e-01,  2.7377e-01, -8.6808e-02, -4.4439e-01, -2.2023e-01,
           1.7355e-01, -1.7122e-01,  2.4350e-01,  5.5833e-02, -1.9989e-01,
           1.6761e-01,  1.3789e-01, -2.2841e-01, -2.5382e-01,  1.3766e-01,
          -6.8374e-02, -1.3163e-01,  3.1315e-01,  1.7567e-01, -4.4282e-01,
          -3.4138e-01,  1.5482e-01,  2.5926e-01, -3.5778e-01, -1.2043e-01,
          -1.8216e-01,  2.8988e-01,  9.7825e-02, -4.2102e-01],
         [ 1.3466e-01,  3.7617e-02, -5.2437e-01,  1.9046e-01,  2.1331e-01,
           1.5998e-01,  7.6560e-02, -6.4361e-02, -1.4285e-01,  1.8281e-01,
           1.0111e-01,  5.3287e-03, -2.1498e-01, -2.3451e-01, -1.0962e-01,
           5.7146e-02, -4.5374e-01, -5.1914e-01, -3.9032e-01,  2.8821e-01,
           2.7364e-01,  3.4174e-01,  1.1095e-01, -1.1197e-01, -1.1733e-01,
          -2.0974e-01,  2.2336e-01, -4.7988e-01,  2.1117e-01, -3.7570e-01,
           2.6542e-01, -4.2129e-01,  1.1106e-01, -2.2093e-01],
         [ 2.3273e-01, -3.6775e-01, -3.2110e-01,  1.5250e-01,  4.7457e-01,
           9.7506e-03, -6.3126e-02, -4.3980e-01, -3.9288e-01,  3.6213e-01,
          -1.4299e-01, -4.1189e-01, -2.4633e-01,  2.1551e-01,  9.4989e-02,
           2.3922e-01,  4.8628e-02, -3.3758e-02, -8.3288e-02,  2.9191e-01,
           9.8244e-02,  2.8737e-01, -2.5629e-01, -2.2844e-01, -5.8409e-01,
          -3.6278e-01, -3.1148e-01, -2.3771e-01,  2.1692e-01, -9.9696e-02,
           2.7713e-01,  2.0730e-01,  1.4438e-01, -3.6195e-01],
         [-2.4680e-01, -2.6593e-01,  2.1798e-01,  1.9306e-01, -3.6370e-02,
           6.0426e-02, -3.0964e-01,  6.8402e-02,  8.0981e-02, -2.7864e-01,
          -5.4420e-02,  2.0058e-01,  1.1377e-01,  1.0954e-01,  8.0405e-02,
          -3.0767e-01,  1.3136e-01,  1.0608e-01, -6.4364e-02, -2.7824e-01,
           2.4267e-01, -3.2672e-01, -1.6894e-01, -5.8419e-02,  2.3358e-01,
           1.1596e-01, -5.0056e-02,  1.5248e-01, -5.9290e-02,  6.7860e-02,
          -2.0320e-01, -4.3997e-01,  4.6849e-02,  2.9652e-01],
         [-1.1176e-02,  1.0069e-01,  1.3054e-01, -3.5213e-01,  2.3306e-01,
           6.8317e-02,  5.2122e-02, -3.6217e-01, -7.1125e-02,  1.1108e-01,
           2.8434e-01, -3.8681e-01, -3.5011e-01,  1.8226e-02, -3.4277e-01,
           1.7925e-01, -3.0742e-01, -3.3333e-01, -9.2561e-02,  1.2987e-01,
          -5.1629e-02,  4.5598e-02,  1.9453e-01, -2.9647e-01, -4.7132e-01,
          -3.0812e-01,  1.0530e-01,  1.5112e-01,  2.7915e-01, -1.6659e-01,
           1.5382e-01,  4.1178e-02,  1.8816e-01, -1.9140e-01],
         [-1.9860e-01, -1.0037e-01, -4.1768e-01,  6.6502e-02, -4.0616e-01,
           2.4902e-01,  1.1903e-01,  2.6208e-01,  1.7733e-01,  1.3320e-01,
           1.3087e-01,  1.9621e-01,  8.4750e-02, -3.3627e-01, -3.5622e-01,
          -2.6184e-01, -2.9971e-01, -7.5426e-02,  6.9585e-02, -3.8535e-01,
           2.4766e-01,  2.0700e-01,  1.1872e-01, -3.4054e-01, -2.2999e-01,
           1.5921e-01,  1.8596e-01, -2.4019e-01,  1.3902e-01, -3.9700e-01,
           2.4030e-01, -2.7191e-01, -2.4680e-01,  1.8762e-01],
         [ 1.8920e-01, -3.5580e-01,  1.6988e-01, -1.3288e-01,  2.2596e-01,
           1.8144e-01, -3.5629e-02,  2.4084e-01,  2.3193e-01,  1.2073e-01,
          -4.2139e-01,  2.0381e-01,  1.0249e-01, -3.0103e-01, -1.5194e-01,
          -3.5112e-01, -1.4278e-01,  3.4938e-01,  3.4354e-01, -4.4480e-02,
          -1.2451e-01, -3.8045e-01, -8.8080e-02, -4.6184e-02,  1.0564e-01,
           1.7981e-01, -3.8894e-01, -3.0913e-01, -1.4454e-01,  3.2690e-01,
          -2.0876e-01, -6.7034e-02, -3.4451e-01,  1.3175e-01],
         [ 2.7782e-01, -3.9870e-01, -2.8053e-01,  1.3879e-01,  3.4355e-01,
           1.7194e-01,  1.1194e-01,  1.1837e-01,  7.1608e-02,  3.6288e-01,
          -3.5802e-02, -5.4436e-02, -1.8926e-01, -2.5084e-01, -1.6789e-01,
           7.8963e-02, -3.8555e-01,  1.9743e-01,  3.7051e-01, -1.2243e-01,
           1.2802e-01,  2.2952e-01, -3.6617e-01, -3.5333e-01, -2.7463e-01,
          -2.6817e-01, -2.7513e-01, -2.5426e-01,  3.0693e-01, -2.4861e-01,
           2.9557e-01, -1.4348e-01, -4.9938e-02, -4.9273e-01],
         [ 3.7557e-02,  1.9490e-01, -4.2608e-01, -4.0932e-03, -3.4637e-01,
          -1.4218e-01,  2.5887e-01,  2.7955e-01,  5.7757e-02, -2.4607e-01,
          -2.7820e-03,  2.1935e-01,  3.1279e-01, -7.9003e-02,  3.2676e-04,
          -4.2866e-01, -9.9129e-02, -2.6596e-01, -1.8060e-01, -1.1873e-01,
          -3.7753e-01,  2.7345e-01, -2.1721e-01,  2.4073e-01,  6.4838e-02,
           1.5583e-01,  2.6384e-01, -3.3842e-01, -2.6544e-01, -1.8315e-01,
           1.7410e-01, -1.2771e-01, -3.1610e-01, -2.0037e-02],
         [ 1.2703e-01, -1.5209e-01, -3.8296e-01,  5.1203e-02, -2.8195e-01,
           1.2207e-01,  1.7410e-01,  2.7171e-01,  1.6824e-01, -1.0616e-01,
          -2.7877e-01,  2.5802e-01,  2.2533e-01, -2.4801e-01,  5.8137e-02,
          -4.0988e-01, -1.7819e-01,  2.9852e-01,  2.7231e-01, -3.2909e-02,
          -7.4197e-02, -9.6541e-02, -1.7487e-01,  9.0187e-02,  7.3194e-02,
           1.9239e-01,  1.2888e-01, -3.3871e-01, -2.0046e-01,  2.2322e-01,
          -3.8186e-02, -1.3833e-01, -3.1065e-01,  5.5344e-02],
         [ 1.3459e-01, -9.6467e-02,  1.1626e-01, -4.2945e-01, -1.1836e-01,
          -4.5923e-01,  2.3133e-01,  2.0104e-01,  9.3427e-02, -4.3746e-01,
          -3.6058e-01, -3.2081e-02,  2.6966e-01, -2.2015e-01, -7.4113e-03,
           2.8693e-02,  1.7488e-01,  2.9998e-01,  2.7868e-01, -5.0156e-01,
          -7.9874e-02, -1.7889e-01, -4.5805e-01,  2.4045e-01,  2.8824e-02,
           8.4338e-02, -1.9476e-01,  2.2053e-01, -3.7547e-01,  3.4044e-01,
          -2.8525e-01,  2.2755e-01, -4.4595e-01, -6.6313e-02],
         [-4.7133e-01,  7.5201e-02, -2.6232e-01,  2.2155e-01, -3.7843e-01,
          -1.0770e-01,  1.2516e-04,  1.0361e-02, -2.2680e-01, -1.9219e-01,
          -3.0879e-01,  1.3454e-02, -5.5649e-02,  2.2828e-01,  2.9474e-01,
          -3.7527e-02,  2.7682e-01, -7.1574e-02, -2.5823e-01,  2.7611e-01,
          -1.1524e-01, -1.9278e-01,  2.2396e-01,  2.3999e-01,  7.2924e-02,
           4.2652e-02,  1.8384e-01,  1.1956e-01, -3.7766e-01, -3.1921e-01,
          -2.9216e-02,  1.7034e-01,  1.5196e-01,  1.3092e-01],
         [ 2.9772e-01,  1.3286e-01, -5.6662e-02, -1.7787e-01,  4.0727e-02,
          -2.7991e-01,  3.2969e-01,  1.4247e-01, -2.4353e-01,  9.5060e-02,
           1.4961e-02, -1.0238e-01,  2.7573e-01, -3.8431e-01, -3.9581e-01,
           1.4283e-01,  9.8498e-02, -4.4210e-01,  2.5206e-01, -4.3203e-01,
          -3.1308e-01, -2.5151e-01,  7.3384e-02,  1.8410e-01, -2.8227e-01,
          -2.0686e-01,  2.2302e-01,  2.3092e-01, -1.8717e-01,  2.1821e-01,
          -1.3917e-02,  2.8921e-01, -3.8580e-01, -2.6178e-01],
         [-4.0408e-01,  5.6297e-02,  2.2826e-01, -1.5376e-01, -6.3776e-03,
          -6.9453e-02,  1.1470e-01,  1.6851e-03,  5.1792e-02, -3.0446e-01,
           2.3169e-01, -1.2176e-01,  2.8628e-02,  9.2085e-02, -6.1718e-02,
           1.5562e-01,  1.6378e-01, -3.5299e-02, -2.9443e-01,  1.0310e-02,
          -3.8129e-01, -2.3258e-01,  2.1305e-01,  2.0778e-01,  9.9504e-02,
          -6.5905e-03,  1.2434e-02,  2.4533e-01, -4.9128e-02,  1.7717e-01,
          -2.0247e-01,  1.6480e-01,  6.6881e-02,  1.7433e-01],
         [-1.7165e-01,  2.2865e-01, -8.2912e-02, -3.8729e-01, -2.7202e-01,
           1.6267e-01,  2.0804e-01,  2.5316e-01,  1.3539e-01,  5.4089e-02,
           2.2379e-01,  1.1458e-01,  2.2347e-01, -2.4013e-01, -3.8733e-01,
           1.0662e-01, -2.9435e-01, -3.2354e-01,  1.2721e-01, -1.6950e-01,
          -3.0647e-01,  1.0496e-01,  1.9671e-01,  2.0972e-01, -3.1777e-01,
           8.4574e-02,  2.1234e-01, -1.2189e-01,  4.7601e-02, -2.4080e-01,
           1.5967e-01, -3.0485e-02, -2.5776e-01,  7.7971e-02],
         [ 2.3284e-01, -6.3353e-02, -1.3441e-01, -7.1495e-02,  1.1387e-01,
          -3.8818e-01,  2.6908e-01, -1.8773e-01, -4.3262e-01, -6.4070e-04,
          -2.7355e-01, -2.9190e-01,  2.6871e-01,  2.2720e-01,  1.0422e-01,
           1.0640e-01,  2.7838e-01,  1.5297e-01,  1.2881e-01, -1.6533e-01,
          -3.7826e-01,  1.5430e-02, -3.6860e-01, -3.1478e-04, -3.7725e-01,
          -1.8031e-01, -3.4915e-01,  3.0542e-01, -3.8658e-01,  2.5997e-01,
          -3.4384e-01,  3.2290e-01, -1.6634e-02, -4.7610e-01],
         [-2.3172e-01,  2.0924e-01,  9.7613e-02, -2.1539e-01, -1.2353e-01,

In [114]:
class CropRecommendationModelSakib(nn.Module):
    def __init__(self):
        super(CropRecommendationModelSakib, self).__init__()

        # layers
        self.fc1 = nn.Linear(7, 14)
        self.relu1 = nn.ReLU()
        
        # ------ hidden layer
        self.fc2 = nn.Linear(14, 28)
        self.relu2 = nn.ReLU()
        self.do1 = nn.Dropout(0.2)
        
        self.fc3 = nn.Linear(28, 56)
        self.relu3 = nn.ReLU()
        self.do2 = nn.Dropout(0.2)
        
        self.fc4 = nn.Linear(56, 34)
        self.relu4 = nn.ReLU()
        self.do3 = nn.Dropout(0.1)
        # -------
        self.fc5 = nn.Linear(34, 22) # output layer

    def forward(self, x):
        x = self.fc1(x) # input layer
        x = self.relu1(x)
        

        # hidden layer
        x = self.fc2(x)
        x = self.relu2(x)
        x = self.do1(x)
        
        x = self.fc3(x)
        x = self.relu3(x)
        x = self.do2(x)
        
        x = self.fc4(x)
        x = self.relu4(x)
        x = self.do3(x)

        x = self.fc5(x) # output layer

        return x

In [115]:
model = CropRecommendationModelSakib()
model

CropRecommendationModelSakib(
  (fc1): Linear(in_features=7, out_features=14, bias=True)
  (relu1): ReLU()
  (fc2): Linear(in_features=14, out_features=28, bias=True)
  (relu2): ReLU()
  (do1): Dropout(p=0.2, inplace=False)
  (fc3): Linear(in_features=28, out_features=56, bias=True)
  (relu3): ReLU()
  (do2): Dropout(p=0.2, inplace=False)
  (fc4): Linear(in_features=56, out_features=34, bias=True)
  (relu4): ReLU()
  (do3): Dropout(p=0.1, inplace=False)
  (fc5): Linear(in_features=34, out_features=22, bias=True)
)

In [116]:
model.load_state_dict(tensors)

In [117]:
y_pred = model(X_test).argmax(dim=1)
acc= accuracy_score(y_test, y_pred)

In [118]:
acc

0.8818181818181818

- Lets retrain sakib model

In [121]:
optimizer = torch.optim.Adam(model.parameters(), lr=0.001)
loss_function = nn.CrossEntropyLoss()

In [122]:

# Training loop 
epoches = 101

for epoch in range(epoches):
    model.train()

    out = loaded_model(X_train)
    loss = loss_function(out, y_train)

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    # accuracy
    model.eval()
    y_pred = model(X_test).argmax(dim=1)
    acc = accuracy_score(y_test, y_pred)

    if epoch % 10 == 0 :
        print("Epoch: ", epoch, " Loss value: ", loss.item(), " Accuracy: ", acc)

Epoch:  0  Loss value:  0.08622344583272934  Accuracy:  0.9613636363636363
Epoch:  10  Loss value:  0.08622344583272934  Accuracy:  0.9613636363636363
Epoch:  20  Loss value:  0.08622344583272934  Accuracy:  0.9613636363636363
Epoch:  30  Loss value:  0.08622344583272934  Accuracy:  0.9613636363636363
Epoch:  40  Loss value:  0.08622344583272934  Accuracy:  0.9613636363636363
Epoch:  50  Loss value:  0.08622344583272934  Accuracy:  0.9613636363636363
Epoch:  60  Loss value:  0.08622344583272934  Accuracy:  0.9613636363636363
Epoch:  70  Loss value:  0.08622344583272934  Accuracy:  0.9613636363636363
Epoch:  80  Loss value:  0.08622344583272934  Accuracy:  0.9613636363636363
Epoch:  90  Loss value:  0.08622344583272934  Accuracy:  0.9613636363636363
Epoch:  100  Loss value:  0.08622344583272934  Accuracy:  0.9613636363636363

In [123]:
y_pred = model(X_test).argmax(dim=1)
acc = accuracy_score(y_test, y_pred)

In [124]:
acc

0.9613636363636363