# My first FFN

# Classification 
---
Types of classification: https://www.geeksforgeeks.org/machine-learning/getting-started-with-classification/

---

- Binary Classification

- Loading our binary classification data

In [1]:
import pandas as pd

In [2]:
data = pd.read_csv("Datasets/heart.csv")

data.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0

In [3]:
# Seperating features and target as X and Y
X = data.drop("HeartDisease", axis=1)
y = data["HeartDisease"]

X.shape, y.shape

((918, 11), (918,))

In [4]:
X

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up
...,...,...,...,...,...,...,...,...,...,...,...
913,45,M,TA,110,264,0,Normal,132,N,1.2,Flat
914,68,M,ASY,144,193,1,Normal,141,N,3.4,Flat
915,57,M,ASY,130,131,0,Normal,115,Y,1.2,Flat
916,57,F,ATA,130,236,0,LVH,174,N,0.0,Flat
917,38,M,NAP,138,175,0,Normal,173,N,0.0,Up

In [5]:
y

0      0
1      1
2      0
3      1
4      0
      ..
913    1
914    1
915    1
916    1
917    0
Name: HeartDisease, Length: 918, dtype: int64

In [6]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
col = ["Sex", "ChestPainType", "RestingECG", "ExerciseAngina", "ST_Slope"]

X[col] = X[col].apply(le.fit_transform)

X.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope
0,40,1,1,140,289,0,1,172,0,0.0,2
1,49,0,2,160,180,0,1,156,0,1.0,1
2,37,1,1,130,283,0,2,98,0,0.0,2
3,48,0,0,138,214,0,1,108,1,1.5,1
4,54,1,2,150,195,0,1,122,0,0.0,2

- Train test split data (80% training, 20% testing)

In [7]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

X_train.shape, X_test.shape, y_train.shape, y_test.shape

((734, 11), (184, 11), (734,), (184,))

In [8]:
# Convert data to tensors

import torch

X_train_tensor = torch.tensor(X_train.values, dtype=torch.float)
X_test_tensor = torch.tensor(X_test.values, dtype=torch.float)

y_train_tensor = torch.tensor(y_train.values, dtype=torch.long)
y_test_tensor = torch.tensor(y_test.values, dtype=torch.long)

- Building classification model

In [9]:
import torch
import torch.nn as nn

In [10]:
model = nn.Sequential(
    # Layer 1
    nn.Linear(11, 22),
    nn.ReLU(),

    # Layer 2
    nn.Linear(22, 44),
    nn.ReLU(),

    # Layer 3
    nn.Linear(44, 22),
    nn.ReLU(),

    # Layer 4
    nn.Linear(22, 1),
    nn.Sigmoid()
)

print(model)

Sequential(
  (0): Linear(in_features=11, out_features=22, bias=True)
  (1): ReLU()
  (2): Linear(in_features=22, out_features=44, bias=True)
  (3): ReLU()
  (4): Linear(in_features=44, out_features=22, bias=True)
  (5): ReLU()
  (6): Linear(in_features=22, out_features=1, bias=True)
  (7): Sigmoid()
)

In [11]:
single_layer_example = nn.Linear(11, 22)

In [12]:
single_layer_example(X_train_tensor).shape

torch.Size([734, 22])

In [13]:
# Now decide out loss function for binary classification task

loss_function = nn.BCELoss()

# decide the optimizer we will be using
optimizer = torch.optim.Adam(model.parameters(), lr=0.01)

In [14]:
from sklearn.metrics import accuracy_score

In [15]:
# training loop for our model

for epoch in range(101):
    model.train() # Good practice
    out = model(X_train_tensor)
    loss = loss_function(out, y_train_tensor.unsqueeze(dim=1).float())

    optimizer.zero_grad() # Clears old gradients, NOT weights
    loss.backward()
    optimizer.step()

    # Evaluation Mode
    model.eval() 
    with torch.no_grad(): # Saves memory/time during testing
        y_pred = model(X_test_tensor)
        y_pred_class = (y_pred > 0.5).int()

    # Now calculate accuracy
    accuracy = accuracy_score(y_test_tensor.unsqueeze(dim=1).float().detach().numpy(), y_pred_class.detach().numpy())

    if epoch % 10 == 0:
        print("Current epoch: ", epoch, "| And current loss: ", loss.item(), "| Model Accuracy: ", accuracy)

Current epoch:  0 | And current loss:  1.5847407579421997 | Model Accuracy:  0.5597826086956522
Current epoch:  10 | And current loss:  0.6363560557365417 | Model Accuracy:  0.5597826086956522
Current epoch:  20 | And current loss:  0.6122558116912842 | Model Accuracy:  0.6086956521739131
Current epoch:  30 | And current loss:  0.5696879029273987 | Model Accuracy:  0.6739130434782609
Current epoch:  40 | And current loss:  0.5309066772460938 | Model Accuracy:  0.6902173913043478
Current epoch:  50 | And current loss:  0.5122545957565308 | Model Accuracy:  0.7065217391304348
Current epoch:  60 | And current loss:  0.49069878458976746 | Model Accuracy:  0.7228260869565217
Current epoch:  70 | And current loss:  0.4724256694316864 | Model Accuracy:  0.7391304347826086
Current epoch:  80 | And current loss:  0.4486904740333557 | Model Accuracy:  0.75
Current epoch:  90 | And current loss:  0.42201557755470276 | Model Accuracy:  0.7608695652173914
Current epoch:  100 | And current loss:  0.3962147533893585 | Model Accuracy:  0.7934782608695652

# Classic Pytorch Model(Recommended) # IMP

In [16]:
# Example class creation - demo practice
class ExampleClass:
    def __init__(self):
        print("Hello")
        # Use of self key on variable
        self.a = 1
        print(self.a)
        
    # Method
    def forward(self, name):
        print("Your name is:", name)
        # Update variable having self key
        self.a = 100
        print(self.a)
        

# object = class()
a = ExampleClass()

# calling a method for class ExampleClass with name as input parameter
a.forward(name="Aish")

Hello
1
Your name is: Aish
100

- To create a Deep learning AI model in pytorch we use classes.

In [17]:
class BCModel(nn.Module):
    def __init__(self):
        super(BCModel, self).__init__() # Calling nn.Module constructor from BCModel constructor

        # Model layer 
        self.fc1 = nn.Linear(11, 22)
        self.fc2 = nn.Linear(22, 44)
        self.fc3 = nn.Linear(44, 22)
        self.fc4 = nn.Linear(22, 1)

        self.sigmoid = nn.Sigmoid()

    def forward(self, x):
        out = self.fc1(x)
        out = self.fc2(out)
        out = self.fc3(out)
        out = self.fc4(out)
        out = self.sigmoid(out)

        return out

In [18]:
# object = class name
my_model = BCModel()
my_model.to(device=torch.device("cuda"))

BCModel(
  (fc1): Linear(in_features=11, out_features=22, bias=True)
  (fc2): Linear(in_features=22, out_features=44, bias=True)
  (fc3): Linear(in_features=44, out_features=22, bias=True)
  (fc4): Linear(in_features=22, out_features=1, bias=True)
  (sigmoid): Sigmoid()
)

In [19]:
# loss function for Binary Classification - Binary Cross Entropy
loss_function = nn.BCELoss()

In [20]:
# Optimizer - Adam
optimizer = torch.optim.Adam(my_model.parameters(), lr=0.001)

In [21]:
# training Binary Classification Model
X_train_tensor = X_train_tensor.to(device=torch.device("cuda"))
y_train_tensor = y_train_tensor.to(device=torch.device("cuda"))
epochs = 100

for epoch in range(epochs):
    # put model in training mode 
    my_model.train()

    # y_train target for X_train
    y_target = y_train_tensor.unsqueeze(dim=1).float()

    # predict value
    out = my_model(X_train_tensor)
    # calculate loss between predicted value and actual value of input x
    loss = loss_function(out, y_target)

    # now adjust the values of weights and biases in neurons using optimizer and loss
    optimizer.zero_grad()
    loss.backward() # do back-propogation
    optimizer.step() # update the weights

    if epoch % 10 == 0:
        print("Epochs: ", epoch, "| Loss: ", loss.item())

Epochs:  0 | Loss:  4.030083656311035
Epochs:  10 | Loss:  1.2339978218078613
Epochs:  20 | Loss:  0.6220076680183411
Epochs:  30 | Loss:  0.6414700150489807
Epochs:  40 | Loss:  0.5830680131912231
Epochs:  50 | Loss:  0.5606587529182434
Epochs:  60 | Loss:  0.5560398101806641
Epochs:  70 | Loss:  0.5519967675209045
Epochs:  80 | Loss:  0.5480656027793884
Epochs:  90 | Loss:  0.5444164872169495

## Applying Activation function

In [22]:
class BCModelAF(nn.Module):
    def __init__(self):
        super(BCModelAF, self).__init__()
    
        # layer 
        self.fc1 = nn.Linear(11, 22)
        self.relu1 = nn.ReLU()
    
        self.fc2 = nn.Linear(22, 44)
        self.relu2 = nn.ReLU()
        
        self.fc3 = nn.Linear(44, 22)
        self.relu3 = nn.ReLU()
        
        self.fc4 = nn.Linear(22, 1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, x):
     # layer 1 of FNN 
      out = self.fc1(x)
      out = self.relu1(out)

    # layer 2 of FNN 
      out = self.fc2(out)
      out = self.relu2(out)

    # layer 3 of FNN
      out = self.fc3(out)
      out = self.relu3(out)

    # layer 4 of FNN
      out = self.fc4(out)
      out = self.sigmoid(out)
        
      return out

In [23]:
my_model = BCModelAF()

In [24]:
my_model.to(device=torch.device("cuda"))

BCModelAF(
  (fc1): Linear(in_features=11, out_features=22, bias=True)
  (relu1): ReLU()
  (fc2): Linear(in_features=22, out_features=44, bias=True)
  (relu2): ReLU()
  (fc3): Linear(in_features=44, out_features=22, bias=True)
  (relu3): ReLU()
  (fc4): Linear(in_features=22, out_features=1, bias=True)
  (sigmoid): Sigmoid()
)

In [25]:
# loss function
loss_function = nn.BCELoss()

# optimizer
optimizer = torch.optim.Adam(my_model.parameters(), lr=0.001)

In [26]:
X_train_tensor = X_train_tensor.to(device=torch.device("cuda"))
y_train_tensor = y_train_tensor.to(device=torch.device("cuda"))

epoches = 101

for epoch in range(epoches):
    # put model on training mode 
    model.train()

    y_target = y_train_tensor.unsqueeze(dim=1).float()

    out = my_model(X_train_tensor)
    loss = loss_function(out, y_target)

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    if epoch % 10 == 0:
        print("Epochs: ", epoch, "| Loss:", loss.item())

Epochs:  0 | Loss: 0.9630364775657654
Epochs:  10 | Loss: 0.687758207321167
Epochs:  20 | Loss: 0.6740186810493469
Epochs:  30 | Loss: 0.657046914100647
Epochs:  40 | Loss: 0.6345445513725281
Epochs:  50 | Loss: 0.5935966372489929
Epochs:  60 | Loss: 0.566180944442749
Epochs:  70 | Loss: 0.5488665103912354
Epochs:  80 | Loss: 0.5353196263313293
Epochs:  90 | Loss: 0.5276868343353271
Epochs:  100 | Loss: 0.5215113759040833

# Monitoring model training using wandb(Weights and Biases)

In [27]:
import random

import wandb

# Start a new wandb run to track this script.
run = wandb.init(
    # Set the wandb entity where your project will be logged (generally your team name).
    entity="aishwaryapatil845-aish-com",
    # Set the wandb project where this run will be logged.
    project="my-awesome-project",
    # Track hyperparameters and run metadata.
    config={
        "learning_rate": 0.001,
        "architecture": "FNN",
        "dataset": "Heart_Disease Dataset",
        "epochs": 500,
    },
)

wandb: ERROR Failed to detect the name of this notebook. You can set it manually with the WANDB_NOTEBOOK_NAME environment variable to enable code saving.
wandb: [wandb.login()] Loaded credentials for https://api.wandb.ai from /home/aishwarya/.netrc.
wandb: Currently logged in as: aishwaryapatil845 (aishwaryapatil845-aish-com) to https://api.wandb.ai. Use `wandb login --relogin` to force relogin

In [28]:
X_train_tensor = X_train_tensor.to(device=torch.device("cuda"))
y_train_tensor = y_train_tensor.to(device=torch.device("cuda"))

epoches = 500

for epoch in range(epoches):
    # put model on training mode 
    model.train()

    y_target = y_train_tensor.unsqueeze(dim=1).float()

    out = my_model(X_train_tensor)
    loss = loss_function(out, y_target)

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    if epoch % 10 == 0:
        print("Epochs: ", epoch, "| Loss:", loss.item())
        run.log({"loss": loss.item(), "epoch": epoch})

Epochs:  0 | Loss: 0.5209910273551941
Epochs:  10 | Loss: 0.5156139135360718
Epochs:  20 | Loss: 0.5104851722717285
Epochs:  30 | Loss: 0.504891037940979
Epochs:  40 | Loss: 0.4984062612056732
Epochs:  50 | Loss: 0.4903959035873413
Epochs:  60 | Loss: 0.47853755950927734
Epochs:  70 | Loss: 0.46355968713760376
Epochs:  80 | Loss: 0.4488298296928406
Epochs:  90 | Loss: 0.4332931935787201
Epochs:  100 | Loss: 0.4187397360801697
Epochs:  110 | Loss: 0.405420184135437
Epochs:  120 | Loss: 0.39455118775367737
Epochs:  130 | Loss: 0.38665488362312317
Epochs:  140 | Loss: 0.3760940134525299
Epochs:  150 | Loss: 0.3690449893474579
Epochs:  160 | Loss: 0.3645918071269989
Epochs:  170 | Loss: 0.3601658046245575
Epochs:  180 | Loss: 0.35692816972732544
Epochs:  190 | Loss: 0.35461312532424927
Epochs:  200 | Loss: 0.35247674584388733
Epochs:  210 | Loss: 0.35027173161506653
Epochs:  220 | Loss: 0.3483908176422119
Epochs:  230 | Loss: 0.34672555327415466
Epochs:  240 | Loss: 0.3457072675228119
Epochs:  250 | Loss: 0.3437992036342621
Epochs:  260 | Loss: 0.3426104784011841
Epochs:  270 | Loss: 0.34091082215309143
Epochs:  280 | Loss: 0.33909115195274353
Epochs:  290 | Loss: 0.33771970868110657
Epochs:  300 | Loss: 0.33723533153533936
Epochs:  310 | Loss: 0.33546459674835205
Epochs:  320 | Loss: 0.33407044410705566
Epochs:  330 | Loss: 0.3325308859348297
Epochs:  340 | Loss: 0.3314101994037628
Epochs:  350 | Loss: 0.33023154735565186
Epochs:  360 | Loss: 0.3289068341255188
Epochs:  370 | Loss: 0.3280315399169922
Epochs:  380 | Loss: 0.3276905417442322
Epochs:  390 | Loss: 0.32646384835243225
Epochs:  400 | Loss: 0.32493212819099426
Epochs:  410 | Loss: 0.32333552837371826
Epochs:  420 | Loss: 0.3220004141330719
Epochs:  430 | Loss: 0.3207123577594757
Epochs:  440 | Loss: 0.32026779651641846
Epochs:  450 | Loss: 0.31842756271362305
Epochs:  460 | Loss: 0.3188346326351166
Epochs:  470 | Loss: 0.3164488673210144
Epochs:  480 | Loss: 0.31547024846076965
Epochs:  490 | Loss: 0.31823694705963135

## Comparing models using wandb

In [29]:
# Start a new wandb run to track this script.
run = wandb.init(
    # Set the wandb entity where your project will be logged (generally your team name).
    entity="aishwaryapatil845-aish-com",
    # Set the wandb project where this run will be logged.
    project="HeartModel",
    name="Epoch100",
    # Track hyperparameters and run metadata.
    config={
        "learning_rate": 0.001,
        "architecture": "FNN",
        "dataset": "Heart_Disease Dataset",
        "epochs": 100,
    },
)


X_train_tensor = X_train_tensor.to(device=torch.device("cuda"))
y_train_tensor = y_train_tensor.to(device=torch.device("cuda"))

epoches = 100

for epoch in range(epoches):
    # put model on training mode 
    model.train()

    y_target = y_train_tensor.unsqueeze(dim=1).float()

    out = my_model(X_train_tensor)
    loss = loss_function(out, y_target)

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    if epoch % 10 == 0:
        print("Epochs: ", epoch, "| Loss:", loss.item())
        run.log({"loss": loss.item(), "epoch": epoch})

Epochs:  0 | Loss: 0.3145003020763397
Epochs:  10 | Loss: 0.313497394323349
Epochs:  20 | Loss: 0.3124476373195648
Epochs:  30 | Loss: 0.31170564889907837
Epochs:  40 | Loss: 0.31064853072166443
Epochs:  50 | Loss: 0.3097427189350128
Epochs:  60 | Loss: 0.3110577166080475
Epochs:  70 | Loss: 0.30979806184768677
Epochs:  80 | Loss: 0.30763673782348633
Epochs:  90 | Loss: 0.3067612051963806

In [30]:
# 500 epoch

# Start a new wandb run to track this script.
run = wandb.init(
    # Set the wandb entity where your project will be logged (generally your team name).
    entity="aishwaryapatil845-aish-com",
    # Set the wandb project where this run will be logged.
    project="HeartModel",
    name="Epoch500",
    # Track hyperparameters and run metadata.
    config={
        "learning_rate": 0.001,
        "architecture": "FNN",
        "dataset": "Heart_Disease Dataset",
        "epochs": 500,
    },
)


X_train_tensor = X_train_tensor.to(device=torch.device("cuda"))
y_train_tensor = y_train_tensor.to(device=torch.device("cuda"))

epoches = 500

for epoch in range(epoches):
    # put model on training mode 
    model.train()

    y_target = y_train_tensor.unsqueeze(dim=1).float()

    out = my_model(X_train_tensor)
    loss = loss_function(out, y_target)

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    if epoch % 10 == 0:
        print("Epochs: ", epoch, "| Loss:", loss.item())
        run.log({"loss": loss.item(), "epoch": epoch})

Epochs:  0 | Loss: 0.3060922622680664
Epochs:  10 | Loss: 0.3076415956020355
Epochs:  20 | Loss: 0.30516257882118225
Epochs:  30 | Loss: 0.3050306737422943
Epochs:  40 | Loss: 0.30300745368003845
Epochs:  50 | Loss: 0.30320918560028076
Epochs:  60 | Loss: 0.3013593256473541
Epochs:  70 | Loss: 0.30302926898002625
Epochs:  80 | Loss: 0.3003079295158386
Epochs:  90 | Loss: 0.2994374930858612
Epochs:  100 | Loss: 0.2985367178916931
Epochs:  110 | Loss: 0.29784443974494934
Epochs:  120 | Loss: 0.29749980568885803
Epochs:  130 | Loss: 0.2966286838054657
Epochs:  140 | Loss: 0.2971336543560028
Epochs:  150 | Loss: 0.2950707972049713
Epochs:  160 | Loss: 0.29618948698043823
Epochs:  170 | Loss: 0.2939029335975647
Epochs:  180 | Loss: 0.2932170331478119
Epochs:  190 | Loss: 0.2924230992794037
Epochs:  200 | Loss: 0.2912658452987671
Epochs:  210 | Loss: 0.29182979464530945
Epochs:  220 | Loss: 0.29010289907455444
Epochs:  230 | Loss: 0.2892179787158966
Epochs:  240 | Loss: 0.28877463936805725
Epochs:  250 | Loss: 0.2904451787471771
Epochs:  260 | Loss: 0.28768447041511536
Epochs:  270 | Loss: 0.28693366050720215
Epochs:  280 | Loss: 0.2863655090332031
Epochs:  290 | Loss: 0.2886177599430084
Epochs:  300 | Loss: 0.2869201600551605
Epochs:  310 | Loss: 0.2868204712867737
Epochs:  320 | Loss: 0.28695985674858093
Epochs:  330 | Loss: 0.28408950567245483
Epochs:  340 | Loss: 0.28358304500579834
Epochs:  350 | Loss: 0.2841978967189789
Epochs:  360 | Loss: 0.2822224795818329
Epochs:  370 | Loss: 0.2818635404109955
Epochs:  380 | Loss: 0.28186386823654175
Epochs:  390 | Loss: 0.2810884118080139
Epochs:  400 | Loss: 0.28107988834381104
Epochs:  410 | Loss: 0.2803259491920471
Epochs:  420 | Loss: 0.2813292145729065
Epochs:  430 | Loss: 0.28007644414901733
Epochs:  440 | Loss: 0.27884232997894287
Epochs:  450 | Loss: 0.27826184034347534
Epochs:  460 | Loss: 0.2779679298400879
Epochs:  470 | Loss: 0.27823054790496826
Epochs:  480 | Loss: 0.2775164544582367
Epochs:  490 | Loss: 0.27657440304756165

In [31]:
# 500 epoch

# Start a new wandb run to track this script.
run = wandb.init(
    # Set the wandb entity where your project will be logged (generally your team name).
    entity="aishwaryapatil845-aish-com",
    # Set the wandb project where this run will be logged.
    project="HeartModel",
    name="Epoch500",
    # Track hyperparameters and run metadata.
    config={
        "learning_rate": 0.001,
        "architecture": "FNN",
        "dataset": "Heart_Disease Dataset",
        "epochs": 500,
    },
)


X_train_tensor = X_train_tensor.to(device=torch.device("cuda"))
y_train_tensor = y_train_tensor.to(device=torch.device("cuda"))

epoches = 500

for epoch in range(epoches):
    # put model on training mode 
    model.train()

    y_target = y_train_tensor.unsqueeze(dim=1).float()

    out = my_model(X_train_tensor)
    loss = loss_function(out, y_target)

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    if epoch % 10 == 0:
        print("Epochs: ", epoch, "| Loss:", loss.item())
        run.log({"loss": loss.item(), "epoch": epoch})

Epochs:  0 | Loss: 0.2761111855506897
Epochs:  10 | Loss: 0.27591967582702637
Epochs:  20 | Loss: 0.2761263847351074
Epochs:  30 | Loss: 0.2756749987602234
Epochs:  40 | Loss: 0.27534085512161255
Epochs:  50 | Loss: 0.2739316523075104
Epochs:  60 | Loss: 0.27338656783103943
Epochs:  70 | Loss: 0.2744278907775879
Epochs:  80 | Loss: 0.2749936282634735
Epochs:  90 | Loss: 0.2742066979408264
Epochs:  100 | Loss: 0.2724534571170807
Epochs:  110 | Loss: 0.27150797843933105
Epochs:  120 | Loss: 0.270902544260025
Epochs:  130 | Loss: 0.27120304107666016
Epochs:  140 | Loss: 0.2719501256942749
Epochs:  150 | Loss: 0.27236735820770264
Epochs:  160 | Loss: 0.27248069643974304
Epochs:  170 | Loss: 0.26971808075904846
Epochs:  180 | Loss: 0.26887455582618713
Epochs:  190 | Loss: 0.26927778124809265
Epochs:  200 | Loss: 0.2692832052707672
Epochs:  210 | Loss: 0.268184095621109
Epochs:  220 | Loss: 0.2675003409385681
Epochs:  230 | Loss: 0.26772341132164
Epochs:  240 | Loss: 0.2666340172290802
Epochs:  250 | Loss: 0.26712629199028015
Epochs:  260 | Loss: 0.2671054005622864
Epochs:  270 | Loss: 0.2672763168811798
Epochs:  280 | Loss: 0.2664746344089508
Epochs:  290 | Loss: 0.2648587226867676
Epochs:  300 | Loss: 0.2643837034702301
Epochs:  310 | Loss: 0.2650928497314453
Epochs:  320 | Loss: 0.266238272190094
Epochs:  330 | Loss: 0.26426514983177185
Epochs:  340 | Loss: 0.26320022344589233
Epochs:  350 | Loss: 0.26282191276550293
Epochs:  360 | Loss: 0.2632087767124176
Epochs:  370 | Loss: 0.2646019458770752
Epochs:  380 | Loss: 0.26314112544059753
Epochs:  390 | Loss: 0.2623307704925537
Epochs:  400 | Loss: 0.26111748814582825
Epochs:  410 | Loss: 0.26125797629356384
Epochs:  420 | Loss: 0.26157301664352417
Epochs:  430 | Loss: 0.26099562644958496
Epochs:  440 | Loss: 0.2617773711681366
Epochs:  450 | Loss: 0.26278242468833923
Epochs:  460 | Loss: 0.2597833275794983
Epochs:  470 | Loss: 0.25870439410209656
Epochs:  480 | Loss: 0.2598707675933838
Epochs:  490 | Loss: 0.26251116394996643

In [32]:
# Start a new wandb run to track this script.
run = wandb.init(
    # Set the wandb entity where your project will be logged (generally your team name).
    entity="aishwaryapatil845-aish-com",
    # Set the wandb project where this run will be logged.
    project="HeartModel",
    name="Epoch1000",
    # Track hyperparameters and run metadata.
    config={
        "learning_rate": 0.001,
        "architecture": "FNN",
        "dataset": "Heart_Disease Dataset",
        "epochs": 1000,
    },
)


X_train_tensor = X_train_tensor.to(device=torch.device("cuda"))
y_train_tensor = y_train_tensor.to(device=torch.device("cuda"))

epoches = 1000

for epoch in range(epoches):
    # put model on training mode 
    model.train()

    y_target = y_train_tensor.unsqueeze(dim=1).float()

    out = my_model(X_train_tensor)
    loss = loss_function(out, y_target)

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    if epoch % 10 == 0:
        print("Epochs: ", epoch, "| Loss:", loss.item())
        run.log({"loss": loss.item(), "epoch": epoch})

Epochs:  0 | Loss: 0.25969311594963074
Epochs:  10 | Loss: 0.25867152214050293
Epochs:  20 | Loss: 0.25740283727645874
Epochs:  30 | Loss: 0.2576093077659607
Epochs:  40 | Loss: 0.2575733959674835
Epochs:  50 | Loss: 0.2562630772590637
Epochs:  60 | Loss: 0.25554266571998596
Epochs:  70 | Loss: 0.2575789988040924
Epochs:  80 | Loss: 0.25605109333992004
Epochs:  90 | Loss: 0.25698086619377136
Epochs:  100 | Loss: 0.2546650171279907
Epochs:  110 | Loss: 0.2556968331336975
Epochs:  120 | Loss: 0.25439390540122986
Epochs:  130 | Loss: 0.25427475571632385
Epochs:  140 | Loss: 0.25648990273475647
Epochs:  150 | Loss: 0.25339600443840027
Epochs:  160 | Loss: 0.2531808018684387
Epochs:  170 | Loss: 0.25278207659721375
Epochs:  180 | Loss: 0.2527231276035309
Epochs:  190 | Loss: 0.25314265489578247
Epochs:  200 | Loss: 0.25157690048217773
Epochs:  210 | Loss: 0.2516935467720032
Epochs:  220 | Loss: 0.25549572706222534
Epochs:  230 | Loss: 0.2511861026287079
Epochs:  240 | Loss: 0.25019949674606323
Epochs:  250 | Loss: 0.2502836287021637
Epochs:  260 | Loss: 0.2542036473751068
Epochs:  270 | Loss: 0.2504246234893799
Epochs:  280 | Loss: 0.25050386786460876
Epochs:  290 | Loss: 0.2493802011013031
Epochs:  300 | Loss: 0.24870826303958893
Epochs:  310 | Loss: 0.24866029620170593
Epochs:  320 | Loss: 0.2490106225013733
Epochs:  330 | Loss: 0.2495647668838501
Epochs:  340 | Loss: 0.24938391149044037
Epochs:  350 | Loss: 0.2483590543270111
Epochs:  360 | Loss: 0.24725393950939178
Epochs:  370 | Loss: 0.24705255031585693
Epochs:  380 | Loss: 0.24653741717338562
Epochs:  390 | Loss: 0.24969631433486938
Epochs:  400 | Loss: 0.248961940407753
Epochs:  410 | Loss: 0.24648505449295044
Epochs:  420 | Loss: 0.2472328096628189
Epochs:  430 | Loss: 0.2480507642030716
Epochs:  440 | Loss: 0.24557779729366302
Epochs:  450 | Loss: 0.2458060383796692
Epochs:  460 | Loss: 0.24526453018188477
Epochs:  470 | Loss: 0.24538064002990723
Epochs:  480 | Loss: 0.2456757128238678
Epochs:  490 | Loss: 0.24474428594112396
Epochs:  500 | Loss: 0.24475204944610596
Epochs:  510 | Loss: 0.2500430941581726
Epochs:  520 | Loss: 0.24586287140846252
Epochs:  530 | Loss: 0.24309749901294708
Epochs:  540 | Loss: 0.24265648424625397
Epochs:  550 | Loss: 0.2437228411436081
Epochs:  560 | Loss: 0.2436549961566925
Epochs:  570 | Loss: 0.24326463043689728
Epochs:  580 | Loss: 0.24225486814975739
Epochs:  590 | Loss: 0.24165543913841248
Epochs:  600 | Loss: 0.24227730929851532
Epochs:  610 | Loss: 0.24173974990844727
Epochs:  620 | Loss: 0.24076560139656067
Epochs:  630 | Loss: 0.24310451745986938
Epochs:  640 | Loss: 0.2399202585220337
Epochs:  650 | Loss: 0.24105708301067352
Epochs:  660 | Loss: 0.24008417129516602
Epochs:  670 | Loss: 0.24153448641300201
Epochs:  680 | Loss: 0.2392822504043579
Epochs:  690 | Loss: 0.23953001201152802
Epochs:  700 | Loss: 0.24369283020496368
Epochs:  710 | Loss: 0.23796164989471436
Epochs:  720 | Loss: 0.23927870392799377
Epochs:  730 | Loss: 0.23705792427062988
Epochs:  740 | Loss: 0.23680222034454346
Epochs:  750 | Loss: 0.23643642663955688
Epochs:  760 | Loss: 0.2370036095380783
Epochs:  770 | Loss: 0.23913852870464325
Epochs:  780 | Loss: 0.2356685847043991
Epochs:  790 | Loss: 0.2363186776638031
Epochs:  800 | Loss: 0.23571789264678955
Epochs:  810 | Loss: 0.2372228354215622
Epochs:  820 | Loss: 0.23880253732204437
Epochs:  830 | Loss: 0.23464931547641754
Epochs:  840 | Loss: 0.235695943236351
Epochs:  850 | Loss: 0.2347394824028015
Epochs:  860 | Loss: 0.23426656424999237
Epochs:  870 | Loss: 0.2339298576116562
Epochs:  880 | Loss: 0.23369325697422028
Epochs:  890 | Loss: 0.233304962515831
Epochs:  900 | Loss: 0.2345537394285202
Epochs:  910 | Loss: 0.23253773152828217
Epochs:  920 | Loss: 0.23223842680454254
Epochs:  930 | Loss: 0.23713800311088562
Epochs:  940 | Loss: 0.2343919426202774
Epochs:  950 | Loss: 0.2333458662033081
Epochs:  960 | Loss: 0.235178604722023
Epochs:  970 | Loss: 0.23233354091644287
Epochs:  980 | Loss: 0.23087453842163086
Epochs:  990 | Loss: 0.23065932095050812

### Multiclass Classification
- Has more than two classes 
- Using iris dataset which has more than 2 classes (3 class)

In [79]:
# Load dataset using scikit-learn
from sklearn.datasets import load_iris

data = load_iris()
data.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

- Lets check number of classes (target names)

In [80]:
print("Target names(classes): ", data["target_names"], "\nTotal number of classes: ", len(data["target_names"]))

Target names(classes):  ['setosa' 'versicolor' 'virginica']
Total number of classes:  3

In [81]:
X = data["data"] # input
y = data["target"] # output

In [82]:
X.shape, y.shape

((150, 4), (150,))

In [83]:
# data type of X and y
type(X), type(y)

(numpy.ndarray, numpy.ndarray)

- So there are numpy array therefore they can't work with our pytorch model
- Lets connect these X and y into tensors

In [84]:
import torch

In [110]:
device = "cuda" if torch.cuda.is_available() else "cpu"

X = torch.tensor(X, dtype=torch.float32).to(device)
y = torch.tensor(y, dtype=torch.long).to(device)

/tmp/ipykernel_6279/1405115077.py:3: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  X = torch.tensor(X, dtype=torch.float32).to(device)
/tmp/ipykernel_6279/1405115077.py:4: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  y = torch.tensor(y, dtype=torch.long).to(device)

In [111]:
type(X), type(y)

(torch.Tensor, torch.Tensor)

- lets unsqueeze `y`

In [112]:
y.size()

torch.Size([150])

In [113]:
#y = y.unsqueeze(dim=1).to(device=torch.device("cuda"))
#y.size()

- Here we have converted our numpy array dataset into tensor
- Now lets split our data into 80 and 20 percent ratio using scikit-learn `train_test_split`

In [114]:
from sklearn.model_selection import train_test_split

In [115]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [116]:
X_train.size(), X_test.size(), y_train.size(), y_test.size()

(torch.Size([120, 4]),
 torch.Size([30, 4]),
 torch.Size([120]),
 torch.Size([30]))

In [117]:
X_train.shape

torch.Size([120, 4])

In [118]:
# Model 
class MCCModel(nn.Module):
    def __init__(self):
        super(MCCModel, self).__init__()

        # layer 
        self.fc1 = nn.Linear(4, 8)
        self.fc2 = nn.Linear(8, 16)
        self.fc3 = nn.Linear(16, 8)
        self.fc4 = nn.Linear(8, 3)

    def forward(self, x):
        x = self.fc1(x)
        x = self.fc2(x)
        x = self.fc3(x)
        x = self.fc4(x)

        return x

In [119]:
multiclass_model = MCCModel()
multiclass_model.to(device=torch.device("cuda"))

MCCModel(
  (fc1): Linear(in_features=4, out_features=8, bias=True)
  (fc2): Linear(in_features=8, out_features=16, bias=True)
  (fc3): Linear(in_features=16, out_features=8, bias=True)
  (fc4): Linear(in_features=8, out_features=3, bias=True)
)

In [120]:
# loss function 
loss_function = nn.CrossEntropyLoss()

# optimizer 
optimizer = torch.optim.Adam(multiclass_model.parameters(), lr=0.001)

In [121]:
# training loop 
epoches = 100 

for epoch in range(epoches):
    multiclass_model.train() # put model in training mode

    out = multiclass_model(X_train)
    loss = loss_function(out, y_train)

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    if epoch % 10 == 0:
        print("Epochs: ", epoch, "| Loss: ", loss.item())

Epochs:  0 | Loss:  1.3495932817459106
Epochs:  10 | Loss:  1.212422490119934
Epochs:  20 | Loss:  1.1235878467559814
Epochs:  30 | Loss:  1.0600258111953735
Epochs:  40 | Loss:  1.0043805837631226
Epochs:  50 | Loss:  0.9444148540496826
Epochs:  60 | Loss:  0.873837411403656
Epochs:  70 | Loss:  0.7925665378570557
Epochs:  80 | Loss:  0.7060229182243347
Epochs:  90 | Loss:  0.6239306330680847

## Evaluate Model

In [122]:
from sklearn.metrics import classification_report 

multiclass_model.eval()

# 1. Get the raw predictions (logists)
y_pred_values = multiclass_model(X_test)

# 2. Find the predicted class (argmax along dimension 1)
# 3. Move the result to the CPU, detach, and convert to numpy
y_pred = y_pred_values.argmax(dim=1).cpu().detach().numpy()

In [123]:
print(classification_report(y_test.to(device=torch.device("cpu")), y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      0.11      0.20         9
           2       0.58      1.00      0.73        11

    accuracy                           0.73        30
   macro avg       0.86      0.70      0.64        30
weighted avg       0.85      0.73      0.66        30