# My first FFN

# Classification 
---
Types of classification: https://www.geeksforgeeks.org/machine-learning/getting-started-with-classification/

---

- Binary Classification

- Loading our binary classification data

In [1]:
import pandas as pd

In [2]:
data = pd.read_csv("Datasets/heart.csv")

data.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0

In [3]:
# Seperating features and target as X and Y
X = data.drop("HeartDisease", axis=1)
y = data["HeartDisease"]

X.shape, y.shape

((918, 11), (918,))

In [4]:
X

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up
...,...,...,...,...,...,...,...,...,...,...,...
913,45,M,TA,110,264,0,Normal,132,N,1.2,Flat
914,68,M,ASY,144,193,1,Normal,141,N,3.4,Flat
915,57,M,ASY,130,131,0,Normal,115,Y,1.2,Flat
916,57,F,ATA,130,236,0,LVH,174,N,0.0,Flat
917,38,M,NAP,138,175,0,Normal,173,N,0.0,Up

In [5]:
y

0      0
1      1
2      0
3      1
4      0
      ..
913    1
914    1
915    1
916    1
917    0
Name: HeartDisease, Length: 918, dtype: int64

In [6]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
col = ["Sex", "ChestPainType", "RestingECG", "ExerciseAngina", "ST_Slope"]

X[col] = X[col].apply(le.fit_transform)

X.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope
0,40,1,1,140,289,0,1,172,0,0.0,2
1,49,0,2,160,180,0,1,156,0,1.0,1
2,37,1,1,130,283,0,2,98,0,0.0,2
3,48,0,0,138,214,0,1,108,1,1.5,1
4,54,1,2,150,195,0,1,122,0,0.0,2

- Train test split data (80% training, 20% testing)

In [7]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

X_train.shape, X_test.shape, y_train.shape, y_test.shape

((734, 11), (184, 11), (734,), (184,))

In [8]:
# Convert data to tensors

import torch

X_train_tensor = torch.tensor(X_train.values, dtype=torch.float)
X_test_tensor = torch.tensor(X_test.values, dtype=torch.float)

y_train_tensor = torch.tensor(y_train.values, dtype=torch.long)
y_test_tensor = torch.tensor(y_test.values, dtype=torch.long)

- Building classification model

In [9]:
import torch
import torch.nn as nn

In [10]:
model = nn.Sequential(
    # Layer 1
    nn.Linear(11, 22),
    nn.ReLU(),

    # Layer 2
    nn.Linear(22, 44),
    nn.ReLU(),

    # Layer 3
    nn.Linear(44, 22),
    nn.ReLU(),

    # Layer 4
    nn.Linear(22, 1),
    nn.Sigmoid()
)

print(model)

Sequential(
  (0): Linear(in_features=11, out_features=22, bias=True)
  (1): ReLU()
  (2): Linear(in_features=22, out_features=44, bias=True)
  (3): ReLU()
  (4): Linear(in_features=44, out_features=22, bias=True)
  (5): ReLU()
  (6): Linear(in_features=22, out_features=1, bias=True)
  (7): Sigmoid()
)

In [11]:
single_layer_example = nn.Linear(11, 22)

In [12]:
single_layer_example(X_train_tensor).shape

torch.Size([734, 22])

In [13]:
# Now decide out loss function for binary classification task

loss_function = nn.BCELoss()

# decide the optimizer we will be using
optimizer = torch.optim.Adam(model.parameters(), lr=0.01)

In [14]:
from sklearn.metrics import accuracy_score

In [15]:
# training loop for our model

for epoch in range(101):
    model.train() # Good practice
    out = model(X_train_tensor)
    loss = loss_function(out, y_train_tensor.unsqueeze(dim=1).float())

    optimizer.zero_grad() # Clears old gradients, NOT weights
    loss.backward()
    optimizer.step()

    # Evaluation Mode
    model.eval() 
    with torch.no_grad(): # Saves memory/time during testing
        y_pred = model(X_test_tensor)
        y_pred_class = (y_pred > 0.5).int()

    # Now calculate accuracy
    accuracy = accuracy_score(y_test_tensor.unsqueeze(dim=1).float().detach().numpy(), y_pred_class.detach().numpy())

    if epoch % 10 == 0:
        print("Current epoch: ", epoch, "| And current loss: ", loss.item(), "| Model Accuracy: ", accuracy)

Current epoch:  0 | And current loss:  1.3141015768051147 | Model Accuracy:  0.5815217391304348
Current epoch:  10 | And current loss:  0.6095088124275208 | Model Accuracy:  0.6902173913043478
Current epoch:  20 | And current loss:  0.6068292260169983 | Model Accuracy:  0.6358695652173914
Current epoch:  30 | And current loss:  0.5854557752609253 | Model Accuracy:  0.657608695652174
Current epoch:  40 | And current loss:  0.5471241474151611 | Model Accuracy:  0.6739130434782609
Current epoch:  50 | And current loss:  0.5090667009353638 | Model Accuracy:  0.6956521739130435
Current epoch:  60 | And current loss:  0.48744410276412964 | Model Accuracy:  0.717391304347826
Current epoch:  70 | And current loss:  0.4605482518672943 | Model Accuracy:  0.7554347826086957
Current epoch:  80 | And current loss:  0.43760403990745544 | Model Accuracy:  0.8043478260869565
Current epoch:  90 | And current loss:  0.4151339530944824 | Model Accuracy:  0.8043478260869565
Current epoch:  100 | And current loss:  0.3477875292301178 | Model Accuracy:  0.8315217391304348

# Classic Pytorch Model(Recommended) # IMP

In [16]:
# Example class creation - demo practice
class ExampleClass:
    def __init__(self):
        print("Hello")
        # Use of self key on variable
        self.a = 1
        print(self.a)
        
    # Method
    def forward(self, name):
        print("Your name is:", name)
        # Update variable having self key
        self.a = 100
        print(self.a)
        

# object = class()
a = ExampleClass()

# calling a method for class ExampleClass with name as input parameter
a.forward(name="Aish")

Hello
1
Your name is: Aish
100

- To create a Deep learning AI model in pytorch we use classes.

In [17]:
class BCModel(nn.Module):
    def __init__(self):
        super(BCModel, self).__init__() # Calling nn.Module constructor from BCModel constructor

        # Model layer 
        self.fc1 = nn.Linear(11, 22)
        self.fc2 = nn.Linear(22, 44)
        self.fc3 = nn.Linear(44, 22)
        self.fc4 = nn.Linear(22, 1)

        self.sigmoid = nn.Sigmoid()

    def forward(self, x):
        out = self.fc1(x)
        out = self.fc2(out)
        out = self.fc3(out)
        out = self.fc4(out)
        out = self.sigmoid(out)

        return out

In [18]:
# object = class name
my_model = BCModel()
my_model.to(device=torch.device("cuda"))

BCModel(
  (fc1): Linear(in_features=11, out_features=22, bias=True)
  (fc2): Linear(in_features=22, out_features=44, bias=True)
  (fc3): Linear(in_features=44, out_features=22, bias=True)
  (fc4): Linear(in_features=22, out_features=1, bias=True)
  (sigmoid): Sigmoid()
)

In [19]:
# loss function for Binary Classification - Binary Cross Entropy
loss_function = nn.BCELoss()

In [20]:
# Optimizer - Adam
optimizer = torch.optim.Adam(my_model.parameters(), lr=0.001)

In [22]:
# training Binary Classification Model
X_train_tensor = X_train_tensor.to(device=torch.device("cuda"))
y_train_tensor = y_train_tensor.to(device=torch.device("cuda"))
epochs = 100

for epoch in range(epochs):
    # put model in training mode 
    my_model.train()

    # y_train target for X_train
    y_target = y_train_tensor.unsqueeze(dim=1).float()

    # predict value
    out = my_model(X_train_tensor)
    # calculate loss between predicted value and actual value of input x
    loss = loss_function(out, y_target)

    # now adjust the values of weights and biases in neurons using optimizer and loss
    optimizer.zero_grad()
    loss.backward() # do back-propogation
    optimizer.step() # update the weights

    if epoch % 10 == 0:
        print("Epochs: ", epoch, "| Loss: ", loss.item())

Epochs:  0 | Loss:  0.36490586400032043
Epochs:  10 | Loss:  0.3641834557056427
Epochs:  20 | Loss:  0.3788556754589081
Epochs:  30 | Loss:  0.36552315950393677
Epochs:  40 | Loss:  0.36306723952293396
Epochs:  50 | Loss:  0.36159446835517883
Epochs:  60 | Loss:  0.3608439862728119
Epochs:  70 | Loss:  0.36039969325065613
Epochs:  80 | Loss:  0.35979318618774414
Epochs:  90 | Loss:  0.35930269956588745

## Applying Activation function

In [26]:
class BCModelAF(nn.Module):
    def __init__(self):
        super(BCModelAF, self).__init__()
    
        # layer 
        self.fc1 = nn.Linear(11, 22)
        self.relu1 = nn.ReLU()
    
        self.fc2 = nn.Linear(22, 44)
        self.relu2 = nn.ReLU()
        
        self.fc3 = nn.Linear(44, 22)
        self.relu3 = nn.ReLU()
        
        self.fc4 = nn.Linear(22, 1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, x):
     # layer 1 of FNN 
      out = self.fc1(x)
      out = self.relu1(out)

    # layer 2 of FNN 
      out = self.fc2(out)
      out = self.relu2(out)

    # layer 3 of FNN
      out = self.fc3(out)
      out = self.relu3(out)

    # layer 4 of FNN
      out = self.fc4(out)
      out = self.sigmoid(out)
        
      return out

In [27]:
my_model = BCModelAF()

In [32]:
my_model.to(device=torch.device("cuda"))

BCModelAF(
  (fc1): Linear(in_features=11, out_features=22, bias=True)
  (relu1): ReLU()
  (fc2): Linear(in_features=22, out_features=44, bias=True)
  (relu2): ReLU()
  (fc3): Linear(in_features=44, out_features=22, bias=True)
  (relu3): ReLU()
  (fc4): Linear(in_features=22, out_features=1, bias=True)
  (sigmoid): Sigmoid()
)

In [33]:
# loss function
loss_function = nn.BCELoss()

# optimizer
optimizer = torch.optim.Adam(my_model.parameters(), lr=0.001)

In [34]:
X_train_tensor = X_train_tensor.to(device=torch.device("cuda"))
y_train_tensor = y_train_tensor.to(device=torch.device("cuda"))

epoches = 101

for epoch in range(epoches):
    # put model on training mode 
    model.train()

    y_target = y_train_tensor.unsqueeze(dim=1).float()

    out = my_model(X_train_tensor)
    loss = loss_function(out, y_target)

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    if epoch % 10 == 0:
        print("Epochs: ", epoch, "| Loss:", loss.item())

Epochs:  0 | Loss: 4.9913225173950195
Epochs:  10 | Loss: 0.9011608958244324
Epochs:  20 | Loss: 0.8866009712219238
Epochs:  30 | Loss: 0.7714970111846924
Epochs:  40 | Loss: 0.6283795237541199
Epochs:  50 | Loss: 0.591643750667572
Epochs:  60 | Loss: 0.5637290477752686
Epochs:  70 | Loss: 0.552648663520813
Epochs:  80 | Loss: 0.545718252658844
Epochs:  90 | Loss: 0.5408397316932678
Epochs:  100 | Loss: 0.5360256433486938

# Monitoring model training using wandb(Weights and Biases)

In [36]:
import random

import wandb

# Start a new wandb run to track this script.
run = wandb.init(
    # Set the wandb entity where your project will be logged (generally your team name).
    entity="aishwaryapatil845-aish-com",
    # Set the wandb project where this run will be logged.
    project="my-awesome-project",
    # Track hyperparameters and run metadata.
    config={
        "learning_rate": 0.001,
        "architecture": "FNN",
        "dataset": "Heart_Disease Dataset",
        "epochs": 500,
    },
)

In [37]:
X_train_tensor = X_train_tensor.to(device=torch.device("cuda"))
y_train_tensor = y_train_tensor.to(device=torch.device("cuda"))

epoches = 500

for epoch in range(epoches):
    # put model on training mode 
    model.train()

    y_target = y_train_tensor.unsqueeze(dim=1).float()

    out = my_model(X_train_tensor)
    loss = loss_function(out, y_target)

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    if epoch % 10 == 0:
        print("Epochs: ", epoch, "| Loss:", loss.item())
        run.log({"loss": loss.item(), "epoch": epoch})

Epochs:  0 | Loss: 0.5354811549186707
Epochs:  10 | Loss: 0.5301845669746399
Epochs:  20 | Loss: 0.5244994759559631
Epochs:  30 | Loss: 0.5178558230400085
Epochs:  40 | Loss: 0.5105375647544861
Epochs:  50 | Loss: 0.502001166343689
Epochs:  60 | Loss: 0.4927770495414734
Epochs:  70 | Loss: 0.4825555682182312
Epochs:  80 | Loss: 0.471566766500473
Epochs:  90 | Loss: 0.46007469296455383
Epochs:  100 | Loss: 0.4484926462173462
Epochs:  110 | Loss: 0.4368247091770172
Epochs:  120 | Loss: 0.4249669015407562
Epochs:  130 | Loss: 0.41403713822364807
Epochs:  140 | Loss: 0.4044601023197174
Epochs:  150 | Loss: 0.39493507146835327
Epochs:  160 | Loss: 0.3850337862968445
Epochs:  170 | Loss: 0.3815670907497406
Epochs:  180 | Loss: 0.37069985270500183
Epochs:  190 | Loss: 0.36527878046035767
Epochs:  200 | Loss: 0.3601369857788086
Epochs:  210 | Loss: 0.3561391830444336
Epochs:  220 | Loss: 0.35286372900009155
Epochs:  230 | Loss: 0.34947317838668823
Epochs:  240 | Loss: 0.3470117747783661
Epochs:  250 | Loss: 0.3465465009212494
Epochs:  260 | Loss: 0.34246641397476196
Epochs:  270 | Loss: 0.339840829372406
Epochs:  280 | Loss: 0.33801937103271484
Epochs:  290 | Loss: 0.33681178092956543
Epochs:  300 | Loss: 0.3335104286670685
Epochs:  310 | Loss: 0.33229804039001465
Epochs:  320 | Loss: 0.3295702338218689
Epochs:  330 | Loss: 0.3279208242893219
Epochs:  340 | Loss: 0.3265443742275238
Epochs:  350 | Loss: 0.3263339102268219
Epochs:  360 | Loss: 0.32385626435279846
Epochs:  370 | Loss: 0.32290881872177124
Epochs:  380 | Loss: 0.3213319778442383
Epochs:  390 | Loss: 0.32097768783569336
Epochs:  400 | Loss: 0.31939542293548584
Epochs:  410 | Loss: 0.3184008300304413
Epochs:  420 | Loss: 0.3170224726200104
Epochs:  430 | Loss: 0.31915780901908875
Epochs:  440 | Loss: 0.3184657096862793
Epochs:  450 | Loss: 0.3142790198326111
Epochs:  460 | Loss: 0.3145332336425781
Epochs:  470 | Loss: 0.3125970959663391
Epochs:  480 | Loss: 0.3120994567871094
Epochs:  490 | Loss: 0.3114553987979889

wandb: WARNING Fatal error while uploading data. Some run data will not be synced, but it will still be written to disk. Use `wandb sync` at the end of the run to try uploading.

## Comparing models using wandb

In [40]:
# Start a new wandb run to track this script.
run = wandb.init(
    # Set the wandb entity where your project will be logged (generally your team name).
    entity="aishwaryapatil845-aish-com",
    # Set the wandb project where this run will be logged.
    project="HeartModel",
    name="Epoch100",
    # Track hyperparameters and run metadata.
    config={
        "learning_rate": 0.001,
        "architecture": "FNN",
        "dataset": "Heart_Disease Dataset",
        "epochs": 100,
    },
)


X_train_tensor = X_train_tensor.to(device=torch.device("cuda"))
y_train_tensor = y_train_tensor.to(device=torch.device("cuda"))

epoches = 100

for epoch in range(epoches):
    # put model on training mode 
    model.train()

    y_target = y_train_tensor.unsqueeze(dim=1).float()

    out = my_model(X_train_tensor)
    loss = loss_function(out, y_target)

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    if epoch % 10 == 0:
        print("Epochs: ", epoch, "| Loss:", loss.item())
        run.log({"loss": loss.item(), "epoch": epoch})

Epochs:  0 | Loss: 0.3044722378253937
Epochs:  10 | Loss: 0.30323705077171326
Epochs:  20 | Loss: 0.30262139439582825
Epochs:  30 | Loss: 0.30256304144859314
Epochs:  40 | Loss: 0.30197668075561523
Epochs:  50 | Loss: 0.3011581301689148
Epochs:  60 | Loss: 0.3027071952819824
Epochs:  70 | Loss: 0.3025939166545868
Epochs:  80 | Loss: 0.3023335933685303
Epochs:  90 | Loss: 0.30138105154037476

In [41]:
# 500 epoch

# Start a new wandb run to track this script.
run = wandb.init(
    # Set the wandb entity where your project will be logged (generally your team name).
    entity="aishwaryapatil845-aish-com",
    # Set the wandb project where this run will be logged.
    project="HeartModel",
    name="Epoch500",
    # Track hyperparameters and run metadata.
    config={
        "learning_rate": 0.001,
        "architecture": "FNN",
        "dataset": "Heart_Disease Dataset",
        "epochs": 500,
    },
)


X_train_tensor = X_train_tensor.to(device=torch.device("cuda"))
y_train_tensor = y_train_tensor.to(device=torch.device("cuda"))

epoches = 500

for epoch in range(epoches):
    # put model on training mode 
    model.train()

    y_target = y_train_tensor.unsqueeze(dim=1).float()

    out = my_model(X_train_tensor)
    loss = loss_function(out, y_target)

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    if epoch % 10 == 0:
        print("Epochs: ", epoch, "| Loss:", loss.item())
        run.log({"loss": loss.item(), "epoch": epoch})

Epochs:  0 | Loss: 0.2992619574069977
Epochs:  10 | Loss: 0.29906973242759705
Epochs:  20 | Loss: 0.2982020080089569
Epochs:  30 | Loss: 0.29828810691833496
Epochs:  40 | Loss: 0.2995620667934418
Epochs:  50 | Loss: 0.2979850172996521
Epochs:  60 | Loss: 0.2964541018009186
Epochs:  70 | Loss: 0.2958274483680725
Epochs:  80 | Loss: 0.29576459527015686
Epochs:  90 | Loss: 0.29489853978157043
Epochs:  100 | Loss: 0.2969324588775635
Epochs:  110 | Loss: 0.2941559851169586
Epochs:  120 | Loss: 0.2936234474182129
Epochs:  130 | Loss: 0.29269376397132874
Epochs:  140 | Loss: 0.29567229747772217
Epochs:  150 | Loss: 0.29439258575439453
Epochs:  160 | Loss: 0.2932754158973694
Epochs:  170 | Loss: 0.2925719916820526
Epochs:  180 | Loss: 0.2912074029445648
Epochs:  190 | Loss: 0.2893127202987671
Epochs:  200 | Loss: 0.2895207107067108
Epochs:  210 | Loss: 0.2903442084789276
Epochs:  220 | Loss: 0.2875496447086334
Epochs:  230 | Loss: 0.29129672050476074
Epochs:  240 | Loss: 0.2870214879512787
Epochs:  250 | Loss: 0.2861805558204651
Epochs:  260 | Loss: 0.2860085368156433
Epochs:  270 | Loss: 0.28597044944763184
Epochs:  280 | Loss: 0.2864431142807007
Epochs:  290 | Loss: 0.2859266996383667
Epochs:  300 | Loss: 0.28639358282089233
Epochs:  310 | Loss: 0.28775909543037415
Epochs:  320 | Loss: 0.2840307950973511
Epochs:  330 | Loss: 0.2828793525695801
Epochs:  340 | Loss: 0.2827853262424469
Epochs:  350 | Loss: 0.28236842155456543
Epochs:  360 | Loss: 0.2824245095252991
Epochs:  370 | Loss: 0.28198498487472534
Epochs:  380 | Loss: 0.2814466655254364
Epochs:  390 | Loss: 0.2802160680294037
Epochs:  400 | Loss: 0.27985259890556335
Epochs:  410 | Loss: 0.28211891651153564
Epochs:  420 | Loss: 0.27891090512275696
Epochs:  430 | Loss: 0.2788241505622864
Epochs:  440 | Loss: 0.28024664521217346
Epochs:  450 | Loss: 0.28071141242980957
Epochs:  460 | Loss: 0.27901387214660645
Epochs:  470 | Loss: 0.27808040380477905
Epochs:  480 | Loss: 0.27597755193710327
Epochs:  490 | Loss: 0.27561065554618835

In [41]:
# 500 epoch

# Start a new wandb run to track this script.
run = wandb.init(
    # Set the wandb entity where your project will be logged (generally your team name).
    entity="aishwaryapatil845-aish-com",
    # Set the wandb project where this run will be logged.
    project="HeartModel",
    name="Epoch500",
    # Track hyperparameters and run metadata.
    config={
        "learning_rate": 0.001,
        "architecture": "FNN",
        "dataset": "Heart_Disease Dataset",
        "epochs": 500,
    },
)


X_train_tensor = X_train_tensor.to(device=torch.device("cuda"))
y_train_tensor = y_train_tensor.to(device=torch.device("cuda"))

epoches = 500

for epoch in range(epoches):
    # put model on training mode 
    model.train()

    y_target = y_train_tensor.unsqueeze(dim=1).float()

    out = my_model(X_train_tensor)
    loss = loss_function(out, y_target)

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    if epoch % 10 == 0:
        print("Epochs: ", epoch, "| Loss:", loss.item())
        run.log({"loss": loss.item(), "epoch": epoch})

Epochs:  0 | Loss: 0.2992619574069977
Epochs:  10 | Loss: 0.29906973242759705
Epochs:  20 | Loss: 0.2982020080089569
Epochs:  30 | Loss: 0.29828810691833496
Epochs:  40 | Loss: 0.2995620667934418
Epochs:  50 | Loss: 0.2979850172996521
Epochs:  60 | Loss: 0.2964541018009186
Epochs:  70 | Loss: 0.2958274483680725
Epochs:  80 | Loss: 0.29576459527015686
Epochs:  90 | Loss: 0.29489853978157043
Epochs:  100 | Loss: 0.2969324588775635
Epochs:  110 | Loss: 0.2941559851169586
Epochs:  120 | Loss: 0.2936234474182129
Epochs:  130 | Loss: 0.29269376397132874
Epochs:  140 | Loss: 0.29567229747772217
Epochs:  150 | Loss: 0.29439258575439453
Epochs:  160 | Loss: 0.2932754158973694
Epochs:  170 | Loss: 0.2925719916820526
Epochs:  180 | Loss: 0.2912074029445648
Epochs:  190 | Loss: 0.2893127202987671
Epochs:  200 | Loss: 0.2895207107067108
Epochs:  210 | Loss: 0.2903442084789276
Epochs:  220 | Loss: 0.2875496447086334
Epochs:  230 | Loss: 0.29129672050476074
Epochs:  240 | Loss: 0.2870214879512787
Epochs:  250 | Loss: 0.2861805558204651
Epochs:  260 | Loss: 0.2860085368156433
Epochs:  270 | Loss: 0.28597044944763184
Epochs:  280 | Loss: 0.2864431142807007
Epochs:  290 | Loss: 0.2859266996383667
Epochs:  300 | Loss: 0.28639358282089233
Epochs:  310 | Loss: 0.28775909543037415
Epochs:  320 | Loss: 0.2840307950973511
Epochs:  330 | Loss: 0.2828793525695801
Epochs:  340 | Loss: 0.2827853262424469
Epochs:  350 | Loss: 0.28236842155456543
Epochs:  360 | Loss: 0.2824245095252991
Epochs:  370 | Loss: 0.28198498487472534
Epochs:  380 | Loss: 0.2814466655254364
Epochs:  390 | Loss: 0.2802160680294037
Epochs:  400 | Loss: 0.27985259890556335
Epochs:  410 | Loss: 0.28211891651153564
Epochs:  420 | Loss: 0.27891090512275696
Epochs:  430 | Loss: 0.2788241505622864
Epochs:  440 | Loss: 0.28024664521217346
Epochs:  450 | Loss: 0.28071141242980957
Epochs:  460 | Loss: 0.27901387214660645
Epochs:  470 | Loss: 0.27808040380477905
Epochs:  480 | Loss: 0.27597755193710327
Epochs:  490 | Loss: 0.27561065554618835

In [42]:
# Start a new wandb run to track this script.
run = wandb.init(
    # Set the wandb entity where your project will be logged (generally your team name).
    entity="aishwaryapatil845-aish-com",
    # Set the wandb project where this run will be logged.
    project="HeartModel",
    name="Epoch1000",
    # Track hyperparameters and run metadata.
    config={
        "learning_rate": 0.001,
        "architecture": "FNN",
        "dataset": "Heart_Disease Dataset",
        "epochs": 1000,
    },
)


X_train_tensor = X_train_tensor.to(device=torch.device("cuda"))
y_train_tensor = y_train_tensor.to(device=torch.device("cuda"))

epoches = 1000

for epoch in range(epoches):
    # put model on training mode 
    model.train()

    y_target = y_train_tensor.unsqueeze(dim=1).float()

    out = my_model(X_train_tensor)
    loss = loss_function(out, y_target)

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    if epoch % 10 == 0:
        print("Epochs: ", epoch, "| Loss:", loss.item())
        run.log({"loss": loss.item(), "epoch": epoch})

Epochs:  0 | Loss: 0.2750149965286255
Epochs:  10 | Loss: 0.27951690554618835
Epochs:  20 | Loss: 0.27875083684921265
Epochs:  30 | Loss: 0.27501556277275085
Epochs:  40 | Loss: 0.2731916010379791
Epochs:  50 | Loss: 0.27297207713127136
Epochs:  60 | Loss: 0.2722070813179016
Epochs:  70 | Loss: 0.2718178629875183
Epochs:  80 | Loss: 0.27210548520088196
Epochs:  90 | Loss: 0.27758467197418213
Epochs:  100 | Loss: 0.2710604667663574
Epochs:  110 | Loss: 0.2707573473453522
Epochs:  120 | Loss: 0.27082300186157227
Epochs:  130 | Loss: 0.2703586220741272
Epochs:  140 | Loss: 0.2690790891647339
Epochs:  150 | Loss: 0.26903268694877625
Epochs:  160 | Loss: 0.2704780697822571
Epochs:  170 | Loss: 0.26851800084114075
Epochs:  180 | Loss: 0.26997682452201843
Epochs:  190 | Loss: 0.2675101161003113
Epochs:  200 | Loss: 0.26826637983322144
Epochs:  210 | Loss: 0.2691797614097595
Epochs:  220 | Loss: 0.2690514028072357
Epochs:  230 | Loss: 0.2692480981349945
Epochs:  240 | Loss: 0.26921018958091736
Epochs:  250 | Loss: 0.26733633875846863
Epochs:  260 | Loss: 0.2647905945777893
Epochs:  270 | Loss: 0.26639553904533386
Epochs:  280 | Loss: 0.26491472125053406
Epochs:  290 | Loss: 0.2661173641681671
Epochs:  300 | Loss: 0.2644028663635254
Epochs:  310 | Loss: 0.266327828168869
Epochs:  320 | Loss: 0.2632315754890442
Epochs:  330 | Loss: 0.2626170516014099
Epochs:  340 | Loss: 0.26445823907852173
Epochs:  350 | Loss: 0.2635265588760376
Epochs:  360 | Loss: 0.2626406252384186
Epochs:  370 | Loss: 0.2610146701335907
Epochs:  380 | Loss: 0.2614373564720154
Epochs:  390 | Loss: 0.2625475525856018
Epochs:  400 | Loss: 0.2640572786331177
Epochs:  410 | Loss: 0.2607792317867279
Epochs:  420 | Loss: 0.2607308626174927
Epochs:  430 | Loss: 0.2617017924785614
Epochs:  440 | Loss: 0.2588735520839691
Epochs:  450 | Loss: 0.2581803798675537
Epochs:  460 | Loss: 0.25825875997543335
Epochs:  470 | Loss: 0.2585577368736267
Epochs:  480 | Loss: 0.2559439539909363
Epochs:  490 | Loss: 0.26034674048423767
Epochs:  500 | Loss: 0.2566356658935547
Epochs:  510 | Loss: 0.25468698143959045
Epochs:  520 | Loss: 0.25498929619789124
Epochs:  530 | Loss: 0.2575712502002716
Epochs:  540 | Loss: 0.25648733973503113
Epochs:  550 | Loss: 0.25802797079086304
Epochs:  560 | Loss: 0.2544378936290741
Epochs:  570 | Loss: 0.2523079812526703
Epochs:  580 | Loss: 0.2514936625957489
Epochs:  590 | Loss: 0.254414826631546
Epochs:  600 | Loss: 0.25319257378578186
Epochs:  610 | Loss: 0.25613489747047424
Epochs:  620 | Loss: 0.2515014410018921
Epochs:  630 | Loss: 0.2492806315422058
Epochs:  640 | Loss: 0.24904458224773407
Epochs:  650 | Loss: 0.2504878342151642
Epochs:  660 | Loss: 0.25313374400138855
Epochs:  670 | Loss: 0.2490529716014862
Epochs:  680 | Loss: 0.24784164130687714
Epochs:  690 | Loss: 0.2477644979953766
Epochs:  700 | Loss: 0.24981626868247986
Epochs:  710 | Loss: 0.24834227561950684
Epochs:  720 | Loss: 0.24632181227207184
Epochs:  730 | Loss: 0.2503725588321686
Epochs:  740 | Loss: 0.24649763107299805
Epochs:  750 | Loss: 0.2452702522277832
Epochs:  760 | Loss: 0.2440037727355957
Epochs:  770 | Loss: 0.24578583240509033
Epochs:  780 | Loss: 0.2437860518693924
Epochs:  790 | Loss: 0.24370671808719635
Epochs:  800 | Loss: 0.24523089826107025
Epochs:  810 | Loss: 0.2412239909172058
Epochs:  820 | Loss: 0.2418559342622757
Epochs:  830 | Loss: 0.2446303516626358
Epochs:  840 | Loss: 0.24038325250148773
Epochs:  850 | Loss: 0.23935838043689728
Epochs:  860 | Loss: 0.23924489319324493
Epochs:  870 | Loss: 0.23975978791713715
Epochs:  880 | Loss: 0.23912858963012695
Epochs:  890 | Loss: 0.23756183683872223
Epochs:  900 | Loss: 0.24078480899333954
Epochs:  910 | Loss: 0.23763813078403473
Epochs:  920 | Loss: 0.24122531712055206
Epochs:  930 | Loss: 0.23621273040771484
Epochs:  940 | Loss: 0.2364589273929596
Epochs:  950 | Loss: 0.24328263103961945
Epochs:  960 | Loss: 0.23444584012031555
Epochs:  970 | Loss: 0.24108371138572693
Epochs:  980 | Loss: 0.23397913575172424
Epochs:  990 | Loss: 0.23323014378547668