## Student Marks Prediction using Regression Model

In [2]:
import pandas as pd

In [3]:
data = pd.read_csv('Datasets/Student_Marks.csv')

In [4]:
data.head()

   number_courses  time_study   Marks
0               3       4.508  19.202
1               4       0.096   7.734
2               4       3.133  13.811
3               6       7.909  53.018
4               8       7.811  55.299

In [5]:
X = data.drop(['Marks'], axis=1)
y = data['Marks']

In [6]:
X.head()

   number_courses  time_study
0               3       4.508
1               4       0.096
2               4       3.133
3               6       7.909
4               8       7.811

In [7]:
y.head()

0    19.202
1     7.734
2    13.811
3    53.018
4    55.299
Name: Marks, dtype: float64

- Now convert `X` and `y` into tensors

In [8]:
import torch

In [9]:
X_tensor = torch.tensor(X.values, dtype=torch.float)
y_tensor = torch.tensor(y.values, dtype=torch.float)

In [10]:
X_tensor[:5]

tensor([[3.0000, 4.5080],
        [4.0000, 0.0960],
        [4.0000, 3.1330],
        [6.0000, 7.9090],
        [8.0000, 7.8110]])

In [11]:
y_tensor[:5]

tensor([19.2020,  7.7340, 13.8110, 53.0180, 55.2990])

- train test split using sklearn

In [12]:
from sklearn.model_selection import train_test_split

In [13]:
X_train, X_test, y_train, y_test = train_test_split(X_tensor, y_tensor, test_size=0.2, random_state=42)

X_train.shape, X_test.shape, y_train.shape, y_test.shape

(torch.Size([80, 2]), torch.Size([20, 2]), torch.Size([80]), torch.Size([20]))

- Model training - Regression Model

In [14]:
import torch.nn as nn

In [15]:
class Model(nn.Module):
    def __init__(self, input_dim=2, hidden_1=10, hidden_2=20, hidden_3=10, output_dim=1):
        super(Model, self).__init__()

        
        # layers    

        self.fc1 = nn.Linear(input_dim, hidden_1) #input layer

        # hidden state - start 
        self.fc2 = nn.Linear(hidden_1, hidden_2)
        self.relu1 = nn.ReLU()
        self.do1 = nn.Dropout(0.2)
        

        self.fc3 = nn.Linear(hidden_2, hidden_3)
        self.relu2 = nn.ReLU()
        self.do2 = nn.Dropout(0.1)

        self.fc4 = nn.Linear(hidden_3, output_dim)

    def forward(self, x):
        x = self.fc1(x)

        x = self.fc2(x)
        x = self.relu1(x)
        x = self.do1(x)
        

        x = self.fc3(x)
        x = self.relu2(x)
        x = self.do2(x)
        
        x = self.fc4(x)

        return x

In [16]:
model = Model()
model

Model(
  (fc1): Linear(in_features=2, out_features=10, bias=True)
  (fc2): Linear(in_features=10, out_features=20, bias=True)
  (relu1): ReLU()
  (do1): Dropout(p=0.2, inplace=False)
  (fc3): Linear(in_features=20, out_features=10, bias=True)
  (relu2): ReLU()
  (do2): Dropout(p=0.1, inplace=False)
  (fc4): Linear(in_features=10, out_features=1, bias=True)
)

In [17]:
loss_function = nn.MSELoss()
optimizer = torch.optim.Adam(model.parameters(), lr=0.001)

In [18]:
X_train.shape

torch.Size([80, 2])

In [19]:
epoches = 101 

for epoch in range(epoches):
    model.train()

    out = model(X_train)
    loss = loss_function(out, y_train)

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    if epoch % 10 == 0:
        print("Epoch: ", epoch, "Loss: ", loss.item())

/home/aishwarya/Downloads/Notes/PyTorch_Notes/Notebooks/.venv/lib/python3.13/site-packages/torch/nn/modules/loss.py:626: UserWarning: Using a target size (torch.Size([80])) that is different to the input size (torch.Size([80, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)

Epoch:  0 Loss:  752.8074951171875
Epoch:  10 Loss:  741.8696899414062
Epoch:  20 Loss:  730.7393188476562
Epoch:  30 Loss:  719.2510375976562
Epoch:  40 Loss:  704.352783203125
Epoch:  50 Loss:  682.65234375
Epoch:  60 Loss:  648.2051391601562
Epoch:  70 Loss:  599.313232421875
Epoch:  80 Loss:  540.46728515625
Epoch:  90 Loss:  469.1983947753906
Epoch:  100 Loss:  375.65557861328125

- Lets predict

In [20]:
My_Data = torch.tensor([[1, 81.5]], dtype=torch.float)

In [21]:
model.eval()
with torch.no_grad():
    out = model(My_Data)

In [22]:
out

tensor([[56.6712]])

## Wandb model evaluation

In [23]:
import wandb

- With Dropout and 501 epoches

In [24]:
import torch.nn as nn

In [25]:
class Model(nn.Module):
    def __init__(self, input_dim=2, hidden_1=10, hidden_2=20, hidden_3=10, output_dim=1):
        super(Model, self).__init__()

        
        # layers    

        self.fc1 = nn.Linear(input_dim, hidden_1) #input layer

        # hidden state - start 
        self.fc2 = nn.Linear(hidden_1, hidden_2)
        self.relu1 = nn.ReLU()
        self.do1 = nn.Dropout(0.2)
        

        self.fc3 = nn.Linear(hidden_2, hidden_3)
        self.relu2 = nn.ReLU()
        self.do2 = nn.Dropout(0.1)

        self.fc4 = nn.Linear(hidden_3, output_dim)

    def forward(self, x):
        x = self.fc1(x)

        x = self.fc2(x)
        x = self.relu1(x)
        x = self.do1(x)
        

        x = self.fc3(x)
        x = self.relu2(x)
        x = self.do2(x)
        
        x = self.fc4(x)

        return x

In [26]:
loss_function = nn.MSELoss()
optimizer = torch.optim.Adam(model.parameters(), lr=0.001)

In [27]:
# Start a new wandb run to track this script
run = wandb.init(
    # Set the wandb entity where your project will be logged (generally your team name).
    entity ="aishwaryapatil845-aish-com",
    # Set the wandb project where this run will be logged.
    project="Student Marks Dataset",
    # name for this run 
    name = "Dropout_501",
    # Track hyperparameters and run metadat.
    config={
        "learning_rate": 0.001,
        "architecture": "FNN",
        "dataset": "student_marks.csv",
        "epoches": 501,
    }
)

epoches = 501

for epoch in range(epoches):
    model.train()

    out = model(X_train)
    loss = loss_function(out, y_train)

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    if epoch%10==0:
        print("Epoch: ", epoch, " Loss: ", loss.item())
        run.log({"loss": loss.item(), "epoch": epoch,})

wandb: [wandb.login()] Loaded credentials for https://api.wandb.ai from /home/aishwarya/.netrc.
wandb: Currently logged in as: aishwaryapatil845 (aishwaryapatil845-aish-com) to https://api.wandb.ai. Use `wandb login --relogin` to force relogin

/home/aishwarya/Downloads/Notes/PyTorch_Notes/Notebooks/.venv/lib/python3.13/site-packages/torch/nn/modules/loss.py:626: UserWarning: Using a target size (torch.Size([80])) that is different to the input size (torch.Size([80, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)

Epoch:  0  Loss:  385.5877380371094
Epoch:  10  Loss:  353.2049255371094
Epoch:  20  Loss:  305.17706298828125
Epoch:  30  Loss:  271.6437072753906
Epoch:  40  Loss:  249.58441162109375
Epoch:  50  Loss:  253.97445678710938
Epoch:  60  Loss:  249.82284545898438
Epoch:  70  Loss:  253.47640991210938
Epoch:  80  Loss:  240.5657958984375
Epoch:  90  Loss:  233.29103088378906
Epoch:  100  Loss:  231.9578857421875
Epoch:  110  Loss:  247.16827392578125
Epoch:  120  Loss:  245.10548400878906
Epoch:  130  Loss:  244.0829620361328
Epoch:  140  Loss:  231.615234375
Epoch:  150  Loss:  244.64259338378906
Epoch:  160  Loss:  237.5219268798828
Epoch:  170  Loss:  238.48268127441406
Epoch:  180  Loss:  242.03817749023438
Epoch:  190  Loss:  236.92335510253906
Epoch:  200  Loss:  241.58538818359375
Epoch:  210  Loss:  237.2061767578125
Epoch:  220  Loss:  239.70761108398438
Epoch:  230  Loss:  233.75067138671875
Epoch:  240  Loss:  229.81333923339844
Epoch:  250  Loss:  240.24728393554688
Epoch:  260  Loss:  230.7771453857422
Epoch:  270  Loss:  227.7313690185547
Epoch:  280  Loss:  236.56564331054688
Epoch:  290  Loss:  228.97723388671875
Epoch:  300  Loss:  227.49851989746094
Epoch:  310  Loss:  226.46018981933594
Epoch:  320  Loss:  239.25381469726562
Epoch:  330  Loss:  231.82395935058594
Epoch:  340  Loss:  221.78564453125
Epoch:  350  Loss:  221.4107666015625
Epoch:  360  Loss:  221.52272033691406
Epoch:  370  Loss:  214.63812255859375
Epoch:  380  Loss:  231.17401123046875
Epoch:  390  Loss:  223.0782012939453
Epoch:  400  Loss:  221.59884643554688
Epoch:  410  Loss:  218.51759338378906
Epoch:  420  Loss:  228.1798095703125
Epoch:  430  Loss:  222.19253540039062
Epoch:  440  Loss:  215.84849548339844
Epoch:  450  Loss:  221.96865844726562
Epoch:  460  Loss:  207.25250244140625
Epoch:  470  Loss:  213.3568572998047
Epoch:  480  Loss:  208.05152893066406
Epoch:  490  Loss:  213.32949829101562
Epoch:  500  Loss:  216.58763122558594

- Without Drop-Out

In [28]:
class Model(nn.Module):
    def __init__(self, input_dim=2, hidden_1=10, hidden_2=20, hidden_3=10, output_dim=1):
        super(Model, self).__init__()

        
        # layers    

        self.fc1 = nn.Linear(input_dim, hidden_1) #input layer

        # hidden state - start 
        self.fc2 = nn.Linear(hidden_1, hidden_2)
        self.relu1 = nn.ReLU()
        
        

        self.fc3 = nn.Linear(hidden_2, hidden_3)
        self.relu2 = nn.ReLU()
        

        self.fc4 = nn.Linear(hidden_3, output_dim)

    def forward(self, x):
        x = self.fc1(x)

        x = self.fc2(x)
        x = self.relu1(x)
        
        

        x = self.fc3(x)
        x = self.relu2(x)
       
        
        x = self.fc4(x)

        return x

In [29]:
model = Model()
loss_function = nn.MSELoss()
optimizer = torch.optim.Adam(model.parameters(), lr=0.001)

In [30]:
# Start a new wandb run to track this script
run = wandb.init(
    # Set the wandb entity where your project will be logged (generally your team name).
    entity ="aishwaryapatil845-aish-com",
    # Set the wandb project where this run will be logged.
    project="Student Marks Dataset",
    # name for this run 
    name = " Without_Dropout_501",
    # Track hyperparameters and run metadat.
    config={
        "learning_rate": 0.001,
        "architecture": "FNN",
        "dataset": "student_marks.csv",
        "epoches": 501,
    }
)

epoches = 501

for epoch in range(epoches):
    model.train()

    out = model(X_train)
    loss = loss_function(out, y_train)

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    if epoch%10==0:
        print("Epoch: ", epoch, " Loss: ", loss.item())
        run.log({"loss": loss.item(), "epoch": epoch,})

/home/aishwarya/Downloads/Notes/PyTorch_Notes/Notebooks/.venv/lib/python3.13/site-packages/torch/nn/modules/loss.py:626: UserWarning: Using a target size (torch.Size([80])) that is different to the input size (torch.Size([80, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)

Epoch:  0  Loss:  720.6113891601562
Epoch:  10  Loss:  711.2704467773438
Epoch:  20  Loss:  701.3240356445312
Epoch:  30  Loss:  688.9984130859375
Epoch:  40  Loss:  672.7474975585938
Epoch:  50  Loss:  651.10302734375
Epoch:  60  Loss:  622.4176635742188
Epoch:  70  Loss:  584.885498046875
Epoch:  80  Loss:  537.2089233398438
Epoch:  90  Loss:  479.982666015625
Epoch:  100  Loss:  415.813232421875
Epoch:  110  Loss:  350.4418640136719
Epoch:  120  Loss:  292.80914306640625
Epoch:  130  Loss:  252.79840087890625
Epoch:  140  Loss:  234.81405639648438
Epoch:  150  Loss:  231.67926025390625
Epoch:  160  Loss:  231.72625732421875
Epoch:  170  Loss:  230.9305419921875
Epoch:  180  Loss:  230.1332550048828
Epoch:  190  Loss:  229.59249877929688
Epoch:  200  Loss:  229.09344482421875
Epoch:  210  Loss:  228.58168029785156
Epoch:  220  Loss:  228.07492065429688
Epoch:  230  Loss:  227.5722198486328
Epoch:  240  Loss:  227.06675720214844
Epoch:  250  Loss:  226.55686950683594
Epoch:  260  Loss:  226.0430450439453
Epoch:  270  Loss:  225.5190887451172
Epoch:  280  Loss:  225.01206970214844
Epoch:  290  Loss:  224.52195739746094
Epoch:  300  Loss:  224.0312042236328
Epoch:  310  Loss:  223.54322814941406
Epoch:  320  Loss:  223.05868530273438
Epoch:  330  Loss:  222.57452392578125
Epoch:  340  Loss:  222.08123779296875
Epoch:  350  Loss:  221.57980346679688
Epoch:  360  Loss:  221.0614776611328
Epoch:  370  Loss:  220.52066040039062
Epoch:  380  Loss:  219.98976135253906
Epoch:  390  Loss:  219.5037078857422
Epoch:  400  Loss:  219.0166778564453
Epoch:  410  Loss:  218.53530883789062
Epoch:  420  Loss:  218.05999755859375
Epoch:  430  Loss:  217.59019470214844
Epoch:  440  Loss:  217.1260986328125
Epoch:  450  Loss:  216.66787719726562
Epoch:  460  Loss:  216.2161102294922
Epoch:  470  Loss:  215.77191162109375
Epoch:  480  Loss:  215.33509826660156
Epoch:  490  Loss:  214.9064483642578
Epoch:  500  Loss:  214.48553466796875

- With more neurons and no dropout , epoch=501

In [31]:
class Model(nn.Module):
    def __init__(self, input_dim=2, hidden_1=15,hidden_2=50,hidden_3=5, output_dim=1):
        super(Model, self).__init__()

        
        # layers    

        self.fc1 = nn.Linear(input_dim, hidden_1) #input layer

        # hidden state - start 
        self.fc2 = nn.Linear(hidden_1, hidden_2)
        self.relu1 = nn.ReLU()
        
        

        self.fc3 = nn.Linear(hidden_2, hidden_3)
        self.relu2 = nn.ReLU()
        

        self.fc4 = nn.Linear(hidden_3, output_dim)

    def forward(self, x):
        x = self.fc1(x)

        x = self.fc2(x)
        x = self.relu1(x)
        
        

        x = self.fc3(x)
        x = self.relu2(x)
       
        
        x = self.fc4(x)

        return x

In [32]:
model = Model()
loss_function = nn.MSELoss()
optimizer = torch.optim.Adam(model.parameters(), lr=0.001)

In [33]:
# Start a new wandb run to track this script
run = wandb.init(
    # Set the wandb entity where your project will be logged (generally your team name).
    entity ="aishwaryapatil845-aish-com",
    # Set the wandb project where this run will be logged.
    project="Student Marks Dataset",
    # name for this run 
    name = " More_neurons_Without_Dropout_501",
    # Track hyperparameters and run metadat.
    config={
        "learning_rate": 0.001,
        "architecture": "FNN",
        "dataset": "student_marks.csv",
        "epoches": 501,
    }
)

epoches = 501

for epoch in range(epoches):
    model.train()

    out = model(X_train)
    loss = loss_function(out, y_train)

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    if epoch%10==0:
        print("Epoch: ", epoch, " Loss: ", loss.item())
        run.log({"loss": loss.item(), "epoch": epoch,})

/home/aishwarya/Downloads/Notes/PyTorch_Notes/Notebooks/.venv/lib/python3.13/site-packages/torch/nn/modules/loss.py:626: UserWarning: Using a target size (torch.Size([80])) that is different to the input size (torch.Size([80, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)

Epoch:  0  Loss:  746.173828125
Epoch:  10  Loss:  742.850341796875
Epoch:  20  Loss:  740.16943359375
Epoch:  30  Loss:  735.9558715820312
Epoch:  40  Loss:  729.42626953125
Epoch:  50  Loss:  719.341064453125
Epoch:  60  Loss:  704.0526733398438
Epoch:  70  Loss:  681.109619140625
Epoch:  80  Loss:  647.8184204101562
Epoch:  90  Loss:  601.4459228515625
Epoch:  100  Loss:  540.1871337890625
Epoch:  110  Loss:  465.2735900878906
Epoch:  120  Loss:  383.33428955078125
Epoch:  130  Loss:  307.1156005859375
Epoch:  140  Loss:  252.73648071289062
Epoch:  150  Loss:  229.6620330810547
Epoch:  160  Loss:  227.6492919921875
Epoch:  170  Loss:  228.0887451171875
Epoch:  180  Loss:  227.04554748535156
Epoch:  190  Loss:  226.5045166015625
Epoch:  200  Loss:  226.28514099121094
Epoch:  210  Loss:  226.03062438964844
Epoch:  220  Loss:  225.77003479003906
Epoch:  230  Loss:  225.52671813964844
Epoch:  240  Loss:  225.2859344482422
Epoch:  250  Loss:  225.0449981689453
Epoch:  260  Loss:  224.80609130859375
Epoch:  270  Loss:  224.56146240234375
Epoch:  280  Loss:  224.30215454101562
Epoch:  290  Loss:  224.02508544921875
Epoch:  300  Loss:  223.74667358398438
Epoch:  310  Loss:  223.50112915039062
Epoch:  320  Loss:  223.2513885498047
Epoch:  330  Loss:  223.00320434570312
Epoch:  340  Loss:  222.75650024414062
Epoch:  350  Loss:  222.5108184814453
Epoch:  360  Loss:  222.26612854003906
Epoch:  370  Loss:  222.0220489501953
Epoch:  380  Loss:  221.77879333496094
Epoch:  390  Loss:  221.53619384765625
Epoch:  400  Loss:  221.29417419433594
Epoch:  410  Loss:  221.05271911621094
Epoch:  420  Loss:  220.81170654296875
Epoch:  430  Loss:  220.5709991455078
Epoch:  440  Loss:  220.3305206298828
Epoch:  450  Loss:  220.09007263183594
Epoch:  460  Loss:  219.84938049316406
Epoch:  470  Loss:  219.6083526611328
Epoch:  480  Loss:  219.3673858642578
Epoch:  490  Loss:  219.12588500976562
Epoch:  500  Loss:  218.88406372070312